### ISSUE TITLE
[Source Code] Why Ack will not change?

### ISSUE THREAD

**Issue by zjzwjcbj** [buger/goreplay#1027]
Why is it guaranteed that the messageId is unique?  Why Ack will  not change?
![image](https://user-images.githubusercontent.com/26433840/142992700-5a637fd7-60e2-4da2-b779-dd228f8e8b78.png)

**Comment by wangfeng22** [comment]
I want to know why too.

**Comment by wangfeng22** [comment]
> Why is it guaranteed that the messageId is unique? Why Ack will not change? ![image](https://user-images.githubusercontent.com/26433840/142992700-5a637fd7-60e2-4da2-b779-dd228f8e8b78.png)

Because they are a set of tcp packets.
