### ISSUE TITLE
cannot replay protocol with GoReplay PRO version

### ISSUE THREAD

**Issue by lixinkun** [buger/goreplay#1067]
my GoReplay Pro is Version:1.3.1

I have catched gRPC protocol traffic, with cmd:
./gor --input-raw :26182 --input-raw-protocol binary --output-file ./requests.gor

When I'm trying to replay this output file localhost, it doesn't work. My server didn't receive any requests.
./gor --input-file './requests*.gor' --output-binary localhost:26182

gor has no error output. Is there anything wrong with my replay cmd?

**Comment by Dao007forever** [comment]
What is the conclusion of this @lixinkun ?
