### ISSUE TITLE
cant start goreplay in docker 

### ISSUE THREAD

**Issue by y-koyamatsu** [buger/goreplay#1089]
Hi!

I try to do GoRepaly in dokcer like below Docker Fiile!

```
FROM alpine:latest
RUN wget https://github.com/buger/goreplay/releases/download/1.3.3/gor_1.3.3_x64.tar.gz
RUN tar -zxvf gor_1.3.3_x64.tar.gz
ENTRYPOINT ./gor --input-raw :8080  --output-stdout
```

> tunl0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented
Above error was happened....

How can I fix this???

```
Docker % docker run -it edaubert/goreplay:1.3.3 --input-raw :8080  --output-stdout
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
2022/05/24 07:22:12 tunl0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented
```

**Comment by sswastioyono18** [comment]
iirc some docker images arent compatible with arm64. Workaround is to add --platform=linux/amd64 in docker run/compose

**Comment by yqbjtu** [comment]
docker run -it --rm --platform=linux/amd64 gostudy/goreplay:1.3.3 --input-raw-track-response  --output-file=req.gor --input-raw :8080
2022/07/02 04:39:33 tunl0: SIOCETHTOOL(ETHTOOL_GLINK) ioctl failed: Function not implemented

when I add the --platform=linux/amd64, it still failed.

gostudy/goreplay:1.3.3  is the same with edaubert/goreplay:1.3.3

**Comment by petaluma007** [comment]
Try to add --net=host in docker run/compose.

**Comment by y-koyamatsu** [comment]
Thank you so much!
