### ISSUE TITLE
very strange question

### ISSUE THREAD

**Issue by wangfeng22** [buger/goreplay#1109]
Sometimes goreplay can barely grab the request, sometimes only the response.This phenomenon seems to be related to the size of the response message. Using jmeter to stress the 2k json message can be reproduced.

**Comment by moviewang** [comment]
add --input-raw-override-snaplen

**Comment by wangfeng22** [comment]
> 

Why does this happen? What is the function of this parameter？

**Comment by wangfeng22** [comment]
> add --input-raw-override-snaplen

Why does this happen? What is the function of this parameter

**Comment by wangfeng22** [comment]
> add --input-raw-override-snaplen

Thank you very much!!!  this solved my problem.
