### ISSUE TITLE
[Question]: How do I use the --input-raw-max-wait parameter

### ISSUE THREAD

**Issue by gcil125** [buger/goreplay#1210]
`go
# That's right
gor --input-file "a.gor" --output-http "http://127.0.0.1:50001" input-raw-max-wait 0.1s

# This is wrong
gor --input-file "a.gor" --output-http "http://127.0.0.1:50001" --input-raw-max-wait 0.1s
`
<img width="951" alt="image" src="https://github.com/buger/goreplay/assets/67992830/28fd4601-0a66-4a0d-8b55-2cbe267d1631">
<img width="946" alt="image" src="https://github.com/buger/goreplay/assets/67992830/89273454-9429-4033-a1e9-61bd2498ac8d">

**Comment by ivan-stankov-salt-security** [comment]
@gcil125 
see:
https://github.com/buger/goreplay/blob/master/settings.go#L168C48-L168C67

try
```
gor --input-file "a.gor" --output-http "http://127.0.0.1:50001/" --input-file-max-wait 0.1s
```
