### ISSUE TITLE
tool for easy spliting of large replay file into smaller ones

### ISSUE THREAD

**Issue by webervin** [buger/goreplay#152]
Would like to be able to take "first 10 minutes of requests", "last 3000 requests" or "first 5%  of requests". 
Also this tool could report basic information on saved replay file (like X request, recorded over Y time starting at Z).

**Comment by buger** [comment]
Now gor use human readable file format, much easier to parse and operate: [0.10.0](https://github.com/buger/gor/releases/tag/0.10.0)

**Comment by buger** [comment]
Partially related to this issue, now you can use date variables in file names and now it writes data in chunks: https://github.com/buger/gor/wiki/Saving-and-Replaying-from-file
