### ISSUE TITLE
Use Gor in VCR way?

### ISSUE THREAD

**Issue by dnaeon** [buger/goreplay#230]
Hi,

Can Gor be used in a way what VCR is doing?
- https://github.com/kevin1024/vcrpy

I'm interested in such a functionality similar to VCR where all requests are recorded during the first run of your code and next calls can make use of the recorded session, so sending a specific requests returns a specific response from the recorded session.

Is there such a functionality existing in Gor?

> VCR.py simplifies and speeds up tests that make HTTP requests. The first time you run code that is inside a VCR.py context manager or decorated function, VCR.py records all HTTP interactions that take place through the libraries it supports and serializes and writes them to a flat file (in yaml format by default). This flat file is called a cassette. When the relevant piece of code is executed again, VCR.py will read the serialized requests and responses from the aforementioned cassette file, and intercept any HTTP requests that it recognizes from the original test run and return the responses that corresponded to those requests. This means that the requests will not actually result in HTTP traffic, which confers several benefits including:

Thanks!

**Comment by buger** [comment]
Well, you can record even production traffic,  prepare it for development environment by filtering using simple middleware or built-in filters, and save it to file. 

Then you can put this file to your repository, and replay to your app during tests. However there is few issue to use it like this. First of all it can't be integrated (yet) as python/ruby/etc library to use directly in code. Also it won't return proper exit code if one of requests will fail, and will just continue working, or exit normally at the end.
