### ISSUE TITLE
StatsD/Graphite integration

### ISSUE THREAD

**Issue by buger** [buger/goreplay#28]
Instead of writing own stats solution #12 it make sense to integrate Gor with well known stats aggregation products like StatsD and Graphite.

**Comment by dt** [comment]
It looks like go-metrics could be useful, to provide a common API for various stats backends https://github.com/rcrowley/go-metrics

**Comment by buger** [comment]
@dt thanks for the suggestion, go-metrics looks cool.

**Comment by bharathrajbk** [comment]
@buger , when are we closing this issue? Have you finalized on the reporting solution yet?

Personally, we should write to Graphite as it has a lot of possibilities from there... we can use InfluxDB as timeseries database to capture metrics or use grafana.
[https://influxdata.com/](url)
[http://grafana.org/](url)
Any updates?

**Comment by joekiller** [comment]
My guess is that since go-metrics writes to Librato, Graphite, InfluxDB, and Ganglia. It would be the winner. As for an implementation you could look at what he wrote for #12 and hook it into the library.

I don't see any active branches regarding this.

**Comment by buger** [comment]
After releasing new version with all the bugfixes this will be one of my priorities.

**Comment by bharathrajbk** [comment]
Thanks @buger ! I will try to get the stats into go-metrics as well... I'll see how I go with it.

**Comment by ivanich** [comment]
@buger Any progress with this?

**Comment by urbanishimwe** [comment]
closing this in fever of #772
