### ISSUE TITLE
Is Gor the right tool to duplicate GPS Tracker traffic to multiple targets ?

### ISSUE THREAD

**Issue by Phantomatz** [buger/goreplay#372]
Hello, I would like to use goreplay to share the information sent by my GPS tracker via GPRS to different tracking platforms.

I plan to use my Raspi to receive the data on port XXXX of my raspi and to distribute to my NAS which is within my network and also to forward to external (worldwide) tracking platforms, to compare the features of the different platforms.

Is this feasible with gor ? Sorry for the question, but I am a complete noob wrt to IP traffic.

If you could propose another tool which is easy install and would better fit my requirements I am thankfull for each hint.

I could also run it on my Synology DS216+ but I expect its easier to get it to work on  RasPi.

My problem is that getting gor to work would take me days based on my very limited knowledge ... - therefore it would be good to know in advance if it fits my requirements or if there is another easier tool or setup which could do.

**Comment by buger** [comment]
I see, Gor definitely can do such work, but note that there should be some server which receives requests, from where Gor can capture traffic. The simplest one in your use-case can be simple netcat bash server :)

```bash
while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; sh test; } | nc -l 8080; done
```

If your GPS tracker sends HTTP requests, it's not enough just to copy traffic to difference sources; it also requires rewriting HOST header (which Gor does).

You can also check this StackOverflow question for more tools http://serverfault.com/questions/570761/how-to-duplicate-tcp-traffic-to-one-or-multiple-remote-servers-for-benchmarking

**Comment by Phantomatz** [comment]
Hello buger,
thank you very much for your answer .

I know the link you are refering to, and I will also try if the Python script could do the job, as I there is an easy install Python package for Synology available. I only see myself currently strunggling with the complete lack of knowhow on traffic shaping an the way to use such python or whatever proposed solution. I first need to dig through quite some "XXX for dummies" introductions :-) as I am not that much in IT and need to find my way around all the dummy traps :-)..

Thank you for your netcat bash server tip.
I installed netcat on my NAS and need to check to understand the script example you made.
I would expect to redirect the network traffic I would need a service running on the machine where the traffic is initially directed to (the IP:Port of a RasPi or NAS DS216 in my network). I would expect that the service running on that machine takes care of the redirection (e.g. redirection to another IP:Port within my private network and to external IP).
Why does the server need to receive requests ? I would expect that e.g in my case as the data transfer from the tracker is unidirectional to my server without and feedack channel, that this would not be required ? Or is my interpretation of the way of working of the service completely wrong ?

I downloaded gor and got it running with one of your test commands from the description ... sudo ./gor --input-raw :8000 --output-stdout and I can get my homeautomization page directed to stdout ! :-) ... First success for today !! I will dig through your documentation and video during the next days. Seems it might be easier then expected 

Thanks for the support !

**Comment by buger** [comment]
If you can tell the model of your GPS tracker, it can help. But, basic idea is that there are network protocols which expect a response like HTTP, and there is which not. 

Let's use the assumption that it is HTTP; it will mean you need some web server which receives requests, maybe logs them, and after, distribute to the multiple endpoints.

Gor is not made to receive traffic, it is made to analyse and record traffic from already running network server, that's why it required having bare minimum web server running like netcat example above. 

So Gor configuration in your case may look like this:

#### 1. Start this command on your NAS

```bash
# Running simple web server in the background, for example, you may run this command inside `screen`.
while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; } | nc -l 8080; done
```

#### 2. Configure GPS tracker to use http://nas-ip:8080 endpoint
#### 3. Run Gor to capture traffic coming to port 8080 and redirect it where you want
```bash
# Run on the same server (NAS) where your web server running
gor --input-raw :8080 --output-http http://service-1.com --output-http http://service-2.com
```
Command above will capture traffic from port 8080 and duplicate it to 2 external services 


Hope it helps ;)

**Comment by Phantomatz** [comment]
Hello buger,
I am getting closer ... 
I had to slightly change the netcat command due to Synology special installation:
while true; do { echo -e 'HTTP/1.1 200 OK\r\n'; } | /opt/bin/netcat-nc -l 8080; done 
works fine without any error message.
Gor also seem to work
sudo /volume1/web/gor  --input-raw :8080 --output-http http://MyNASID:55013 --output-http http://193.193.165.166:20912
--> The 193.193.165.166:20912 is the IP:Port for GPS TRace service from Orange.
I just need to recharge and reconfigure my GPS trackers (currently I have several in evaluation).
Most likely I will use the Incutex TK5000 Tracker, as it is DNS capable (compared to most other trackers which need a fixed IP).
I will further debug during the weekend ! Looking foward to get this issue fixed.
I'll update here then with a brief description :-)

**Comment by Phantomatz** [comment]
BTW: 
To easy adapt testing I have mapped in my Internet Router the original port to my NAS (MyNasID:55013 as TraccarPort fot tracker information) to the NAS Port 8080 (which is connected to the netcat as mentioned above).
At the end it might be even an option to have more then 2 port duplicated (Tracker for my car and Ebike and the same for my wife) ..> would it require then 4 parallel instances of netcat & gor running ?
