### ISSUE TITLE
Gor does not dump traffic in file immideately

### ISSUE THREAD

**Issue by lezhnev74** [buger/goreplay#381]
Hey!

I use Gor to capture http requests (and responses) to debug our API. But when http request-response is finished - Gor still keeps it somewhere in the buffers until I make another request, then Gor flushes previous one into file.

Did anyone face this issue? Does Gor have some flag to dump things immideately to file?

My current command to run Gor looks like this:
```
sudo ~/gocode/gor --input-raw :8880 --input-raw-track-response --output-file ./dump_http/%Y%m%d_%H%M%S.log --output-file-append
```

**Comment by buger** [comment]
Hello! When writing to file there is an internal buffer, and get flushed after some time or until the buffer is overfilled, so some delay is expected. But I want you to tell me how big this delay is? Also, does it means that last request will never be written to file unless we get next one?

Thank you.

**Comment by lezhnev74** [comment]
From my experience with Gor - yes, the last request won't get into the file until it is pushed be the next one. Currently I can say, that the delay if big enough for me make a request, switch to window with logs, refresh it and see empty file.

I did few tests - it took few seconds to push data in the logs.

-- 
P.s. I noticied also annoying thing - some log files contain few requests and responses within. Is there anyway to name log files differently for each request?

**Comment by buger** [comment]
I see, this definitely can be a bug, if you need it only for debugging reasons, without replaying later, you can try to use --output-stdout instead.

> P.s. I noticied also annoying thing - some log files contain few requests and responses within. Is there anyway to name log files differently for each request?
So, you want to have separate file per request? If so, it is definitely possible to add support for "request_id" variable to name pattern.

**Comment by lezhnev74** [comment]
yes, that `request_id` or something would be great, at least it will let me to separate each request which is a good thing

**Comment by buger** [comment]
Name generation happens in (FileOutput#filename)[https://github.com/buger/gor/blob/master/output_file.go#L119] function, which is run in a separate thread and runs every second. 

In case of request_id, this filename generation should happen on each write, and in my view this should be implemented as special case.

Let's define new fille name variable called "%r", which stands for request_id. For example in controller we can tell:
```

// ... Constructor ...
if strings.Contains(pathTemplate, "%r") {
  o.requestPerFile = true
}

// ... inside OutputFile#Write function ...
// At the start of the function
if o.requestPerFile {
   o.currentID = payloadMeta(data)[1]
   o.updateName()
}

// .. inisde OutputFile#filename
if o.requestPerFile {
   path = strings.Replace(path, "%r", o.currentID, -1)
}
```

I'm happy to provide any help and mentorship for all the details related to this task :)

**Comment by smostovoy** [comment]
I can take this one

**Comment by buger** [comment]
Ha, sure! Thank you!
