### ISSUE TITLE
Windows support

### ISSUE THREAD

**Issue by Elufimov** [buger/goreplay#384]
Hi!
I tested gor (1.5.0 build from releases page) on windows system with installed WinPcap on it. And it did not work. Do you have any plan to support windows on a permanent basis?

**Comment by buger** [comment]
Well, it worked on my tests, but I did not use it on daily basis so probably I can't test it properly.

Can you tell me command you used to run gor? 

Also if you were trying to intercept traffic loopback interface (e.g 127.0.0.1), you have to install additional "loopback" driver. See "Prototip" section here: http://opensourceconnections.com/blog/2016/06/08/building-go-replay-gor-on-windows/

**Comment by buger** [comment]
Closing it for now, feel free to re-open if you still have the issue

**Comment by grasevski** [comment]
yep tried running the exes on the site after doing the loopback driver and installing libpcap etc, "gor file-server :8000" works, nothing else seems to, eg "gor --input-raw :8000 --output-stdout" seemingly does nothing.

**Comment by surfmuggle** [comment]
Hi @Elufimov, @grasevski could you solve the issue? 
Were you able to run goreplay on windows?

**Comment by Elufimov** [comment]
@surfmuggle Our transition to linux infrastructure solved this issue.

**Comment by grasevski** [comment]
No, I don't use Windows anymore.
