### ISSUE TITLE
ipv4 with option -input-raw-realip-header displays an ipv6

### ISSUE THREAD

**Issue by d1ee** [buger/goreplay#393]
If I run gor with option -input-raw-realip-header and do a request with ipv4, then I there is an ipv6 on the destination. For example, the requesters ip address was `10.23.205.72` but on the replayed side I see `a17:cd48::`, which is actually an hexadecimal representation of ipv4.

I looked at the code and address field was a []byte of length 16, which leads to the wrong string conversion of ipv4. I would try to solve the problem and do a pull request, but I thought it would be a good idea to write an issue here and get some help.

**Comment by buger** [comment]
Asking first always make sense, and feel free to provide PR, I'll give you some context:

Go internally use [16]byte for storing both IPv6 and IPv4 addresses. But for IPv4 first bytes should not be used. 

I pinpointed bug till this point:
https://github.com/buger/gor/blob/master/raw_socket_listener/listener.go#L526
```go
newBuf := make([]byte, len(data)+16)
copy(newBuf[:16], srcIP) # <--- here it is
copy(newBuf[16:], data)
t.packetsChan <- newBuf
```

Bug happens because `srcIP` is 4 bytes for IPv4 because it is extracted from TCP payload.
And it writes IP bytes to start of the buffer, and instead should write at the end. 
Final solution can look like this:
```go
if len(srcIP) == 4 {
  copy(newBuf[12:16], srcIP)
} else {
  copy(newBuf[:16], srcIP)
}
```

Thanks!

**Comment by mathicalee** [comment]
In my humble opinion, it won't fix the problem. 

net.IP is an ipv4 only if the byte slice is of length 4, but we write the srcIP into a 16 byte slice, which can be a valid ipv6 address. The information that this was an ipv4 get lost as soon as we write the ipv4 into a 16 byte buffer.

I think we need an extra byte to distinguish ipv4 and ipv6.

**Comment by buger** [comment]
Here is how Go creates IPv4 address, it is 16 byte slice, but indeed have few extra flags, see v4InV6Prefix prefix.

https://golang.org/src/net/ip.go?s=919:933#L43

```go
    43	func IPv4(a, b, c, d byte) IP {
    44		p := make(IP, IPv6len)
    45		copy(p, v4InV6Prefix)
    46		p[12] = a
    47		p[13] = b
    48		p[14] = c
    49		p[15] = d
    50		return p
    51	}
    52	
    53	var v4InV6Prefix = []byte{0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0xff, 0xff}
```

**Comment by mathicalee** [comment]
Thanks, I saw only the implementation of String method. 

Are there any tests regarding the -input-raw-realip-header option?

**Comment by buger** [comment]
Yes, but it does not check the value https://github.com/buger/goreplay/blob/master/input_raw_test.go#L52

**Comment by d1ee** [comment]
Closing this issue, because it's way too old.
