### ISSUE TITLE
Why is the input-http command flag commented out?

### ISSUE THREAD

**Issue by minervas** [buger/goreplay#402]
I am trying to use gor to copy requests with body sizes as big as 2mb. In your [FAQ](https://github.com/buger/gor/wiki/FAQ) you say:

> Due to the fact that Gor can't guarantee interception of all packets, for large payloads > 200kb there is chance of missing some packets and corrupting body. Treat it as a feature and chance to test broken bodies handling :) The only way to guarantee delivery is using --input-http, but you will miss some features.

When I ran
`gor --help`
I noticed that --input-http was not amongst the command flags listed. Then when I searched the repo for input-http I found that [this command flag was commented out](https://github.com/buger/gor/blob/719e9b8e563ab20bbd862f448674e41e3c3e9257/settings.go#L117). Is there a reason for this?

**Comment by minervas** [comment]
Also, do you know if all input types fail to copy request payloads of over 200kb or just certain ones?

**Comment by buger** [comment]
Sorry for the late response! 

I'm afraid GoReplay can't give you any guarantee due to the way how packet capture works. 

As alternative, I'm planning to add "proxy" mode, but as a price, you will have to route your traffic through GoReplay.

**Comment by minervas** [comment]
Alrighty, thanks for getting back to me!
