### ISSUE TITLE
Bug: Negative latency found.

### ISSUE THREAD

**Issue by huyx** [buger/goreplay#404]
Today I encounter the following HTTP response. It as a negative latency.

```
2 6ab1074ccee9bdfcd9c6ff4723967edf683860f7 1481786618718741470 -3265695
HTTP/1.1 200 OK
Date: Thu, 15 Dec 2016 07:23:37 GMT
...
```

It should be a bug.

Thanks.

**Comment by buger** [comment]
Definitely it is, and I think that this pull request should fix the issue: https://github.com/buger/goreplay/pull/395

**Comment by buger** [comment]
Should be fixed now! 

Check this binary:
[gor_fix_pcap_timestamp_x64.tar.gz](https://github.com/buger/goreplay/files/659537/gor_fix_pcap_timestamp_x64.tar.gz)
