### ISSUE TITLE
Requests per second ratelimit

### ISSUE THREAD

**Issue by mariokostelac** [buger/goreplay#405]
Hi guys, I found your tool today and it seems 😍.

I was reading https://github.com/buger/goreplay/wiki/Rate-limiting and I am wondering if there is a rate limiting that would allow executing certain number of request per second (or minute), but without dropping requests. I'd like goreplay to slow down and wait.

That would massively help with benchmarking characteristics of systems under certain load (1000 writes per second, 100 reads per second; 1000 writes per second, 200 reads per second etc ).

Do you support this?
If not, do you plan to support that?
If you do not plan to support that, why? :)

**Comment by buger** [comment]
It is for sure supported! 

It works how your described, by slowing down or speeding up when you replay from file: https://github.com/buger/goreplay/wiki/Saving-and-Replaying-from-file#performance-testing

For obvious reasons such functionality not supported when replaying in live mode.

Thank you!

**Comment by mariokostelac** [comment]
Ok, so it is not supported actually. What I was thinking originally was using live traffic for getting the content of requests, but I wanted to control the speed. I can see that it is not a trivial thing to implement, but I am interested if you have something religiously against that feature :) (or in other words "would you be willing to work on accepting somebody's else's PR if people need it"?).

**Comment by buger** [comment]
Nope, I'm happy accepting pull requests :)

To implement the feature like you described, you have to maintain sort of buffer, which can be quite big. By reading from buffer, you can slow down, but only until buffer will reach the size limit (and in this case you have to back to original speed, or somehow clean up it). If you will try to speed up, you can do it only until you read all the buffer. 

I'm open to any suggestions, and even implemented like described above, it will be great feature!

**Comment by mariokostelac** [comment]
Thanks @buger. If I find it as a a deal-breaker, will submit a PR :).
