### ISSUE TITLE
PANIC: pkg: runtime error: slice bounds out of range Addr:

### ISSUE THREAD

**Issue by neeraj9** [buger/goreplay#408]
After running the the tool for a 6+ hours it threw a panic. A possible bug.

```
$ sudo ~/bin/gor --input-raw :9090 --output-file=%Y-%m-%d_%H-%M-requests.log.gz --input-raw-track-response --output-file-append
Version:
2016/12/23 14:00:37 PANIC: pkg: runtime error: slice bounds out of range Addr:

Source port: 9090
Dest port:21920
Sequence:2948825057
Acknowledgment:1824782714
Header len:8
FIN:false
Data size:1426
Data:3="http://www.w3.org/2001/XMLSchema-instance" ns3:nil="true" /><ns2:SomeAlteNo>1234567890</ns2:SomeAlteNo><ns2:Someab>124</ns2:Someab><ns2:ContactPerson>123456</ns2:ContactPerson><ns2:DisplayOnline> goroutine 8 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/lib/go-1.6/src/runtime/debug/stack.go:24 +0x80
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket.func1(0xc821c87050)
        /home/neeraj9/go/src/github.com/buger/gor/raw_socket_listener/listener.go:676 +0x75
panic(0xa67520, 0xc82000e0a0)
        /usr/lib/go-1.6/src/runtime/panic.go:443 +0x4e9
github.com/buger/gor/proto.ParseHeaders(0xc8227974a0, 0x14, 0x14, 0xc820039a40)
        /home/neeraj9/go/src/github.com/buger/gor/proto/proto.go:233 +0x680
github.com/buger/gor/raw_socket_listener.(*TCPMessage).updateBodyType(0xc82286b340)
        /home/neeraj9/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:376 +0x107
github.com/buger/gor/raw_socket_listener.(*TCPMessage).AddPacket(0xc82286b340, 0xc821c87050)
        /home/neeraj9/go/src/github.com/buger/gor/raw_socket_listener/tcp_message.go:149 +0x4cd
github.com/buger/gor/raw_socket_listener.(*Listener).processTCPPacket(0xc82014c500, 0xc821c87050)
        /home/neeraj9/go/src/github.com/buger/gor/raw_socket_listener/listener.go:743 +0x8a2
github.com/buger/gor/raw_socket_listener.(*Listener).listen(0xc82014c500)
        /home/neeraj9/go/src/github.com/buger/gor/raw_socket_listener/listener.go:148 +0x1dd
created by github.com/buger/gor/raw_socket_listener.NewListener
        /home/neeraj9/go/src/github.com/buger/gor/raw_socket_listener/listener.go:119 +0x3aa
```

**Comment by buger** [comment]
Hello! Since version field is empty, I assume you are running custom build. May I ask what version of Gor it is?

**Comment by neeraj9** [comment]
I am running latest build out of git (as of today).

On Dec 23, 2016 7:50 PM, Leonid Bugaev <notifications@github.com> wrote:Hello! Since version field is empty, I assume you are running custom build. May I ask what version of Gor it is?

**Comment by buger** [comment]
Just to clarify, it does not crash the process, but sometimes throws error into logs, right? What is the average requests per second? Just to understand how common issue is. Thans!

**Comment by neeraj9** [comment]
I was running the application in foreground for testing and unfortunately I did not notice whether it continued working. I do remember that I killed it manually via ctrl-c (sigint) signal. I will have to dig into the details to give an exact number but my initial guess regarding RPS would be somewhere in tens per second. I would revise the estimate once I am done with detailed analysis through.

**Comment by neeraj9** [comment]
Huh! So, the panic probably doesn't handle the message which caused the panic but the application stays up and continues to intercept and log messages. It does leads to loss of the message which caused the panic, but it does continue working.
I will continue to monitor the quantum of panics, but it will be great to have a patch for the issue.

**Comment by buger** [comment]
Cool! Thank you for the feedback!

**Comment by buger** [comment]
Issue was fixed, using fuzzer helped #411

**Comment by buger** [comment]
Here is latest binary fith fix [gor_DEV-1482850025_x64.tar.gz](https://github.com/buger/goreplay/files/674262/gor_DEV-1482850025_x64.tar.gz)

**Comment by neeraj9** [comment]
@buger Thanks.
