### ISSUE TITLE
Docker usage

### ISSUE THREAD

**Issue by k2xl** [buger/goreplay#414]
I'm trying to get gor to work in a docker container.

I have two containers, one is just an app listening on 8000 and gor. I'm trying to figure out how to get gor to work, but it doesn't seem to be able to listen to connections on the other container. It does work within the container, just trying to figure out how to get it listen to the other.

I stand up python SimpleHTTPServer in container App (port 8000)
I stand up gor to listen to port 8000 in container Gor

`curl localhost:8000` the SimpleHTTPServer responds, but Gor doesn't.

If I move the SimpleHTTPServer inside Gor, then Gor does respond.

I've tried having them both join the same docker network, but that doesn't seem to work. Also tried host networking with gor but no dice.

**Comment by buger** [comment]
Hello! Can you give the commands how you run both Docker and Gor? 

Gor need access to network interface where the traffic comes in.
Your assumption to use host networking is right and should work, maybe you are listening to the wrong port?
When you run docker container, if you do not explicitly bind docker app port to host port, by default it will choose random host port. So check `docker ps` output, to see the port of your app.

If this will not work, try using this tcpdump container for debugging https://hub.docker.com/r/corfr/tcpdump

Thank you!

**Comment by pwheel** [comment]
Hi, here's an example docker-compose file using a simple hello-world docker container.

    hello-world:
      ports:
       - "80:80"
      image: tutum/hello-world:latest
    gor-listen:
      image: pwheeler/hotels/gor:0.16.0
      net: "host"
      command: ./gor --input-raw :80 --output-stdout --input-raw-track-response

Make sure you're not using Docker for Mac for e.g. as the custom networking can get in the way and stop it working. I had to test on a Linux environment using vagrant.

**Comment by buger** [comment]
Just added official image: "buger/goreplay"

https://github.com/buger/goreplay/issues/451

**Comment by cattanisimone** [comment]
Have you some possible configuration in order to intercept traffic between one container and another? Can I run gor to redirect/filter/export service1 requests?

`  service1:
    image: ...
    links:
      - service2:s

  service2:
    image: ...`

**Comment by buger** [comment]
GoReplay needs to have access to the network interface to capture the data. Even to the virtual interface, which is used by Docker. Example by @pwheel above shows how you can run goreplay image in "host" mode, so it has access to all traffic on the machine.

**Comment by Gabology** [comment]
Host mode networking is not an option for us because we are using Docker swarm with a dozen or so different nodes that are scaled up/down depending on the traffic. So we must use overlay networking to allow service discovery and other things. 

Any recommendations on how we could solve this?

**Comment by one2gopher** [comment]
you can get date from the node where traefik work on，with gor

**Comment by karsten42** [comment]
Is there any update on this, I'm also having problems running `goreplay`. 
I'm trying to run the following command:
`docker run --rm -it -p 8629:8629 buger/goreplay --input-raw :8629 --output-stdout`

Even with the suggested `--network host` I don't get any logs if I try to do `curl -v localhost:8629/test`.
If I run this locally on my computer without docker everything works as expected.

**Comment by urbanishimwe** [comment]
FYI goreplay inside docker will capture traffics designated to the container(inside the same network group)

**Comment by MatteoOreficeIT** [comment]
I've tested this option for `docker run` command see [network settings](https://docs.docker.com/engine/reference/run/#network-settings) in docker run doc page

example to attach to another container :

```bash
docker run -ti --rm --net container:othercontainername customimage/gor --project-gor-options ....
```

> pay attention to tune gor options to capture packets in the right way
