### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by tomek-artneo** [buger/goreplay#427]
Hello
I'm having problems with gor. For some of requests, it throws:
```Failed to decode input payload encoding/hex: invalid byte: U+005B '[' 41
Failed to decode input payload encoding/hex: invalid byte: U+005B '[' 23
Failed to decode input payload encoding/hex: invalid byte: U+005B '[' 23
Failed to decode input payload encoding/hex: odd length hex string 98
Failed to decode input payload encoding/hex: invalid byte: U+005B '[' 25
Failed to decode input payload encoding/hex: odd length hex string 28
Failed to decode input payload encoding/hex: invalid byte: U+005B '[' 33
Failed to decode input payload encoding/hex: odd length hex string 26
Failed to decode input payload encoding/hex: invalid byte: U+005B '['
Failed to decode input payload encoding/hex: invalid byte: U+0020 ' ' 1685
```

and then stops:
```panic: runtime error: index out of range
goroutine 23 [running]:
panic(0x998bc0, 0xc820010090)
        /usr/lib/golang/src/runtime/panic.go:481 +0x3e6
main.CopyMulty(0x7f64c9af0178, 0xc82119e480, 0xc821157c10, 0x1, 0x1, 0x0, 0x0)
        /home/gocode/src/github.com/buger/gor/emitter.go:64 +0x12b2
created by main.Start
        /home/gocode/src/github.com/buger/gor/emitter.go:25 +0x2b4
```

It happens only with a gor I compiled myself, after changing expire timeout in listener.go (according to [this comment](https://github.com/buger/goreplay/issues/424#issuecomment-281646915)). The official binary also shows decode erros, but doesn't panics. I'd like to use that version, but I need to work with POST responses, which are returned after 2-10 seconds and as I suppose, --input-raw timeout is not configurable yet.

Did I do something wrong with compilation? I'll be grateful for any help.

**Comment by buger** [comment]
Can you specify exact command you were using? Did you used middleware?

**Comment by tomek-artneo** [comment]
Yes, I'm using middleware:
`gor --input-raw :82 --output-null -input-raw-track-response --middleware "/usr/bin/php /home/yama/middleware.php"`

**Comment by buger** [comment]
This is a known bug and fixed in master. Not released yet,
But will be soon. So you can compile by yourself or I can help you with it
later. 👍🏻

**Comment by tomek-artneo** [comment]
When was it fixed? My panicking gor was compiled yesterday at 1pm UTC. Should use a different URL with `go get github.com/buger/gor` to get latest fixes?

**Comment by buger** [comment]
Got it, maybe it is a new bug. Looks like related to UTF8 characters, will
check soon.

**Comment by tomek-artneo** [comment]
I'm looking forward to hear some good news :-) Let me know if you need more details to track this bug. I tried to find out, which request/response (or part of it) causes "index out of range" error, but can't figure it out from verbose debug log.

By the way - great work with --prettify-http. It'll help me a lot :-)

**Comment by buger** [comment]
I have a feeling that reason is your middleware itself. And you not properly hex encoding outcoming data.

Recently I wrote NodeJS middleware framework https://github.com/buger/goreplay/tree/master/middleware which should become a baseline for writing in another languages. Maybe you can try port your middleware to it?

Btw, here is the binaries with new `--input-raw-expire` option.

[gor_DEV-1489760767_mac.tar.gz](https://github.com/buger/goreplay/files/850810/gor_DEV-1489760767_mac.tar.gz)
[gor_DEV-1489760743_x64.tar.gz](https://github.com/buger/goreplay/files/850811/gor_DEV-1489760743_x64.tar.gz)

**Comment by buger** [comment]
Closing for now, feel free to re-open
