### ISSUE TITLE
--output-file-size-limit not being respected

### ISSUE THREAD

**Issue by dullyouth** [buger/goreplay#429]
I'm trying to set gor to roll files based on size every 5MB.

I've tried this with and without the timestamps in the filename, since that seems to be the only thing that will actually rotate it in my case.

Using AB i'm generating roughly 23MB of gor logs

```
root@appdev:/opt/gor/out/local_dev/master# /usr/bin/gor --input-raw :80 --output-file=/opt/gor/out/local_dev/master/%m-%d-%Y_g7bn8l48mpWeQwqG_requests.gor --output-file-queue-limit 0 --output-file-size-limit 5m &

root@appdev:/opt/gor/out/local_dev/master# ab -q -n 150000 -c 1000 localhost:80/  > /tmp/ab.log

root@appdev:/opt/gor/out/local_dev/master# ls -lah
total 23M
drwxr-xr-x 2 gor  gor  4.0K Mar 16 21:33 .
drwxr-xr-x 3 gor  gor  4.0K Mar 16 21:12 ..
-rw-r----- 1 root root  23M Mar 16 21:34 03-16-2017_g7bn8l48mpWeQwqG_requests_0.gor
root@appdev:/opt/gor/out/local_dev/master#
```

**Comment by buger** [comment]
I see the issue. So, even if Gor have specified limit, it get's checked only per second, and controller by `output-file-flush-interval` option. Looking at your `ab` command I may assume that in 1 second it generate more traffic in 1 second, more than your  `--output-file-size-limit` limit. If you change it to generate a bit less requests, you should see that size limit will work. 

Worth noticing that Gor support automatic file compression and decompression, just end your file with ".gz" extension: ` --output-file requests.gor.gz`

**Comment by dullyouth** [comment]
I can run ab 10 times over 20 minutes and it only ever creates one file.
