### ISSUE TITLE
Basic auth doesn't seem to work

### ISSUE THREAD

**Issue by k2xl** [buger/goreplay#430]
` --output-http-elasticsearch http://<user>:<pass>@url.com:5000/index"`

The error I see is that it can't parse out the user and pass `dial tcp: lookup nowhere Post http://http:5000/_bulk`

**Comment by buger** [comment]
Yeah, currently it use non-standard URI parser https://github.com/buger/goreplay/blob/master/elasticsearch.go#L56. To make it work it should be replaced by standard `net/url` parsing, and if auth attributes found, it should call `p.eConn.SetBasicAuth(Username, Password)`

**Comment by fxponscarme** [comment]
Hi had the issue so I've made a quick fix.
`net/url`is used in elasticgo library in SetFromUrl function but is not working well if no scheme is set in URI.
