### ISSUE TITLE
--output-file-size-limit not being respected

### ISSUE THREAD

**Issue by dullyouth** [buger/goreplay#431]
Re-opening https://github.com/buger/goreplay/issues/429 since the response didn't really address the issue i'm seeing.
## initial issue
I'm trying to set gor to roll files based on size every 5MB.

I've tried this with and without the timestamps in the filename, since that seems to be the only thing that will actually rotate it in my case.

Using AB i'm generating roughly 23MB of gor logs. It takes roughly 10 seconds to generate the ab traffic

I can run AB over any number of times over any period of time and it only creates the one file.

```
root@appdev:/opt/gor/out/local_dev/master# /usr/bin/gor --input-raw :80 --output-file=/opt/gor/out/local_dev/master/%m-%d-%Y_g7bn8l48mpWeQwqG_requests.gor --output-file-queue-limit 0 --output-file-size-limit 5m &

root@appdev:/opt/gor/out/local_dev/master# ab -q -n 150000 -c 1000 localhost:80/  > /tmp/ab.log

root@appdev:/opt/gor/out/local_dev/master# ls -lah
total 23M
drwxr-xr-x 2 gor  gor  4.0K Mar 16 21:33 .
drwxr-xr-x 3 gor  gor  4.0K Mar 16 21:12 ..
-rw-r----- 1 root root  23M Mar 16 21:34 03-16-2017_g7bn8l48mpWeQwqG_requests_0.gor
root@appdev:/opt/gor/out/local_dev/master#
```

## after letting it run over night with the recommended settings.

Gor has been running over night on a live server with the gor command used in my first comment.

```
root:/opt/gor/out/# ls -lah
total 170M
drwxr-xr-x 2 gor gor 4.0K Mar 16 23:19 .
drwxr-xr-x 3 gor gor 4.0K Mar 16 23:07 ..
-rw-r----- 1 gor gor 170M Mar 17 16:34 2017-03-16-23_3DdjGKVz3zQeJHke_requests_0.gor
root:/opt/gor/out/# ps xau |grep gor
gor       1173  0.2  0.5 629424 47164 ?        Sl   Mar16   2:44 /usr/bin/gor --input-raw :80 --output-file=/opt/gor/out/%Y-%m-%d-%H_3DdjGKVz3zQeJHke_requests.gor --output-file-queue-limit 0 --output-file-size-limit 5m
root:/opt/gor/out/# date
Fri Mar 17 16:35:18 UTC 2017
root:/opt/gor/out/#

**Comment by buger** [comment]
Sorry for the delay, bug is fixed!

**Comment by ikenchina** [comment]
bug still exist.

**Comment by buger** [comment]
@ikenchina which version did you tried, latest master?
