### ISSUE TITLE
http-original-host does not preserve ip address in request header

### ISSUE THREAD

**Issue by rajat2107** [buger/goreplay#435]
Command:
sudo ./gor --input-raw :<port> --http-original-host --output-http http://<ip>:<port>

Gor does not preserve the original headers in request.

**Comment by buger** [comment]
Hello! First of all wanted to clarify, it does not preserve http "Host" header? Or you mean smth different?

**Comment by rajat2107** [comment]
Thanks for your reply. I want to preserve the IP from which the original request came. Can you please suggest how this can be done?

**Comment by buger** [comment]
Well, from a network point of view it is impossible to initiate a request from different IP which you have now. This is problem which experience all users who proxy requests through Nginx or similar. In most cases it is solved by adding special HTTP header (usually called `X-Forwarded-For`), which store original user IP. Proxies like nginx or AWS ELB support this scheme from the box. 

So, once header is added to the http payload, you replay this traffic to the target, and this target should extract user IP from this header.

**Comment by rajat2107** [comment]
Thanks for the prompt response and explanation. When X-Forwarded-For was set, I was able to get the IP at the target.

**Comment by buger** [comment]
👌
