### ISSUE TITLE
missing items from vendor directory

### ISSUE THREAD

**Issue by ilovezfs** [buger/goreplay#437]
```
==> go build -o /usr/local/Cellar/gor/HEAD-dcc7af4/bin/gor -ldflags -X main.VERSION=HEAD-dcc7af4
input_kafka.go:5:2: cannot find package "github.com/Shopify/sarama" in any of:
	/private/tmp/gor-20170408-9454-1910oh7/src/github.com/buger/gor/vendor/github.com/Shopify/sarama (vendor tree)
	/usr/local/Cellar/go/1.8_1/libexec/src/github.com/Shopify/sarama (from $GOROOT)
	/private/tmp/gor-20170408-9454-1910oh7/src/github.com/Shopify/sarama (from $GOPATH)
input_kafka.go:6:2: cannot find package "github.com/Shopify/sarama/mocks" in any of:
	/private/tmp/gor-20170408-9454-1910oh7/src/github.com/buger/gor/vendor/github.com/Shopify/sarama/mocks (vendor tree)
	/usr/local/Cellar/go/1.8_1/libexec/src/github.com/Shopify/sarama/mocks (from $GOROOT)
	/private/tmp/gor-20170408-9454-1910oh7/src/github.com/Shopify/sarama/mocks (from $GOPATH)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```

For Homebrew, we used to be able to build goreplay without any additional go resource blocks, but now the above build failure occurs unless I add a whole pile of them:
```
  go_resource "github.com/Shopify/sarama" do
    url "https://github.com/Shopify/sarama.git",
        :revision => "d4ece5d05a86b2b64248f4943f872bea961ec835"
  end

  go_resource "github.com/davecgh/go-spew" do
    url "https://github.com/davecgh/go-spew.git",
        :revision => "346938d642f2ec3594ed81d874461961cd0faa76"
  end

  go_resource "github.com/eapache/go-resiliency" do
    url "https://github.com/eapache/go-resiliency.git",
        :revision => "b86b1ec0dd4209a588dc1285cdd471e73525c0b3"
  end

  go_resource "github.com/eapache/go-xerial-snappy" do
    url "https://github.com/eapache/go-xerial-snappy.git",
        :revision => "bb955e01b9346ac19dc29eb16586c90ded99a98c"
  end

  go_resource "github.com/eapache/queue" do
    url "https://github.com/eapache/queue.git",
        :revision => "44cc805cf13205b55f69e14bcb69867d1ae92f98"
  end

  go_resource "github.com/golang/snappy" do
    url "https://github.com/golang/snappy.git",
        :revision => "553a641470496b2327abcac10b36396bd98e45c9"
  end

  go_resource "github.com/klauspost/crc32" do
    url "https://github.com/klauspost/crc32.git",
        :revision => "1bab8b35b6bb565f92cbc97939610af9369f942a"
  end

  go_resource "github.com/pierrec/lz4" do
    url "https://github.com/pierrec/lz4.git",
        :revision => "f5b77fd73d83122495309c0f459b810f83cc291f"
  end

  go_resource "github.com/pierrec/xxHash" do
    url "https://github.com/pierrec/xxHash.git",
        :revision => "5a004441f897722c627870a981d02b29924215fa"
  end

  go_resource "github.com/rcrowley/go-metrics" do
    url "https://github.com/rcrowley/go-metrics.git",
        :revision => "1f30fe9094a513ce4c700b9a54458bbb0c96996c"
  end
```
In the interests of maintainability, it would be great of those could be vendored as well. Or perhaps I'm just doing something wrong, and sarama, etc. aren't actually required after all?

**Comment by buger** [comment]
Sorry for the delay! All these packages should be vendored now. I also updated tag.

**Comment by ilovezfs** [comment]
@buger it would be best to use a new tag name (0.6.1 or 0.6.0.1) rather than changing the 0.6.0 tag because

- when you retag you break the from-source build for anyone using Homebrew (and also possibly other projects)
- when you retag we don't know until a PR is filed whether it was intentional or you've been hacked
- we (and you) now can't easily differentiate between users using the old tag or the new one as they have the same Homebrew version number
- when you retag anyone who has done `git fetch --tags` and runs it again will not receive an updated tag. This is because Git is designed to not update tags as they are meant to be permanent. Retagging in Git-land is equivalent to force-pushing to a public branch (i.e. bad)

Thanks!

**Comment by buger** [comment]
Man, you are quick :)

Added new "v0.16.0.1" tag, I hope it is ok. Thank you!

**Comment by buger** [comment]
But can we still call it "0.16.0" in homebrew?

**Comment by ilovezfs** [comment]
It will detect the version from the tag name, and since I published bottles for 0.16.0 Apr 7, it would now be best to let it be called 0.16.0.1 rather than coercing the version to be the same with a version override. That will ensure everyone gets upgraded to the version with the vendored dependencies and avoid having 0.16.0 mean two things.

**Comment by ilovezfs** [comment]
By the way is it intentional that the import path is still `github.com/buger/gor` nor `github.com/buger/goreplay`?

**Comment by buger** [comment]
@ilovezfs It is a good point, project name was changed a bit, but binary name stayed the same. And github properly does the redirects. So from the naming point of view I'm ok in having `brew install gor`.  But if it violate rules or similar, name can be updated.

**Comment by ilovezfs** [comment]
```
==> go build -o /usr/local/Cellar/gor/0.16.0/bin/gor -ldflags -X main.VERSION=0.16.0
elasticsearch.go:5:2: cannot find package "github.com/buger/gor/proto" in any of:
	/private/tmp/gor-20170501-3494-1g1l7v2/src/github.com/buger/goreplay/vendor/github.com/buger/gor/proto (vendor tree)
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/buger/gor/proto (from $GOROOT)
	/private/tmp/gor-20170501-3494-1g1l7v2/src/github.com/buger/gor/proto (from $GOPATH)
input_raw.go:5:2: cannot find package "github.com/buger/gor/raw_socket_listener" in any of:
	/private/tmp/gor-20170501-3494-1g1l7v2/src/github.com/buger/goreplay/vendor/github.com/buger/gor/raw_socket_listener (vendor tree)
	/usr/local/Cellar/go/1.8.1/libexec/src/github.com/buger/gor/raw_socket_listener (from $GOROOT)
	/private/tmp/gor-20170501-3494-1g1l7v2/src/github.com/buger/gor/raw_socket_listener (from $GOPATH)
/usr/local/Homebrew/Library/Homebrew/debrew.rb:11:in `raise'
```
is what happens if I try to use the new repo name.

**Comment by buger** [comment]
Made changes and added new "0.16.0.2" tag.

**Comment by ilovezfs** [comment]
@buger thanks! Voilà: https://github.com/Homebrew/homebrew-core/pull/13121

**Comment by buger** [comment]
👍
