### ISSUE TITLE
-output-file-size-limit doesn't work

### ISSUE THREAD

**Issue by ikenchina** [buger/goreplay#442]
i speficied --output-file-size-limit in order to quit program while file size was reached specify size,
but seems it's useless, program was still running and file size exceed the size

**Comment by buger** [comment]
Related PR https://github.com/buger/goreplay/pull/445/files

**Comment by majones713** [comment]
As a heads up I was able to reproduce this on my end as well but also noticed when you don't even use the -output-file-size-limit arg but rather use default (not specifying command) the file still grows vs stopping at 256mb and creating chunks.  Chunking doesn't work either

**Comment by buger** [comment]
@majones713  what is your OS?

**Comment by majones713** [comment]
@buger sorry for  late repsonse..been on holidays.

I was able to reproduce on both WIN7 and LINUX

**Comment by majones713** [comment]
So tested this using latest code where the last commit was https://github.com/buger/goreplay/commit/bf8198d6391b4713b39870be6fd8e17910ee3af9

We've tested and found even if you don't include arg it doesn't default to 32mb in file size chunks.  The command we're using is:

./goreplay --input-raw :8080 --output-file reports/%Y-%m-%d.log --input-raw-track-response --prettify-http

Can you please let me know if I wanted to output file chunks of 64mb within the hour is this correct:

./goreplay --input-raw :8080 --output-file reports/%Y-%m-%d-%H.log --output-file-size-limit 64m --input-raw-track-response --prettify-http

also, -help shows args using two dashes (--) but --help shows args using one dash.  Which one is correct?

**Comment by nagendra547** [comment]
I am also able to reproduce this issue on CentOS 7. 
parameter --output-file-size-limit is not working.

**Comment by buger** [comment]
It should be fixed in master. The main logic here is that even "--output-file-flush-interval" (which is 1 second by default), it checks file size and compare with what specified in order to decide if issue new chunk or not. 

But I also found code which not covered by error handling in this part, and it should now print error. Maybe this is your case somehow.
