### ISSUE TITLE
Comparison with flashback

### ISSUE THREAD

**Issue by tomkel** [buger/goreplay#446]
Linkedin's [flashback](https://github.com/linkedin/flashback) tool seems to occupy a lot of the same problem space as gor. Can someone please explain how they are different? 

Flashback seems to be a proxy where as goreplay says it's not. But it seems to me that goreplay could be set up in such a way to serve as a proxy. Also flashback seems less flexible in terms of multiple instances working independently. Goreplay also seems to be geared more towards load testing. Flashback supports HTTPS recording with a custom cert, where goreplay requires a reverse proxy.

**Comment by buger** [comment]
Flashback operates in a parallel space, but still very different. What it does, in the industry called [Service Virtualization](https://en.wikipedia.org/wiki/Service_virtualization). Basically, it is mocking "external" network dependencies. While GoReplay is used to record your "incoming" traffic, and replay it.

I have ideas on introducing some of the service virtualization functionality, here is one of the related discussions https://github.com/buger/goreplay/issues/441
