### ISSUE TITLE
Hangs forever

### ISSUE THREAD

**Issue by juztin** [buger/goreplay#448]
`gor` hangs indefinitely

--- 

### Setup:
    Linux Mint 18.1
    Kernel 4.4.0-66-generic
    libpcap-dev 1.7.4-2
    Docker 17.03.1-ce
        Alpine 3.5 w/libpcap-dev

First tried getting things working in a container:
```
% docker run \
        -it \
        --rm \
        --network host \
        --publish 7070:7070 \
        private-repo/gor --input-tcp :7070 \
            --output-stdout
            --debug \
            --verbose

Version: 0.16.0
```

When I try issuing a cURL to `localhost:7070` it just hangs... forever.  
If I `ctrl+c` the GoReplay server, cURL will finally exit.

I get the same result both running on my host _(Linux Mint)_ and from within the Alpine container.  

There is no other output, errors or otherwise.

**Comment by buger** [comment]
Worth noticing that `--input-tcp` is used only in distributed configuration and not for capturing traffic. You should use `--input-raw` instead.

**Comment by juztin** [comment]
I tried that while I was trying to get things working.  
Running with `--input-raw` I get immediate `Connection refused`, and it takes a while to stop Gor.

Running locally, under `root`, and within a container yield the same results.

**Comment by buger** [comment]
Can you describe your use-case a bit?

I have a feeling that you trying to use GoReplay as a reverse proxy, eg. sending traffic directly to GoReplay. 

Instead on port 7070 you should run your web application, and GoReplay will capture its traffic using `--input-raw :7070`. 

GoReplay is designed to not affect your application flow, it is safe to run it on your web machines, and it will capture traffic in the background.

**Comment by juztin** [comment]
Thanks @buger!

Yes, I was trying to use GoReplay as a reverse proxy =S

I should have known when I was getting `libpcap` installed, but I had my blinders on and I was stuck trying to "make it work". Thanks for the quick replies and help =)
