### ISSUE TITLE
Public 'official' docker image for GoReplay on Docker Hub

### ISSUE THREAD

**Issue by pwheel** [buger/goreplay#451]
Hi,

We're using GoReplay in Docker and have built our own docker image using the latest release (0.16).

It would be nice if there was a publicly available docker image for GoReplay on https://hub.docker.com. https://hub.docker.com/r/dmoscrop/gor/ seems to be the most popular image on docker hub but the gor binary in there is quite out of date.

Ideally would have new versions automatically published to docker hub so I don't have to maintain my own docker image :-)

Thanks,
Paul

**Comment by buger** [comment]
Just added https://hub.docker.com/r/buger/goreplay/ :)

**Comment by pwheel** [comment]
Awesome, thanks, will check it out!

**Comment by ezeql** [comment]
would it be possible to have access to  Dockerfile? thanks
