### ISSUE TITLE
Question: Save in pcap format

### ISSUE THREAD

**Issue by sunny137** [buger/goreplay#453]
Is it possible to save captured requests in .pcap format so they can be consumed by other tools for further analysis? If yes, how to do this and has anyone tried this before? If no, do you have this as part of your road map?

**Comment by buger** [comment]
GoReplay can read from pcap using `--input-pcap`, but I think writing does not make much sense. GoReplay is a high-level tool, it process raw traffic (like pcap), and turns it into high-level objects like HTTP payload (which can consist from multiple packets and there can be a lot of pre-processing). 

If you need save to pcap file just use `tcpdump`.
