### ISSUE TITLE
goreplay and AWS ELBs traffic

### ISSUE THREAD

**Issue by salimane** [buger/goreplay#454]
Hi,

Imagine a situation where you have your production and staging services in AWS all behind AWS ELBs balancing the traffic. There is no nginx in between the ELB and the service. The ELBs terminate the SSL. How would you setup goreplay to replay the traffic from the production ELB to the staging ELB.

Thanks

**Comment by buger** [comment]
The only way here is to run GoReplay on the machine with your service. There is no difference if there is nginx or not, the only thing matters that traffic should be unencrypted.

**Comment by salimane** [comment]
Ok thanks :)
