### ISSUE TITLE
Add support for TLS connection between GoReplay instances

### ISSUE THREAD

**Issue by buger** [buger/goreplay#457]
Both `--input-tcp` and `--output-tcp` should support TLS.

**Comment by zengxiaobai** [comment]
HI,  can I capture the https traffic to server like nginx but not goreplay which listen to port 443, if i have the certificate which nginx uses.  

such as this: 
(443 port is not listened by goreplay but by nginx)
./goreplay -output-http "http://183.6.9.206:443|60%" -input-tcp-secure --input-tcp-certificate "/usr/local/nginx/cert/dd.crt" --input-tcp-certificate-key "/usr/local/nginx/cert/ddkey" -input-raw-bpf-filter "dst port 443" -input-raw ":443"
