### ISSUE TITLE
-output-file arg not working on Windows

### ISSUE THREAD

**Issue by majones713** [buger/goreplay#459]
Environment Info:
OS: Windows 7
Gor Binary Version: go1.8.3.windows-386.msi

Test Steps:

1. Start local file server:

C:\Users\Me\go\src\github.com\buger\gor>gor.exe file-server :8000
2017/05/25 20:15:17 Started example file server for current directory on address
  :8000

2. Start 

C:\Users\Me\go\src\github.com\buger\gor>gor.exe -input-raw :8000 -output-file requests.log

3. Open browser and go to localhost:8000

ISSUE:

File isn't created with recorded traffic.  I attempted to use full path to file such as -output-file "C:\requests.log" and still no luck. 

I ran this as well and saw output in consoled but no luck via file

C:\Users\Me\go\src\github.com\buger\gor>gor.exe -input-raw :8000 -output-stdout -output-file requests.log

**Comment by urbanishimwe** [comment]
I guess the file extension should end with `.gor`
