### ISSUE TITLE
-input-raw-track-response arg not working on Windows

### ISSUE THREAD

**Issue by majones713** [buger/goreplay#460]
Environment Info:
OS: Windows 7
Gor Binary Version: go1.8.3.windows-386.msi

Test Steps:

1. Start local file server:

C:\Users\Me\go\src\github.com\buger\gor>gor.exe file-server :8000
2017/05/25 20:15:17 Started example file server for current directory on address
  :8000

2. Start 

C:\Users\Me\go\src\github.com\buger\gor>gor.exe -input-raw :8000 -input-raw-track-response  -output-stdout

3. Open browser and go to localhost:8000

ISSUE:

You see the request but not the response being captured:

**Comment by crccheck** [comment]
I'm getting the same thing. With a `python2 -m SimpleHTTPServer 6969` running in another terminal, I only get response type `1` and `3`.

On OSX, I've tried 0097c59, v0.16.1 and v0.15.1 with
```
./gor \
  --input-raw :6969 \
  --input-raw-track-response \
  --output-stdout
```

On CentOS, I've tried
```
sudo ./goreplay \
  --input-raw :6969 \
  --input-raw-track-response \
  --output-stdout
```

and

```
docker run --rm --net=host buger/goreplay \
  --input-raw :6969 \
  --input-raw-track-response \
  --output-stdout
```

If I add `--input dummy`, I get response type `2`, but those look like they're synthetic. I've also tried it with the [`echo.sh`](https://github.com/buger/goreplay/blob/master/examples/middleware/echo.sh) middleware but don't see the input response.

**Comment by buger** [comment]
Can you pls try latest windows binary from this thread https://github.com/buger/goreplay/issues/440 ?

**Comment by crccheck** [comment]
Ugh, I figured out my issue on Ubuntu/Centos/OSX... I was testing using `curl localhost` and `curl 127.0.0.1`, but it looks like Goreplay only tracks responses if it goes outside the box.

**Comment by buger** [comment]
I see, well, on windows localhost handling is very different from the unix systems. I would recommend installing https://nmap.org/npcap/, which adds virtual interface to track local traffic. 
In addition, you can set custom bpf filter, to avoid IP checks, like this --input-raw-bpf-filter ":<port>". 

Hope it helps!
