### ISSUE TITLE
Why does gor always write to STDOUT

### ISSUE THREAD

**Issue by pmyjavec** [buger/goreplay#462]
If I simply run `sudo ./gor --input-raw :8086 --output-http=http://smellwebserver.org`, it prints  everything captured to STDERR. 

Why does gor do that by default and is there a way to disable this behaviour?

**Comment by buger** [comment]
Well, this is indeed not expected. What is your version and OS you are running?

**Comment by pmyjavec** [comment]
Hey @buger, 

I realised afterwards that it seemed to happen if I specified the wrong destination port, and because it was writing to STDERR I began to think that this might be intentional behaviour?

I can provide some more details in the next few days if you like?

**Comment by slimus** [comment]
Gor will write errors and debug to stdout.
