### ISSUE TITLE
runtime error: slice bounds out of range 

### ISSUE THREAD

**Issue by nlmunro** [buger/goreplay#463]
This only happens when I increase the replay speed (3200%!) - it doesn't happen at normal rates, but the point of this is to simulate a very heavy load and it makes it hard to judge the load. The stats queue is still well below 100 at this stage (in the range 0-31).

2017/06/08 13:16:32 PANIC: pkg: runtime error: slice bounds out of range goroutine 68 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
	c:/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0x21e53e00, 0x21e53e0c)
	C:/Work/src/github.com/buger/goreplay/http_client.go:147 +0x367
panic(0x82dfe0, 0x2026e010)
	c:/go/src/runtime/panic.go:458 +0x40b
github.com/buger/goreplay/proto.Path(0x2203a000, 0x1b, 0x19000, 0x0, 0x0, 0x0)
	C:/Work/src/github.com/buger/goreplay/proto/proto.go:348 +0xcf
github.com/buger/goreplay/proto.Status(0x2203a000, 0x1b, 0x19000, 0x0, 0x0, 0x0)
	C:/Work/src/github.com/buger/goreplay/proto/proto.go:448 +0x3f
main.(*HTTPClient).Send(0x21a37e80, 0x22782000, 0x18d3, 0x2000, 0x0, 0x0, 0x0, 0x0, 0x0)
	C:/Work/src/github.com/buger/goreplay/http_client.go:209 +0x1f55
main.(*HTTPOutput).sendRequest(0x20f84780, 0x21a37e80, 0x23e6ee00, 0x1911, 0x1911)
	C:/Work/src/github.com/buger/goreplay/output_http.go:205 +0x234
main.(*HTTPOutput).startWorker(0x20f84780)
	C:/Work/src/github.com/buger/goreplay/output_http.go:125 +0x1a4
created by main.(*HTTPOutput).workerMaster
	C:/Work/src/github.com/buger/goreplay/output_http.go:99 +0x73

**Comment by nlmunro** [comment]
Though I suppose it is safe to say that as soon as I start getting these, the server has maxed-out!

**Comment by buger** [comment]
Ouch, I'll fix this in next release. Thank you for fuzz testing :)

**Comment by buger** [comment]
I think it happens when server times out and return empty response from the server. Should be fixed in 0.6.1
