### ISSUE TITLE
Missing requests when using TCP aggregation?

### ISSUE THREAD

**Issue by nlmunro** [buger/goreplay#464]
I have been testing multiple front-ends using aggregation like this:

Front Ends
 --input-raw :80 --output-tcp capture_server:28020

Capture Server
--input-tcp capture_server:28020 --output-file=network.log --output-file-append

Now I am pretty sure that while this works in general, some requests are being dropped (I am doing a test now to to local captures and compare the merged files). Are these settings correct? Am I missing something?

**Comment by nlmunro** [comment]
Also tried without --output-file-append and it is the same, it is dropping some requests compared to saving to separate local files.

**Comment by buger** [comment]
Hello! Settings are indeed correct, looks like a bug.

**Comment by nlmunro** [comment]
It is hard to absolutely confirm this as the load balancer could also be to blame - I'll do more tests to verify it.

**Comment by nlmunro** [comment]
Actually after reconfiguring the load balancer, I think it was at fault - sorry!
