### ISSUE TITLE
Goreplay and Virtual Host

### ISSUE THREAD

**Issue by sachavuk** [buger/goreplay#466]
Hello,

I want to capture traffic from one virtual host. I didn't find any documentation about virtual host, how to capture traffic from Apache/Nginx with many virtual hosts?

**Comment by buger** [comment]
II think best way to do it will be filtering by `Host` HTTP header.

**Comment by sachavuk** [comment]
Hi Buger, 

Thanks for your answer. Do you mean this parameter -http-original-host ?

**Comment by buger** [comment]
Not exactly, I mean `--http-allow-header`, in your case it will be: `--http-allow-header "Host:vhost.com"`.

`--http-original-host` is used when you want to retain original Host header when replaying traffic (for example if your target host also support virtual hosts, and you want to replay traffic for all of them).

**Comment by sachavuk** [comment]
Thanks @buger It's works !!

**Comment by buger** [comment]
Glad it helped!
