### ISSUE TITLE
Unable to capture upstream traffic in nginx reverse proxy setup

### ISSUE THREAD

**Issue by killdash9** [buger/goreplay#469]
We terminate SSL at an nginx reverse proxy.  When I run gor on the upstream apache servers, gor apparently captures nothing.  I'm running

`sudo ./gor --input-raw :8080 --output-stdout --verbose --stats --debug`

Nothing gets printed to standard out except for
```
[DEBUG][PID 26622][1498003058314756466][1498003058314.756348ms] Listening for traffic on: :8080
Version: 0.16.0
```

This is a surprise since the server is receiving a ton of customer traffic, which I confirmed by tailing the apache request log.  However, when I make a test HTTP request directly to one of the upstream servers, gor sees and prints it to stdout as expected.  Furthermore, the test request appears in the apache request log as one would expect, mixed in with the customer traffic coming via the nginx reverse proxy.  

Any idea why gor would not be capturing the nginx-proxied requests?

**Comment by buger** [comment]
Hello!

What is the OS are you using, and do you use docker?

Do you have any specific network interfaces like tunnels?

Also, try specify direct IP to the `--input-raw` command `gor --input-raw IP:8080`

Thank you!

**Comment by killdash9** [comment]
Yes, there is a tunnel interface.  That seems to be the difference, although I still can't get it to work.  Using netstat I can tell that reverse proxy connections are coming in on the `tunl0` interface and my direct connections are coming on the `em1` interface.

When I try specifying the IP address of the tunnel interface,

`sudo ./gor --input-raw 10.xxx.x.xxx:8080 --output-stdout`

gor doesn't see the reverse proxy requests or direct requests.  Here's my ifconfig with addresses masked:

```
em1       Link encap:Ethernet  HWaddr xx:xx:xx:xx
          inet addr:10.xxx.xx.xx  Bcast:10.xxx.xx.xxx  Mask:255.255.255.0
          inet6 addr: 2620:xx:xxxx:xxxx:xxx:xxx:xxxx:xxxx/64 Scope:Global
          inet6 addr: fe80::xxx:xxx:xxxx:xxxx/64 Scope:Link
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:11237619294 errors:0 dropped:0 overruns:0 frame:0
          TX packets:11358042109 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000 
          RX bytes:6879262405748 (6.2 TiB)  TX bytes:5219983559137 (4.7 TiB)
          Memory:df980000-df9fffff 

lo        Link encap:Local Loopback  
          inet addr:127.0.0.1  Mask:255.0.0.0
          inet6 addr: ::1/128 Scope:Host
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:5847945 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5847945 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:1232929395 (1.1 GiB)  TX bytes:1232929395 (1.1 GiB)

tunl0     Link encap:IPIP Tunnel  HWaddr   
          inet addr:10.xxx.x.xxx  Mask:255.255.255.255
          UP RUNNING NOARP  MTU:1480  Metric:1
          RX packets:0 errors:0 dropped:0 overruns:0 frame:0
          TX packets:0 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:0 
          RX bytes:0 (0.0 b)  TX bytes:0 (0.0 b)
```

**Comment by buger** [comment]
This may be helpful https://unix.stackexchange.com/questions/122468/how-does-one-capture-traffic-on-virtual-interfaces

Traffic going through tunneling interface actually goes through localhost.

**Comment by killdash9** [comment]
I'm not sure what that means in terms of gor parameters.  I tried `--input-raw localhost:8080`, `--input-raw 127.0.0.1:8080` with no luck.  The stackexchange link you gave is about a problem where tcpdump isn't able to see the traffic.  As I said, I  _am_ able to see the traffic with tcpdump on the `em1` interface.  The mystery to me is why tcpdump can see it but gor cannot.  Is there a way to pipe tcpdump output directly into gor?

**Comment by buger** [comment]
You can also specify interface directly to GoReplay, for example `em1:8080`. 

Also you can read pcap files produced by tcpdump using `--input-raw ./file.pcap --input-raw-engine pcap_file` (where last `pcap_file` is a keyword).

**Comment by killdash9** [comment]
I was able to get things working like this:

sudo tcpdump -c 1000 -i em1 -l -w - dst port 8080 | ./gor 
--input-raw - --output-stdout --input-raw-engine pcap_file

Thank you.

Leonid Bugaev writes:

> You can also specify interface directly to GoReplay, for example 
> em1:8080.
>
> Also you can read pcap files produced by tcpdump using 
> --input-raw ./file.pcap --input-raw-engine pcap_file (where last 
> pcap_file is a keyword).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the 
> thread.


-- 
Russell Black
Newspapers.com

**Comment by eddie4** [comment]
> You can also specify interface directly to GoReplay, for example `em1:8080`.

@buger 
This does not seem to be the case for the loopback interface

```
~# tcpdump host 127.0.198.9
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on enp4s0f0, link-type EN10MB (Ethernet), capture size 262144 bytes
^C
0 packets captured
0 packets received by filter
0 packets dropped by kernel
```


```
~# tcpdump host 127.0.198.9 -i lo
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on lo, link-type EN10MB (Ethernet), capture size 262144 bytes
13:20:03.844404 IP localhost.46782 > 127.0.198.9.http: etc.....
3 packets captured
6 packets received by filter
0 packets dropped by kernel
```

I think this is the reason that the following gives no output
```
./gor --input-raw lo:80 --output-stdout
./gor --input-raw 127.0.198.9:80 --output-stdout
```
