### ISSUE TITLE
gor_0.16.0_x64 binary doesn't work

### ISSUE THREAD

**Issue by majones713** [buger/goreplay#473]
OS: WIN 7 x64

Downloaded latest Windows binary and uncompressed and got below error

C:\gor_0.16.0_x64>gor
'gor' is not recognized as an internal or external command,
operable program or batch file.

I was able to compile my own gor.exe though and it worked but discovered the one provided in download section doesn't.

**Comment by buger** [comment]
x64 version, in this case, means Linux x64. It is common notation. But yeah, I plan to release windows binariest in near future.

**Comment by majones713** [comment]
ahhhh OK.  Thanks!
