### ISSUE TITLE
How to build on Mac?

### ISSUE THREAD

**Issue by kustuntas** [buger/goreplay#482]
`go build -ldflags "-extldflags \"-static\""`
This does not build on Mac. 
`ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1`

I searched internet, and apparently Mac OS X does not support static linking.

If I build without the `-ldflags`, it generates `gor` binary, but it does not work; generates error: `./gor: line 1: syntax error: unexpected word (expecting ")")`
 
Is there a workaround?

**Comment by buger** [comment]
You are right, on Mac only dynamic linking is possible. But that's how I actually do the Mac builds,  and it works great. See the Makefile for more details.

**Comment by kustuntas** [comment]
The problem is that after I build it I need to run it inside a container from alpine image. Anyways, I found a solution. Thanks to Dockerfile.dev which basically is container for development. I built it there and extracted the files to build the goreplay container. Works like a charm!
