### ISSUE TITLE
100-Continue Logic Fails on Encountering a Zero-Length ACK.

### ISSUE THREAD

**Issue by TheJoCr** [buger/goreplay#496]
I'll start with the code to reproduce this bug, taken from `listener_test.go`.
The first test passes. The second one fails. 
```go
func TestSingleAck100Continue(t *testing.T) {
	listener := NewListener("", "0", EnginePcap, true, 10*time.Millisecond, "")
	defer listener.Close()

	reqPacket1 := buildPacket(
		true,
		1,
		1,
		[]byte("POST / HTTP/1.1\r\nExpect: 100-continue\r\nContent-Length: 4\r\n\r\n"), time.Now())

	respPacket1 := buildPacket(false,
		uint32(len(reqPacket1.Data)) + reqPacket1.Seq,
		1,
		[]byte(""), time.Now())

	respPacket2 := buildPacket( false,
		uint32(len(reqPacket1.Data)) + reqPacket1.Seq,
		1,
		[]byte("HTTP/1.1 100 Continue\r\n"), time.Now())

	reqPacket3 := buildPacket(true,
		uint32(len(reqPacket1.Data)) + respPacket1.Seq,
		reqPacket1.Seq+uint32(len(reqPacket1.Data)),
		[]byte("DATA"), time.Now())

	respPacket3 := buildPacket(false,
		uint32(len(reqPacket3.Data)) + reqPacket3.Seq,
		respPacket1.Seq+uint32(len(respPacket1.Data)),
		[]byte("HTTP/1.1 200 OK\r\n\r\n"), time.Now())

	result := []byte("POST / HTTP/1.1\r\nContent-Length: 4\r\n\r\nDATA")

	testRawListener100Continue(t, listener, result,
		reqPacket1,
		respPacket1, respPacket2,
		reqPacket3,
		respPacket3 )
}


func TestDoubleAck100Continue(t *testing.T) {
	listener := NewListener("", "0", EnginePcap, true, 10*time.Millisecond, "")
	defer listener.Close()

	reqPacket1 := buildPacket(
		true,
		1,
		1,
		[]byte("POST / HTTP/1.1\r\nExpect: 100-continue\r\nContent-Length: 4\r\n\r\n"), time.Now())

	respPacket1 := buildPacket(false,
		uint32(len(reqPacket1.Data)) + reqPacket1.Seq,
		1,
		[]byte(""), time.Now())

	respPacket2 := buildPacket( false,
		uint32(len(reqPacket1.Data)) + reqPacket1.Seq,
		1,
		[]byte("HTTP/1.1 100 Continue\r\n"), time.Now())

	reqPacket2 := buildPacket(true,
		uint32(len(reqPacket1.Data)) + respPacket1.Seq,
		reqPacket1.Seq+uint32(len(reqPacket1.Data)),
		[]byte(""), time.Now())

	reqPacket3 := buildPacket(true,
		uint32(len(reqPacket1.Data)) + respPacket1.Seq,
		reqPacket1.Seq+uint32(len(reqPacket1.Data)),
		[]byte("DATA"), time.Now())

	respPacket3 := buildPacket(false,
		uint32(len(reqPacket3.Data)) + reqPacket3.Seq,
		respPacket1.Seq+uint32(len(respPacket1.Data)),
		[]byte("HTTP/1.1 200 OK\r\n\r\n"), time.Now())

	result := []byte("POST / HTTP/1.1\r\nContent-Length: 4\r\n\r\nDATA")

	testRawListener100Continue(t, listener, result,
		reqPacket1,
		respPacket1, respPacket2,
		reqPacket2, reqPacket3,
		respPacket3 )
}
```

The only difference is the addition of a single packet called `reqPacket2`, which is a zero length ACK of the `HTTP/1.1 100 Continue` in `respPacket2`. Despite this kind of exchange being perfectly valid TCP, Go Replay's handling of the `Expect: 100-continue` header fails. The result is that it is unable to generate a HTTP request from the packets. 

For a broader context, this bug was originally triggered in our production system when we made a request through a load-balancer. Since both 1) the LB ACKed the `HTTP/1.1 100 Continue` response with a zero length TCP packet, and 2) the client ACKed the same `HTTP/1.1 100 Continue` in his next request (with the same ACK number), we encountered this bug. The impact is very large - all PUT and POST requests with `Expect: 100-continue` headers are dropped. The response to those requests in generally recorded as a separate request. We often end up with requests that have no body or headers, but only a `HTTP/1.1 100 Continue` status line. 

I will be investigating a code fix, but would appreciate whatever help I can get.

**Comment by buger** [comment]
Should be fixed by https://github.com/buger/goreplay/commit/e310fc8369899f153eef844140c56bfa94ec658b

Attaching binaries 
[gor_v0.17.RC2_mac.tar.gz](https://github.com/buger/goreplay/files/1273073/gor_v0.17.RC2_mac.tar.gz)
[gor_v0.17.RC2_x64.tar.gz](https://github.com/buger/goreplay/files/1273074/gor_v0.17.RC2_x64.tar.gz)

Scheduled for release in 0.17
