### ISSUE TITLE
Forwarding request to https server not working

### ISSUE THREAD

**Issue by vinayathimmappa** [buger/goreplay#498]
Hello all,
This is a question 
i am trying forward a request on localhost to a https server. But it is not working. I did put verbose and only thing that is shown is  Connecting to "https://server" and then it gets stuck there. Is there anyway i can figure out what is happening or do i need to use nginx for forwarding to https server

**Comment by buger** [comment]
It should support replaying to https endpoints. More over it skip certificate validation but sets `ServerName` https://github.com/buger/goreplay/blob/master/http_client.go#L95, which potentially can be your issue. 

Try to set proper `server_name` for your HTTPS server, or change goreplay HTTP output point to the different server name. 

So maybe if you have local https server, make sense query it using IP?

**Comment by vinayathimmappa** [comment]
@buger  Thanks for the reply. 

 >maybe if you have local https server, make sense query it using IP?
I used Nginx for proxy passing to https server and it works fine
