### ISSUE TITLE
write tcp 127.0.0.1:8401->127.0.0.1:45736: i / o timeout

### ISSUE THREAD

**Issue by penhauer-xiao** [buger/goreplay#507]
```
./gor --input-file "request*.gor|100%" --output-http "127.0.0.1:8401/api/clear-content" &
```
After a while,  my clear-content service reported an error:  write tcp 127.0.0.1:8401->127.0.0.1:45736: i / o timeout

http write after a period of time, write tcp 127.0.0.1:8401->127.0.0.1:45736: i / o timeout, followed by continue to write, CPU load has been very high, I guess because goreplay, has not read( Or read busy, but goreplay every few seconds to send a request. ), Resulting in http write after the full, can not continue to write new data,

**Comment by buger** [comment]
Hello! May I wonder why you closed it?

**Comment by penhauer-xiao** [comment]
@buger  The problem was found, a third party pack depleted the resources that caused tcp write to fail. Thank you.
