### ISSUE TITLE
Log requests in a readable format

### ISSUE THREAD

**Issue by nlmunro** [buger/goreplay#511]
I find the --stats and --verbose options of limited use, so I made this very simple NodeJS based middleware, which gives the time, method and enough of the url to see what's happening. The result is something like this:

```
2017-09-06 03:08:47.593Z GET  /ER_CTAS_UI/Prescriptions.aspx
2017-09-06 03:08:49.600Z HEAD /
2017-09-06 03:08:52.170Z POST /ER_CTAS_UI/Speciality.aspx
```

---- debug.js

    var gor = require("goreplay_middleware");
    gor.init();
    //just log requests in readable format
    gor.on("request", function(req) {
        let ts = UnixNanoToTimestamp(req.meta[2]);
        let method = gor.httpMethod(req.http);
        if (method.length < 4) method += ' '; //fixed formatting
        let reg = gor.httpPath(req.http).match(/^(.*)\?+/); //ignore query params, just show base url
        let path = gor.httpPath(req.http); //fallback if no query string
        if (reg && reg.length > 1) path = reg[1];
        path = path.substring(0,50); //clip to avoid wrapping in console
        console.error(ts+' '+method+' '+path);
        return req;
    });

    function UnixNanoToTimestamp(nano){
        if (!nano) return;
        let ms = parseInt(nano.substring(0,13)); //Very crude nS => mS
        let date = new Date(ms); 
        return date.toISOString().replace('T',' '); //Clean string
    }

**Comment by buger** [comment]
Why not just use --output-file and write to it? Just trying to understand your use-case. 

Thank you!

**Comment by nlmunro** [comment]
I just find it useful to see a summary of what's happening during replay - I don't want the whole content.

**Comment by buger** [comment]
Ah, I see, totally make sense! 

Will add this somewhere to the docs.
