### ISSUE TITLE
Capture generic HTTP traffic

### ISSUE THREAD

**Issue by gabdu** [buger/goreplay#515]
Gor usage model appears as if it supports only capture and replay at webserver level (looking at request and response stuff). Can it be used to capture http traffic passively between any two service talking http? 

E.g. A python service call -> REST API of -> node service listening on port 100

Can we capture and replay everything on port 100?

**Comment by gabdu** [comment]
To clarify a little more, I can capture request and replay it but what about the response? Is it available only on stdout where capture happens or it can be made available at the replayer -> further upstream side somehow?

**Comment by buger** [comment]
Well, frankly I'm not sure about your use case. Using --input-raw-track-response, GoReplay will record responses as well. But I feel like you want to make it act more like a mock, i'm right?

**Comment by gabdu** [comment]
Yes, I am talking about mock. Guess that would require injection of response something which can be done only if Gor is a proxy which it is not (and it shouldn't be).

**Comment by buger** [comment]
I believe something like this should be possible by writing a middleware, which reads requests, and internally starts own http server, and try to response on requests based on known responses. This is a nice to have built-in, but can't tell any eta.
