### ISSUE TITLE
Add Middleware 2.0 to Wiki

### ISSUE THREAD

**Issue by wt0317** [buger/goreplay#516]
Middleware 2.0 (aka NodeJS goreplay_middleware) looks great. You should definitely add a note about it on the Middleware Wiki. 

I was about to implement a solution based off of one of the middleware examples but goreplay_middleware looks so much easier to use.

**Comment by buger** [comment]
Actually, it includes the link to the framework in the first paragraph. Probably shoule make it more noticable.
