### ISSUE TITLE
how to set proxy while replaying

### ISSUE THREAD

**Issue by salomon1184** [buger/goreplay#519]
I‘d like to replay http request to target web server，meanwhile set proxy to a fuzz proxy（just like fiddler）to gernerate some bad requests， but goreplay seems not support setting http proxy， is there a plan to support this situation？

**Comment by buger** [comment]
You can try set proxy via HTTP_PROXY environment variable like this: `export HTTP_PROXY="http://proxyIp:proxyPort"`

GoReplay itself has no any specific support for proxies, but underlying Go network step should respect ENV variable mentioned above.

**Comment by salomon1184** [comment]
I have tried, but It doesn't seem work.

**Comment by mattrobenolt** [comment]
Just to chime in here, `HTTP_PROXY` definitely doesn't work because gor uses it's own HTTP client. The `HTTP_PROXY` support in native Go, is a part of the HTTP transport, which isn't leveraged here. It's not a network/tcp level thing, it's a change to the way HTTP requests are formed and sent.

https://github.com/buger/goreplay/blob/master/http_client.go#L86-L106

I'm looking to add this in a fork, just something hacky to make it work for my use case.

**Comment by zhizouxiao** [comment]
There is way to do it which is kind of trickey. you can request the proxy with modified header. For example, `goreplay   --input-file "requests.gor"   --output-http http://proxy_host:proxy_port/request_path -http-set-header "Host:request_host"`

**Comment by nagendra547** [comment]
I am also facing the same problem. Looks like goreplay is not following the  http proxy set in environment.

**Comment by nagendra547** [comment]
@mattrobenolt  How did you make it work with your fix?  Did you replay like this?

> http_proxy=http://proxy_server:proxy_port
> https_proxy=http://proxy_server:proxy_port
> 
> ./gor --input-file file.log --output-stdout  --output-http destination-host:80  --output-http-track-response

**Comment by mattrobenolt** [comment]
@nagendra547 I forked goreplay and added support for it.

See: https://github.com/mattrobenolt/goreplay/tree/http-proxy

I used this in a production setting just fine without any issues.

**Comment by buger** [comment]
@mattrobenolt love it! Can you create a pull request? 

Thank you!

**Comment by mattrobenolt** [comment]
@buger https://github.com/buger/goreplay/pull/655 enjoy. :)

**Comment by nagendra547** [comment]
@mattrobenolt  Thanks ! Let me try it out.  For building the binaries are you using this step mentioned 

https://github.com/buger/goreplay/wiki/Compilation

Or building in some different way?

**Comment by mattrobenolt** [comment]
Yeah, it would  have been that. It's been a while, but that seems right.

**Comment by nagendra547** [comment]
Thanks @mattrobenolt . Worked like a charm! :)

**Comment by buger** [comment]
Just released RC2 with this change https://github.com/buger/goreplay/releases/tag/v1.0-rc2
