### ISSUE TITLE
Can't record traffic in a container.

### ISSUE THREAD

**Issue by wenjinchao** [buger/goreplay#526]
execute following command on a container like docker:
goreplay -input-raw-track-response -input-raw :3000 --output-file ./gor-%Y-%m-%d-%H.gor --output-file-append false

and get errors:
017/10/24 20:53:33 Can't find interfaces with addr: . Provide available IP for intercepting traffic:
Name: any
Description: Pseudo-device that captures on all interfaces
Name: nflog
Description: Linux netfilter log (NFLOG) interface
Name: nfqueue
Description: Linux netfilter queue (NFQUEUE) interface
Name: usbmon1
Description: USB bus number 1
Name: usbmon2
Description: USB bus number 2

I tried add prefix before port such "eth0:3000" "eth1:3000", and get the same error.
Any help?
Thanks a lot!

jinchao

**Comment by buger** [comment]
Can you try with "any:3000" ?

**Comment by wenjinchao** [comment]
It doesn't work:

2017/10/25 09:59:14 Can't find interfaces with addr: any. Provide available IP for intercepting traffic:
Name: any
Description: Pseudo-device that captures on all interfaces
Name: nflog
Description: Linux netfilter log (NFLOG) interface
Name: nfqueue
Description: Linux netfilter queue (NFQUEUE) interface
Name: usbmon1
Description: USB bus number 1
Name: usbmon2
Description: USB bus number 2

**Comment by wenjinchao** [comment]
This problem is fixed by changing CentOS from 4.3 to 6.3.

**Comment by buger** [comment]
👌
