### ISSUE TITLE
What's the exactly meaning of 2x speed when talking about performance testing?

### ISSUE THREAD

**Issue by wenjinchao** [buger/goreplay#531]
docs from wiki: 
# Replay from file on 2x speed 
gor --input-file "requests.gor|200%" --output-http "staging.com"

I'am wondering how 2x speed is executed?
For example,  there's some requests in file of requests.gor,  goreplay will send the second request  for every request immediately after the original one? 

If there is interval  between two original requests,  does goreplay will replay requests in the same interval?

Thanks!

JinChao

**Comment by buger** [comment]
So basically it squeezes interval between requests by this percent.

**Comment by wenjinchao** [comment]
Thanks！
