### ISSUE TITLE
Repo activity

### ISSUE THREAD

**Issue by GiovanniPaoloGibilisco** [buger/goreplay#539]
Hi, is this repo still in active development?

**Comment by TheJoCr** [comment]
I made a PR 3 weeks ago and haven't heard anything about it yet.

**Comment by slimus** [comment]
@GiovanniPaoloGibilisco @TheJoCr Hi! Yes, we have stable version 1 and now developing new version. If you have any issue\question\idea feel free to create new issue with details. Thanks!
