### ISSUE TITLE
master: Some code error

### ISSUE THREAD

**Issue by monotone** [buger/goreplay#540]
https://github.com/buger/goreplay/blob/bf8198d6391b4713b39870be6fd8e17910ee3af9/http_client.go#L301

I was founding a issue from version 0.16.1, but I got the master source code( I have known it`s not the source code of v0.16.1), so I seen this code:

```go
	if err != nil && readBytes == 0 {
		maxRead := 100
    	        if readBytes < maxRead {
    		    maxRead = readBytes
    	        }
		Debug("[HTTPClient] Response read timeout error", err, c.conn, readBytes, string(c.respBuf[:maxRead]))
		response = errorPayload(HTTP_TIMEOUT)
		c.Disconnect()
		return
	}
```

This make a mistake, and `maxRead` will always be zero.

**Comment by slimus** [comment]
Hi @monotone ! Please look at master branch. Thank you for your issue!
