### ISSUE TITLE
2018/02/07 09:43:01 Failed to start Sarama(Kafka) consumer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

### ISSUE THREAD

**Issue by satishmane** [buger/goreplay#551]
Hi,

1. I have 3 node kfka cluster = kafka version 0.10.0.0. - server1, server2 and server3

2. I installed goreplay latest version 0.16.1 outside kafka cluster on separate server4.

3. From server4, did connectivity test using ping and telnet to IP address and ports. It connects successfully.

4. Then executed below goreplay command from command line and got error.

5. ubuntu@> /opt/goreplay --input-kafka-host 'server1-IP:9092,server2IP:9092,server3IP:9092' \
--input-kafka-topic 'Test' --output-stdout
Got below error
2018/02/07 09:43:01 Failed to start Sarama(Kafka) consumer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?)

Please guide me to resolve this error.

thanks

**Comment by satishmane** [comment]
**Solved issue " 2018/02/07 09:43:01 Failed to start Sarama(Kafka) consumer: kafka: client has run out of available brokers to talk to (Is your cluster reachable?) "**

**Fix :** In  input_kafka.go file => changed 
con, err = sarama.NewConsumer([]string{config.host}, c) to 
con, err = sarama.NewConsumer(strings{config.host,",), c)

2. Solved issue "2018/02/27 11:08:56 meta: 1
panic: runtime error: index out of range

goroutine 51 [running]:
main.CopyMulty(0x7f570edc3498, 0xc42123c210, 0xc4211c4ce0, 0x1, 0x1, 0xf2126c090, 0xf)
	/opt/aeris/goreplay/src/github.com/buger/gor/emitter.go:71 +0xebc
created by main.Start
	/opt/aeris/goreplay/src/github.com/buger/gor/emitter.go:34 +0xb8"

Fix : in emitter.go file, changed as below

requestID := string(meta[1]) to requestID := string(meta[0])

**Comment by buger** [comment]
Fixed by https://github.com/buger/goreplay/pull/555
