### ISSUE TITLE
How to merge/split  traffic from multiple endpoints

### ISSUE THREAD

**Issue by nderzhak** [buger/goreplay#554]
We have multiple endpoints for HA/load balancing reasons. To reconstruct production traffic recorded on all those nodes we would need to merge all recorded files in to one.

I noticed in recording file timestamps are not in exact order but seems to be played in order. Is that right ?

Will concatenating and sorting all records by timestamp do the job ?

Also in the future we would like to split merged file to run on N clients to emulate real clients.

We plan to split by sessions/source IP. Ideas ?

I believe we are not first who tries to do this. I know google groups would be more appropriate , just do not see any activity there.

**Comment by buger** [comment]
@nderzhak GoReplay can read multiple files in parallel and concatenate/replay request in the right order automatically. Just provide pattern instead of the direct path. No additional work needed.

Regarding replaying sessions, this is what GoReplay PRO can do, more info here https://github.com/buger/goreplay/wiki/%5BPRO%5D-Recording-and-replaying-keep-alive-TCP-sessions

Hope it helps!

**Comment by nderzhak** [comment]
Very helpful  ! Thank you !

**Comment by nikolaiderzhak** [comment]
Sorry. Actually I what is proper parameters format for multiple input files ?

Tried like 
```
--input-file '/data/traffic/h1_requests_0.gor|100%' --input-file '/data/traffic/h2_requests_0.gor|100%' 
```
did not help so far. Going to check source.

**Comment by nikolaiderzhak** [comment]
I am getting panic right away:
```
oroutine 36 [running]:
panic(0xa58cc0, 0xc82000e130)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
main.(*FileOutput).Write(0xc820170000, 0xc821c44000, 0x417, 0x500000, 0xc822320ff0, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/output_file.go:212 +0x242
main.CopyMulty(0x7f790860f9b8, 0xc821167740, 0xc82116f220, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/emitter.go:121 +0x102b
created by main.Start
        /go/src/github.com/buger/goreplay/emitter.go:28 +0x4b2
```

**Comment by nikolaiderzhak** [comment]
Seems outputFile       MultiOption is string array too. Let me try to match number inpout and output files.

**Comment by nikolaiderzhak** [comment]
Ok. It works. But not sure how to apply limit rate now. Only to first one of input files ?

**Comment by nikolaiderzhak** [comment]
And it panics in few minutes...

```
panic: runtime error: slice bounds out of range

goroutine 21 [running]:
panic(0xa58cc0, 0xc82000e0f0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
bufio.(*Writer).Write(0xc821d24880, 0xc8298f6ad0, 0xe, 0x10, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:596 +0x277
main.(*FileOutput).Write(0xc820199a40, 0xc821e1e000, 0x442, 0x500000, 0x442, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/output_file.go:213 +0x2d7
main.CopyMulty(0x7f6fef7f0608, 0xc82007e500, 0xc820057800, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/emitter.go:121 +0x102b
created by main.Start
        /go/src/github.com/buger/goreplay/emitter.go:28 +0x4b2
panic: runtime error: slice bounds out of range

goroutine 20 [running]:
panic(0xa58cc0, 0xc82000e0f0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
bufio.(*Writer).Write(0xc821d24880, 0xc8264671d0, 0xe, 0x10, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:596 +0x277
main.(*FileOutput).Write(0xc820199a40, 0xc8217c6000, 0x413, 0x500000, 0x413, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/output_file.go:213 +0x2d7
main.CopyMulty(0x7f6fef7f0608, 0xc82007e410, 0xc820057800, 0x3, 0x4, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/emitter.go:121 +0x102b
created by main.Start
        /go/src/github.com/buger/goreplay/emitter.go:28 +0x4b2
```

**Comment by buger** [comment]
I see, well I actually was mentioning using file pattern instead with 1 file input, only in this case it will concat requests in right order. See this doc on pattern format https://golang.org/pkg/path/filepath/#Match

Regarding panic, I will check what it can be, maybe some concurrency issue because of multiple inputs.

**Comment by nikolaiderzhak** [comment]
Pattern ! Sorry - totally missed that in first place. I got used to regexp term :)  Thank you !

**Comment by nikolaiderzhak** [comment]
Do you want me to file issue for /usr/local/go/src/bufio/bufio.go:596 panic ? It happens at all random moments even for 100% speed. And target cluster seems not under load.

**Comment by nikolaiderzhak** [comment]
One file replay if fine at not too fast speed/%. But two  files (pattern) gives us panic after few minutes.

That is on 0.16.1 . Should I try master build ?

**Comment by nikolaiderzhak** [comment]
Nope. One file fails too, but after 20m vs 10m for this specific recording  :(

**Comment by buger** [comment]
[gor_DEV-1519933432_mac.tar.gz](https://github.com/buger/goreplay/files/1772554/gor_DEV-1519933432_mac.tar.gz)
[gor_DEV-1519933407_x64.tar.gz](https://github.com/buger/goreplay/files/1772555/gor_DEV-1519933407_x64.tar.gz)

Pls try these binaries from latest master

**Comment by nikolaiderzhak** [comment]
Thanks. Will do ASAP.

**Comment by nikolaiderzhak** [comment]
Provided binary is actually stable ! No panics so far. 

But I can not set replay speed now. It seems fixed now.

Getting the same speed for both commands here (and any other percent speed in CMD):

```
./gor --input-file '/data/traffic/h[12]_requests_0.gor|400%'
./gor --input-file '/data/traffic/h[12]_requests_0.gor|100%'
```
output:
```
018/03/02 03:57:30 output_http:0,0,0,190,38,1008
2018/03/02 03:57:35 output_http:0,0,0,185,37,1008
2018/03/02 03:57:40 output_http:0,0,0,189,37,1008
2018/03/02 03:57:45 output_http:0,0,0,186,37,1008
2018/03/02 03:57:50 output_http:0,0,0,190,38,1008
2018/03/02 03:57:55 output_http:0,0,0,185,37,1008
2018/03/02 03:58:00 output_http:0,0,0,188,37,1008
```

I tried to play with --output-http-workers=1000/500 (was) with no changes.

Do you have idea ? Thank you for stabilization fix !

**Comment by buger** [comment]
I wonder if it is somehow related to filter pattern you have, try without pattern to confirm my theory.

Also, try to add `--verbose --debug` logs, maybe it will show something.

**Comment by nikolaiderzhak** [comment]
"|nnn% " does not work either. :( 

Really low 10% or 20% gave me lower count/s. 

But anything bigger then 30%  results in the same  numbers.

For different inout files I have is different limit. So seems changes in rate algorithm were introduced in newer version you gave me.

**Comment by buger** [comment]
hm, can it be that system you are replaying too, is a slow enough to process this speed?

**Comment by nikolaiderzhak** [comment]
I use pretty big m4.xlarge for load-test client - in the peered VPC to tested cluster.

And it works with 0.16.1 - just get random panics.

I get pretty decent RPMs on NewRelic.

This is 0.16.1 with 300%
```
018/03/02 19:15:44 output_http:0,0,0,409,81,109
2018/03/02 19:15:49 output_http:0,0,0,435,87,109
2018/03/02 19:15:54 output_http:0,0,0,457,91,109
```
But it panics in about 5minutes after start.

The same file and settings, but DEV binary gives me:

```
018/03/02 19:19:49 output_http:0,0,0,47,9,108
2018/03/02 19:19:54 output_http:0,0,0,48,9,108
2018/03/02 19:19:59 output_http:0,0,0,47,9,108
```
Does not fail. But probably because lower replay speed :) ?

**Comment by nikolaiderzhak** [comment]
One more note. I ramped up workers number and limits in kernel to have 15000 workers. Trying to find good number.

And it seems during replay process is keeps lot of orphaned connection behind. So eventually it grows too big.

This 5k just in 2 minutes.
```
root@ip-172-100-0-154:/home/ubuntu/load-test# lsof -i -n -P| wc -l
5113
root@ip-172-100-0-154:/home/ubuntu/load-test# lsof -i -n -P| grep CLOSE_WAIT| wc -l
5107
```

**Comment by nikolaiderzhak** [comment]
So yeah. With 15000 workers it grew to like 12000 connection and boom , died.
```
root@ip-172-100-0-154:/home/ubuntu/load-test# FILE=/tmp/lsof-snapshot.out; lsof -i -n -P 2>&1 > $FILE; echo -n 'CONNECTIONS '; cat $FILE| wc -l; echo -n 'CLOSE_WAIT  '; cat $FILE| grep CLOSE_WAIT| wc -l
CONNECTIONS 11963
CLOSE_WAIT  11953
root@ip-172-100-0-154:/home/ubuntu/load-test# FILE=/tmp/lsof-snapshot.out; lsof -i -n -P 2>&1 > $FILE; echo -n 'CONNECTIONS '; cat $FILE| wc -l; echo -n 'CLOSE_WAIT  '; cat $FILE| grep CLOSE_WAIT| wc -l
CONNECTIONS 6
CLOSE_WAIT  0
```

```
2018/03/02 22:06:58 output_http:0,0,0,573,114,15009
2018/03/02 22:07:03 output_http:0,0,0,438,87,15009
panic: runtime error: slice bounds out of range

goroutine 23 [running]:
panic(0xa58cc0, 0xc82000e0e0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
bufio.(*Writer).flush(0xc824b39680, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:562 +0x2a7
bufio.(*Writer).Write(0xc824b39680, 0xc821488000, 0x8c0d, 0x500000, 0x0, 0x0, 0x0)
        /usr/local/go/src/bufio/bufio.go:598 +0x265
main.(*FileOutput).Write(0xc82016e000, 0xc821488000, 0x8c0d, 0x500000, 0xc8d2f6ae70, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/output_file.go:212 +0x248
main.CopyMulty(0x7fa7783d77d0, 0xc82130e000, 0xc8212ec260, 0x2, 0x2, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/emitter.go:121 +0x102b
created by main.Start
        /go/src/github.com/buger/goreplay/emitter.go:33 +0x60a
```

**Comment by nikolaiderzhak** [comment]
So I just ramped up workers to 30k and fine now. Use 0.16.1 as I can control replay speed there.

**Comment by nikolaiderzhak** [comment]
Yes. I can confirm we should close sockets there.

Once it hits workers number it dies:
```
2018/03/02 23:40:23 output_http:0,0,0,371,74,25009
panic: runtime error: slice bounds out of range
```
```
Every 10.0s: FILE=/tmp/lsof-snapshot.out; lsof -i -n -P 2>&1 > /tmp/lsof-snapshot.out; echo -n 'CONNECTIONS '; cat $FILE| wc -l; echo -n 'CLOSE_WAIT  '; cat $FILE| grep CLOSE_WAIT| wc -l                     Fri Mar  2 23:40:24 2018

CONNECTIONS 23256
CLOSE_WAIT  23248
```

**Comment by buger** [comment]
Can you pls put the GoReplay full command here, which you used for this testing?

**Comment by nikolaiderzhak** [comment]
It is:
```
INPUT_FILE="/data/4hours_requests.gor"
#INPUT_FILE="/data/traffic/h1_requests_0.gor"
#INPUT_FILE='/data/traffic/h[12]_requests_0.gor'

CMD=goreplay-0.16.1
#CMD=gor
./$CMD \
    --input-file "${INPUT_FILE}|400%" \
    --stats --output-http-stats \
    --output-file="/data/replay/debug.gor" \
    --output-http-workers=25000 \
    --output-http=$OUTPUT \
    --output-http-track-response > test.out 2> test.err
```

**Comment by nderzhak** [comment]
Sorry for turning this thread in Q/A.

But situation is we need to replay production traffic but for load testing purposes.

That means we need more apache benchmarks/siege behavior - where it fires queries as fast as possible.

Any possibility to do this with gor ?

I understand that we we will mess up responses order seriously , but that kind of ok for us in this case.

**Comment by buger** [comment]
Well, this is one of the main use cases for gor, so yes it should work. Doing it with a higher speed is the right way to go. I would still recommend using 0.17 PRE release instead, as it way more stable.

Also, have you tried turning off `-http-output` and `output-http-track-response`, do you see the same issue without them?

**Comment by nderzhak** [comment]
Yes. There is difference.

```
./gor --input-file '/data/4hours_requests.gor|900%' --stats --output-http-stats --output-http=http://... --output-file=/data/replay/debug.gor --output-http-workers=25000
```
without --output-http-track-response
```
2018/03/05 20:35:55 output_http:latest,mean,max,count,count/second,gcount
2018/03/05 20:35:55 output_http:0,0,0,0,0,7
2018/03/05 20:36:00 output_http:0,0,0,977,195,25008
2018/03/05 20:36:05 output_http:0,0,0,546,109,25008
2018/03/05 20:36:10 output_http:0,0,0,555,111,25010
2018/03/05 20:36:15 output_http:0,0,0,728,145,25008
2018/03/05 20:36:20 output_http:0,0,0,602,120,25010
2018/03/05 20:36:25 output_http:0,0,0,527,105,25008
2018/03/05 20:36:30 output_http:0,0,0,257,51,25008
2018/03/05 20:36:35 output_http:0,0,0,777,155,25010
```


```
./gor --input-file '/data/4hours_requests.gor|900%' --stats --output-http-stats --output-http=http://....  --output-http-track-response --output-file=/data/replay/debug.gor --output-http-workers=25000
```
with --output-http-track-response
```
2018/03/05 21:05:30 output_http:latest,mean,max,count,count/second,gcount
2018/03/05 21:05:30 output_http:0,0,0,0,0,15
2018/03/05 21:05:35 output_http:0,0,0,447,89,25010
2018/03/05 21:05:40 output_http:0,0,0,493,98,25008
2018/03/05 21:05:45 output_http:0,0,0,505,101,25008
2018/03/05 21:05:50 output_http:0,0,0,515,103,25008
2018/03/05 21:05:55 output_http:0,0,0,491,98,25011
2018/03/05 21:06:00 output_http:0,0,0,482,96,25009
2018/03/05 21:06:05 output_http:0,0,0,498,99,25008
2018/03/05 21:06:10 output_http:0,0,0,506,101,25008
```

**Comment by buger** [comment]
What if you do it as simple as:

`./gor --input-file '/data/4hours_requests.gor|1800%' --stats --output-http-stats --output-http=http://.... 

Note I also removed `output-http-workers`, because such high value may affect performance, by default Gor pool auto grow. Additionally I increased rate 2X to 1800%.

Can you show me the output of this command?

**Comment by nderzhak** [comment]
I see.  For ./goreplay-0.16.1 --input-file '/data/4hours_requests.gor|1800%' --output-http=http://.. --stats --output-http-stats

I have got:
```
2018/03/06 19:41:44 output_http:0,5,176,1528,305,263
2018/03/06 19:41:49 output_http:0,60,112,1333,266,207
2018/03/06 19:41:54 output_http:0,0,0,1091,218,141
2018/03/06 19:41:59 output_http:0,5,128,1025,205,265
2018/03/06 19:42:04 output_http:15,14,62,991,198,267
2018/03/06 19:42:09 output_http:251,251,490,2237,447,521
2018/03/06 19:42:14 output_http:8,7,201,1836,367,521
2018/03/06 19:42:19 output_http:0,3,9,1528,305,414
2018/03/06 19:42:24 output_http:0,0,0,2127,425,308
2018/03/06 19:42:29 output_http:0,0,0,1566,313,261
2018/03/06 19:42:34 output_http:0,0,0,1348,269,153
2018/03/06 19:42:39 output_http:0,0,0,1510,302,138
2018/03/06 19:42:44 output_http:0,0,0,1729,345,128
2018/03/06 19:42:49 output_http:0,0,0,1802,360,128
2018/03/06 19:42:54 output_http:0,0,0,1564,312,123
2018/03/06 19:42:59 output_http:0,3,7,2008,401,106
2018/03/06 19:43:04 output_http:0,0,0,2652,530,106
2018/03/06 19:43:09 output_http:259,258,446,1194,238,903
2018/03/06 19:43:10 [HTTPClient] Connection error: dial tcp: i/o timeout
2018/03/06 19:43:10 [HTTPClient] Connection error: dial tcp: i/o timeout
2018/03/06 19:43:14 output_http:0,2,432,1630,326,358
2018/03/06 19:43:19 output_http:0,0,0,1316,263,149
2018/03/06 19:43:24 output_http:0,0,0,1121,224,133
2018/03/06 19:43:29 output_http:0,0,0,1389,277,113
2018/03/06 19:43:34 output_http:0,0,0,1487,297,109
2018/03/06 19:43:39 output_http:0,0,0,1329,265,105
2018/03/06 19:43:44 output_http:0,0,1,1166,233,106
2018/03/06 19:43:49 output_http:0,0,0,850,170,98
2018/03/06 19:43:54 output_http:0,0,0,1308,261,98
2018/03/06 19:43:59 output_http:0,0,0,1235,247,94
2018/03/06 19:44:04 output_http:0,0,0,907,181,90
2018/03/06 19:44:09 output_http:0,0,0,1271,254,88
```

**Comment by buger** [comment]
So it actually replayed on higher speed, right?

**Comment by nderzhak** [comment]
Yes. DEV will obey |speed% , but only without: --output-file= , which we need sometimes to collects more metrics.

**Comment by nikolaiderzhak** [comment]
Hi, Leonid, Is there is any way to disable DNS resolve so frequently ?

I am getting errors like these:

```
Connection error: dial tcp: lookup api-load-test.cloud.appctest.com on 172.100.0.2:53: dial udp 172.100.0.2:53: i/o timeout
```

Seems AWS default DNS servers are not happy with massive benchmark we conduct :)

So I am thinking on solution now.

LIke /etc/hosts and one benchmark client node per target load balancer. Does it seem as good solution to you ?

**Comment by nikolaiderzhak** [comment]
I figured out something like this. As DNS timeouts give me dips in NewRelic RPM chart/affects performance.

```
./$CMD \
    -http-set-header "Host: $ENDPOINT" \
    --input-file "${INPUT_FILE}|3200%" \
    --output-http="http://$IP" \
    --input-file-loop \
    --stats --output-http-stats > test-$IDX.out 2> test-$IDX.err
```
