### ISSUE TITLE
GoReply filtering out PUBLIC VIP Ethernet adapters/devices

### ISSUE THREAD

**Issue by cherimckeown** [buger/goreplay#557]
There is an old/closed thread about VIP issues.
I am having the same/similar issue on a Windows Server 2012 running version 0.16.1 of GoReplay.

My incoming HTTP traffic is being routed to a virtual IP because my messaging system is mirrored with active and passive members hosted on different IPs. Unfortunately, GoReply does not see the traffic coming across the VIP. WireShark of course does, so there must be a way :-)

When I run: **goreplay input-raw :5556 -output-stdout**

I see it open the first device for the BACKUP Ethernet adapter and the first device for the PUBLIC Ethernet adapter.  The VIP with the message traffic is also listed in the PUBLIC Ethernet adapters, but it seems that GoReplay is filtering this device out.

Is there a way I can configure to not filter in this fashion?

Use the physical address (so picking up all of the Public IP addresses) or
or privide a specific IP address with the port?

Thanks,
Cheri

**Comment by cherimckeown** [comment]
I tried: **goreplay -output-stdout -input-raw-bpf-filter 'ip dst host 10.130.218.172'**
172 being my VIP, but got error: _Required at least 1 input and 1 output_

**Comment by cherimckeown** [comment]
Actually the example bpf filter example fails with the same error.
So do I need to install something else to make bpf filtering work?

**Comment by buger** [comment]
Try smth like this: `goreplay --input-raw -input-raw-bpf-filter 'port 5556' -output-stdout`

**Comment by cherimckeown** [comment]
Thanks for the nudged in the right direction, following is what finally worked:
**goreplay -output-stdout -input-raw :5556 -input-raw-bpf-filter "host 10.130.218.172"**

Needed to use double-quotes on bpf filter and also put the port on the plan raw input :-)

Can you tell me, it seems like using "--" before a option or a single "-" before an option have the same effect.  Is this true?  Your example above uses both, just wondering the meaning of this?

**Comment by buger** [comment]
In my case it was just typo, but looks like go `flag` package understand it in both cases :)
