### ISSUE TITLE
Goreplay replay rate very slow when replay input file contains multiple requests. 

### ISSUE THREAD

**Issue by jacoblukose** [buger/goreplay#559]
`./tr-goreplay --input-file test_multiple_req_0.gor --output-http 127.0.0.1:8000 --input-file-loop --exit-after 10s | wc -l`  
[multiple_req.txt](https://github.com/buger/goreplay/files/1796520/multiple_req.txt)

Output:
> 2018/03/09 10:31:43 Running gor for a duration of 10s
2018/03/09 10:31:53 Stopping gor after 10s
6

`./tr-goreplay --input-file test_single_req_0.gor --output-http 127.0.0.1:8000 --input-file-loop --exit-after 10s | wc -l` 
[single_req.txt](https://github.com/buger/goreplay/files/1796523/single_req.txt)

Output:
> 2018/03/09 10:31:43 Running gor for a duration of 10s
2018/03/09 10:31:53 Stopping gor after 10s
3550

Is this behaviour normal  ? Should I add any other options for speeding up ? 
Please explain .

**Comment by buger** [comment]
I'm not sure you count the right number here `wc -l`.
Inside multipl_req file, the difference between 2 requests is approximately 4 seconds: (1520577134652322000 - 1520577130039671000). So it replays 1 request, waits for 4 seconds, replays the second one, and repeat. 

In case of a single request, it does not wait at all, and without any delays just sends same requests again and again. 

You can speed up replay like this: --input-file "test_multiple_req_0.gor|200%",  which will replay it 2x faster. But I'll be frank, both of this cases are kind of edge cases, especially last one. Record at least 10 requests or better hundreds, to make load simulation more realistic. 

Hope it makes sense!

**Comment by jacoblukose** [comment]
got it . Thanks!
