### ISSUE TITLE
--output-http-track-response  not returning response for replayed requests. 

### ISSUE THREAD

**Issue by jacoblukose** [buger/goreplay#577]
Hi here, 

I am trying to capture responses of the replayed requests , but not able to get back responses all time .
On replaying a request, the program code is getting stuck on the net.conn.Read() call. 
https://github.com/buger/goreplay/blob/master/http_client.go#L199 .
  
I see the response in tcpdump output, but not able to obtain the same from within the code using net.conn.Read()

**Comment by vitalyu** [comment]
We have the same problem. No replayed response (3) in middleware stdin

**Comment by buger** [comment]
Oh, 11 thumbs up :)
Frankly better use comments since I do not get notifications about "reactions". Helps to prioritize tasks.

Can you pls try these binaries based on latest master and check if it works for you, and if so, I'll do patch release this week.

[gor_DEV-1526466285_x64.tar.gz](https://github.com/buger/goreplay/files/2008659/gor_DEV-1526466285_x64.tar.gz) 
[gor_DEV-1526466310_mac.tar.gz](https://github.com/buger/goreplay/files/2008658/gor_DEV-1526466310_mac.tar.gz)

**Comment by jacoblukose** [comment]
I tried the gor_DEV-1526466285_x64.tar.gz , But still its not working. Response is coming in tcpdump.

**Comment by buger** [comment]
@jacoblukose any change you can record tcpdump pcap file for me and attach here?

Thank you.

**Comment by jacoblukose** [comment]
OS:

> Red Hat Enterprise Linux Server release 6.8 (Santiago)
> x86_64 GNU/Linux

**Command:** 
`sudo ./gor --input-file sample.gor  --output-http 127.0.0.1:8080 --debug --verbose --output-http-track-response`

Can I get your mailid for sending tcpdump data ?

**Comment by buger** [comment]
Thank you.

Pls send it here: support@goreplay.org

**Comment by buger** [comment]
Can you also confirm that you also do not see the replayed response when using `--output-stdout`, thank you

**Comment by jacoblukose** [comment]
So shall I just  add --output-stdout to the above command I posted and run  ?

**Comment by buger** [comment]
You can try, yes. It is totally ok to use multiple outputs.

**Comment by jacoblukose** [comment]
Still not seeing the response every time.

**Comment by out001a** [comment]
I have the same problem.

**Comment by sol1000** [comment]
I have the same problem.
No response data captured. Only see the requests.
sudo ./gor --input-raw :8000 --output-stdout --output-http-track-response

**Comment by buger** [comment]
Can you pls try this version:
https://www.dropbox.com/s/vdx96jooejsd5nf/gor_DEV-1543578204_x64.tar.gz?dl=1
https://www.dropbox.com/s/d682f1g9u4yjqcl/gor_DEV-1543578245_mac.tar.gz?dl=1

**Comment by sol1000** [comment]
![screen shot 2018-12-04 at 3 39 58 pm](https://user-images.githubusercontent.com/2367512/49471430-e0212580-f7da-11e8-91e1-8fcac6ab8150.png)

Sorry buger. It doesn't work for me. 
I was running "python -m SimpleHTTPServer 8000"
and ran the version you sent with {{--output-http-track-response}} option
"sudo gor --input-raw :8000 --output-stdout --output-http-track-response"
after then I hit the http server with "curl http://localhost:8000"
Gor shows request, but not the response.

**Comment by nziebart** [comment]
can confirm the same issue as @sol1000 

I tried both the latest release (v0.16.1) and the dev version dropbox link above, on both mac os and ubuntu. the following command does not print http responses:

`sudo ./goreplay --output-http-track-response --input-raw-track-response --input-raw :5462 --output-stdout`

**Comment by tautelis** [comment]
test

**Comment by tautelis** [comment]
Any update on this one?

I am running into similar issue while running the following command:
```
./gor --input-raw :80 -input-raw-track-response --output-stdout --middleware "./GorMiddleware.php --listen --debug"
```

When loading single website page with its resources I noticed that only 3 of 13 requests have their response captured.

https://pasteboard.co/Ii7Fkkp.png

Maybe this will help on finding what is in common among captured and not captured responses.

**Comment by imkaka** [comment]
Is this issue resolved, as I am also getting only 1,2 (Request and Original Response ) but not 3(Replayed Response).

I need to replicate the [token thing](https://github.com/buger/goreplay/wiki/Middleware#advanced-example) which is also in documentation, but in ```pyhton3```.

**Comment by NHP95** [comment]
Hey guys, I ran into the same issue. I haven't figured out a way to log the Replayed Response yet. Below is my command and the middleware file was taken from the example folder.

`./gor --input-raw-track-response --output-http-debug --output-http-track-response -verbose --input-file login_hrm_0.log --output-http "http://localhost:5000" --middleware "./sample.py"`

**Comment by buger** [comment]
@NHP95 I believe the way you call middleware. In GoReplay middleware is an executable process. So it should be like: `--middleware "python ./sample.py"`

**Comment by t880216t** [comment]
Hey guys, I ran into the same issue. Any update on this one?

**Comment by topwqp** [comment]
Hey guys, I ran into the same issue.
my version is 1.0.0

`sudo ./gor --output-http-track-response --input-raw-track-response --input-raw :9901 --output-stdout`

my server language is java, if invoke http request , response return  string type , request  and response   return is ok
![image](https://user-images.githubusercontent.com/3363807/70885670-7efa7780-2014-11ea-951c-8a5605711ca7.png)


my sever java code is 
` @RequestMapping(value = "/testString", method = RequestMethod.POST)
    public String testString() {
        return "test";
    }`


above code is capture request and reponse , everthing is ok

but  if i modify java code return  object  like this 
`@RequestMapping(value = "/testObject", method = RequestMethod.POST)
    public MockDTO testObject() {
        MockDTO mockDTO = new MockDTO();
        mockDTO.setId(1);
        mockDTO.setName("wqp");
        mockDTO.setDesc("desc");
        mockDTO.setScope(BigDecimal.valueOf(5.43d));
        return mockDTO;
    }`
no response output   this is my output
![image](https://user-images.githubusercontent.com/3363807/70885606-49ee2500-2014-11ea-9911-b5e9aee75c16.png)

I don't know why ?  someone can help me?

**Comment by lms98052** [comment]
my problem is some time replay response body is missing
my env  :  gor v1.2.0 
command line : sudo ./gor --input-raw :38080 --input-raw-track-response --output-http-track-response  --output-file="all_requests.txt" --output-http "100.95.133.126:40096" --http-allow-method "GET"  --http-disallow-url ".*/oauth/api/v1/ping" --http-allow-method ".*/oauth/api/.*" --input-raw-buffer-size 100485760 --output-stdout

**Comment by buger** [comment]
I think `--output-http-compatibility-mode` will solve the issue (it will use default Go network stack) and I'm thinking to making it default option.
