### ISSUE TITLE
Index out of range panic in goreplay/proto/proto.go:95

### ISSUE THREAD

**Issue by defasun** [buger/goreplay#578]
```panic: runtime error: index out of range
goroutine 133 [running]:
panic(0xa58cc0, 0xc82000e0a0)
        /usr/local/go/src/runtime/panic.go:481 +0x3e6
github.com/buger/goreplay/proto.headerIndex(0xc821e9603f, 0x7aa, 0x4fffc1, 0xc8212c9580, 0xd, 0xd, 0x3)
        /go/src/github.com/buger/goreplay/proto/proto.go:95 +0x24e
github.com/buger/goreplay/proto.header(0xc821e9603f, 0x7aa, 0x4fffc1, 0xc8212c9580, 0xd, 0xd, 0x0, 0x0, 0x0, 0xc, ...)
        /go/src/github.com/buger/goreplay/proto/proto.go:127 +0x9a
github.com/buger/goreplay/proto.SetHeader(0xc821e9603f, 0x7aa, 0x4fffc1, 0xc8212c9580, 0xd, 0xd, 0xc8212c9560, 0xc, 0xc, 0x0, ...)
        /go/src/github.com/buger/goreplay/proto/proto.go:300 +0x7d
main.(*HTTPModifier).Rewrite(0xc8223b2000, 0xc821e9603f, 0x7aa, 0x4fffc1, 0x0, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/http_modifier.go:57 +0x406
main.CopyMulty(0x7fb4744b90f8, 0xc8200884e0, 0xc82138aef0, 0x1, 0x1, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/emitter.go:80 +0x6d3
created by main.Start
        /go/src/github.com/buger/goreplay/emitter.go:28 +0x4b2```

**Comment by defasun** [comment]
inside of the nested for loop, apparently for the index increase (i++), apparently we are missing an index range check for the index i. 

we need  to have the following patch:
diff --git a/proto/proto.go b/proto/proto.go
index 2722527..5aa63a4 100644
--- a/proto/proto.go
+++ b/proto/proto.go
@@ -93,6 +93,10 @@ func headerIndex(payload []byte, name []byte) int {
                                                return i - len(name)
                                        }

+                                       if i == len(payload) {
+                                               return -1
+                                       }
+
                                        if payload[i] != name[j] {
                                                break
                                        }

**Comment by slimus** [comment]
@defasun is it fixed after your PR? May we close this issue?

**Comment by defasun** [comment]
Yes, it is fixed. We can close it.

Thanks,
Defa
