### ISSUE TITLE
output_http traffic will double when two ethernet card have the same ip

### ISSUE THREAD

**Issue by yangjf1024** [buger/goreplay#582]
In this case, I have two interface with the  same ip ，and when capture traffic on this ip, th output flow will double.

whether it should be add a filter in findPacapDevices  function?

**Comment by buger** [comment]
Hi! I believe in this edge case you should be able to use `--input-raw-bpf-filter` and maybe specify the exact ID of your interface. You can find list of available bpf expressions here http://biot.com/capstats/bpf.html

An example can be: `--input-raw-bpf-filter "ifname <interface-id> and port 8080"`

**Comment by yangjf1024** [comment]
Thanks for help!
