### ISSUE TITLE
when using Rate limiting, CPU's usage is 100% ( even no incoming traffic)

### ISSUE THREAD

**Issue by kuaikuai** [buger/goreplay#594]
when using Rate limiting, CPU's usage is 100% ( even no incoming traffic)

./goreplay --input-raw :80 --output-tcp "10.18.210.76:28020|1%"

**Comment by chainhelen** [comment]
En, I get your point.
`/goreplay --input-raw :80 --output-tcp "10.18.210.76:28020"` is ok, 
but `/goreplay --input-raw :80 --output-tcp "10.18.210.76:28020|1%"` cause the problem.

I review the source code and find the reason.
When using `rate limiting`,  `Limiter` will wrap the `TCPOutput`.
And `TCPOutput` has no func named `Read`, but `Limiter` has.   
So the [Limiter.Read](https://github.com/buger/goreplay/blob/c5d1112e7ab3147fd985e9cafc855d75bf585755/limiter.go#L88) always `return 0, nil`, and [emitter.CopyMulty](https://github.com/buger/goreplay/blob/29139e9edaa5b0da69a4d07d1e955de62aea0e8e/emitter.go#L59) trapped in a dead circle.  

![image](https://user-images.githubusercontent.com/7046329/44192573-8aa90600-a162-11e8-9024-9e34997a77b0.png)  

@kuaikuai 
In my options, `tcp` is not an application layer protocol, even `rate limiting` is meaningless. 

@buger 
In my opinion
1. Disable the func `rate` of `TCPOutput` and throw some error
2. Finish `TCPOutput`.read (en, or disabled ?)  

En, I can add a new pr if you support my opinion.

**Comment by kuaikuai** [comment]
Disable the func rate of TCPOutput and throw some error
