### ISSUE TITLE
Containers fail to start because of Openstack repository

### ISSUE THREAD

**Issue by aneutron** [buger/goreplay#599]
I downloaded the latest release (0.16.1), and ran it as root (Ubuntu 18.10), but I couldn't see the port on netstat. 

So I checked docker and the containers exited. `docker start -a` on one of them fails with `cloud-archive for Pike only supported on xenial`.

**Comment by chainhelen** [comment]
@aneutron Gor just capture the package on specify port, but not occupy this port.
