### ISSUE TITLE
Broken link formatting in the wiki

### ISSUE THREAD

**Issue by pepasflo** [buger/goreplay#605]
Thanks so much for creating goreplay!  🎉

I noticed a few of the links are broken in the wiki, e.g. on https://github.com/buger/goreplay/wiki/The-Basics

<img width="785" alt="screen shot 2018-09-18 at 4 52 30 pm" src="https://user-images.githubusercontent.com/25310741/45718673-80b06380-bb63-11e8-802c-24f34d71d854.png">

I'd guess the spaces just need to be replaced with %20.

**Comment by slimus** [comment]
@pepasflo Thank for your issue. I fix it. Please check
