### ISSUE TITLE
PANIC: pkg: runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by bjstrange** [buger/goreplay#622]
Seeing a lot of these (hundreds) during a replay. The goroutine # changes. What else is needed to look into this?

goreplay continues to run but they scrolling by almost constantly. Version is 0.16.1.

```
2018/11/16 15:21:48 PANIC: pkg: runtime error: slice bounds out of range goroutine 106 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc82116dc78, 0xc82116dc90)
        /go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc8200101a0)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
main.(*HTTPClient).Send(0xc821c64680, 0xc82335003f, 0x848, 0x84e, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/http_client.go:304 +0x20bf
main.(*HTTPOutput).sendRequest(0xc82001a550, 0xc821c64680, 0xc823350000, 0x88d, 0x88d)
        /go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc82001a550)
        /go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
        /go/src/github.com/buger/goreplay/output_http.go:99 +0x85

2018/11/16 15:29:40 PANIC: pkg: runtime error: slice bounds out of range goroutine 6 [running]:
runtime/debug.Stack(0x0, 0x0, 0x0)
        /usr/local/go/src/runtime/debug/stack.go:24 +0x80
main.(*HTTPClient).Send.func1(0xc8221d7c78, 0xc8221d7c90)
        /go/src/github.com/buger/goreplay/http_client.go:147 +0x52d
panic(0xa58cc0, 0xc820010190)
        /usr/local/go/src/runtime/panic.go:443 +0x4e9
main.(*HTTPClient).Send(0xc822174280, 0xc821f2163f, 0x87b, 0x885, 0x0, 0x0, 0x0, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/http_client.go:304 +0x20bf
main.(*HTTPOutput).sendRequest(0xc820088500, 0xc822174280, 0xc821f21600, 0x8c4, 0x8c4)
        /go/src/github.com/buger/goreplay/output_http.go:205 +0x2b6
main.(*HTTPOutput).startWorker(0xc820088500)
        /go/src/github.com/buger/goreplay/output_http.go:125 +0x1c7
created by main.(*HTTPOutput).workerMaster
        /go/src/github.com/buger/goreplay/output_http.go:99 +0x85

```

**Comment by jkerr5** [comment]
I am seeing something similar with version 1.2.0 as well but the process exits when these happen for me.
```
2020/10/16 10:06:20 [PPID 48034 and PID 48035] Version:1.2.0
panic: runtime error: slice bounds out of range [:-5697042533507396785]

goroutine 5 [running]:
github.com/buger/goreplay/proto.CheckChunked(0xc000fd41d2, 0xd30, 0x112e, 0xc00006bc11)
        /go/src/github.com/buger/goreplay/proto/proto.go:435 +0x310
github.com/buger/goreplay/proto.HasFullPayload(0xc000fd4000, 0xf02, 0x1300, 0xc000fd4000)
        /go/src/github.com/buger/goreplay/proto/proto.go:455 +0x17b
main.endHint(0xc000d06820, 0xc000c01542)
        /go/src/github.com/buger/goreplay/input_raw.go:207 +0x41
github.com/buger/goreplay/tcp.(*MessagePool).addPacket(0xc0002f6940, 0xc000d06820, 0xc000c0ad70)
        /go/src/github.com/buger/goreplay/tcp/tcp_message.go:217 +0x1ee
github.com/buger/goreplay/tcp.(*MessagePool).Handler(0xc0002f6940, 0x1124fc0, 0xc0001b4c60)
        /go/src/github.com/buger/goreplay/tcp/tcp_message.go:171 +0xa84
github.com/buger/goreplay/capture.(*Listener).Listen(0xc000299130, 0x1118860, 0xc0002f6980, 0xc00006f700, 0x0, 0x0)
        /go/src/github.com/buger/goreplay/capture/capture.go:163 +0x163
github.com/buger/goreplay/capture.(*Listener).ListenBackground.func1(0xc00008cd20, 0xc000299130, 0x1118860, 0xc0002f6980, 0xc00006f700)
        /go/src/github.com/buger/goreplay/capture/capture.go:173 +0x7b
created by github.com/buger/goreplay/capture.(*Listener).ListenBackground
        /go/src/github.com/buger/goreplay/capture/capture.go:171 +0x84
```

**Comment by urbanishimwe** [comment]
This should be reported as a separate issue! the issue mentioned in the first comment was fixed.

**Comment by ilovers** [comment]
> I am seeing something similar with version 1.2.0 as well but the process exits when these happen for me.
> 
> ```
> 2020/10/16 10:06:20 [PPID 48034 and PID 48035] Version:1.2.0
> panic: runtime error: slice bounds out of range [:-5697042533507396785]
> 
> goroutine 5 [running]:
> github.com/buger/goreplay/proto.CheckChunked(0xc000fd41d2, 0xd30, 0x112e, 0xc00006bc11)
>         /go/src/github.com/buger/goreplay/proto/proto.go:435 +0x310
> github.com/buger/goreplay/proto.HasFullPayload(0xc000fd4000, 0xf02, 0x1300, 0xc000fd4000)
>         /go/src/github.com/buger/goreplay/proto/proto.go:455 +0x17b
> main.endHint(0xc000d06820, 0xc000c01542)
>         /go/src/github.com/buger/goreplay/input_raw.go:207 +0x41
> github.com/buger/goreplay/tcp.(*MessagePool).addPacket(0xc0002f6940, 0xc000d06820, 0xc000c0ad70)
>         /go/src/github.com/buger/goreplay/tcp/tcp_message.go:217 +0x1ee
> github.com/buger/goreplay/tcp.(*MessagePool).Handler(0xc0002f6940, 0x1124fc0, 0xc0001b4c60)
>         /go/src/github.com/buger/goreplay/tcp/tcp_message.go:171 +0xa84
> github.com/buger/goreplay/capture.(*Listener).Listen(0xc000299130, 0x1118860, 0xc0002f6980, 0xc00006f700, 0x0, 0x0)
>         /go/src/github.com/buger/goreplay/capture/capture.go:163 +0x163
> github.com/buger/goreplay/capture.(*Listener).ListenBackground.func1(0xc00008cd20, 0xc000299130, 0x1118860, 0xc0002f6980, 0xc00006f700)
>         /go/src/github.com/buger/goreplay/capture/capture.go:173 +0x7b
> created by github.com/buger/goreplay/capture.(*Listener).ListenBackground
>         /go/src/github.com/buger/goreplay/capture/capture.go:171 +0x84
> ```

Did you resolve this? I have the same issue.
