### ISSUE TITLE
--input-file pattern with s3 doesn't work

### ISSUE THREAD

**Issue by sshaunak9** [buger/goreplay#646]
we are using goreplay pro to replay goreplay logs from a s3 bucket like `gor --input-file s3://{some-bucket}/{some-folder}/2019_01_16_11_* --output-http http://example.com`

We are using `*` pattern to match log files with names starting with a prefix.
The files in the `s3://{some-bucket}/{some-folder}` are generated using goreplay pro with names like `%Y_%m_%d_%H_%M_%S.log`

However, goreplay pro fails to replay the logs with a message like 
`2019/01/16 19:41:54 No files match pattern:  s3://{some-bucket}/{some-folder}/2019_01_16_11_*`

Specifying the whole path name works fine like `gor --input-file s3://{some-bucket}/{some-folder}/2019_01_16_11_01_0.log --output-http http://example.com`.

Anything we might be doing wrong ??

**Comment by buger** [comment]
S3 file system do not support full filter patterns, instead, you should specify prefixes. In your case it should be just `s3://{some-bucket}/{some-folder}/2019_01_16_11_` without `*`

Clarified this part in S3 docs https://github.com/buger/goreplay/wiki/%5BPRO%5D-Using-S3-for-storing-and-replaying-traffic
