### ISSUE TITLE
panic with --output-http-elasticsearch version1.0.0

### ISSUE THREAD

**Issue by realhac** [buger/goreplay#662]
version1.0.0
2019/04/03 08:41:54 output_http:latest,mean,max,count,count/second,gcount
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x30 pc=0x830d1e]

goroutine 1 [running]:
main.parseURI(0x7ffcd3a3e6b4, 0x1c, 0xc42006e5a0, 0x60, 0x41247c, 0xc42006c370)
	/go/src/github.com/buger/goreplay/elasticsearch.go:73 +0x5e
main.(*ESPlugin).Init(0xc42008e7d0, 0x7ffcd3a3e6b4, 0x1c)
	/go/src/github.com/buger/goreplay/elasticsearch.go:88 +0x50
main.NewHTTPOutput(0x7ffcd3a3e670, 0x16, 0xff5610, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/output_http.go:94 +0x1ef
reflect.Value.call(0x9900a0, 0xa8fd58, 0x13, 0xa56d42, 0x4, 0xc4201aa060, 0x2, 0x2, 0x9736c0, 0x9736c0, ...)
	/usr/local/go/src/reflect/value.go:447 +0x969
reflect.Value.Call(0x9900a0, 0xa8fd58, 0x13, 0xc4201aa060, 0x2, 0x2, 0x1, 0x2, 0x411149)
	/usr/local/go/src/reflect/value.go:308 +0xa4
main.registerPlugin(0x9900a0, 0xa8fd58, 0xc420067d18, 0x2, 0x2)
	/go/src/github.com/buger/goreplay/plugins.go:56 +0x229
main.InitPlugins()
	/go/src/github.com/buger/goreplay/plugins.go:142 +0xa4c
main.main()
	/go/src/github.com/buger/goreplay/gor.go:64 +0x64f

**Comment by slimus** [comment]
Fixed https://github.com/buger/goreplay/pull/752/files

**Comment by slimus** [comment]
Merged to master. Please pull master branch and check it again. If error will throw again , please create new issue with details.
