### ISSUE TITLE
400% cpu usage on Mac OS

### ISSUE THREAD

**Issue by jbub** [buger/goreplay#676]
After running `sudo ./goreplay --input-raw :9000 --output-stdout` the CPU pegs at 400%. The replaying somehow works but the PC is unusable.

```
goreplay: both precompiled 1.0.0 and the one compiled myself
go: go1.12.5 darwin/amd64
os: Mac OS X10.14.5
```

**Comment by slimus** [comment]
Hi @jbub ! I tried 1.0.0 and master version and it is ok. Can you please test it again? 
Also can you please capture only en0 interface, like this: `sudo ./gor --input-raw en0:9000 --output-stdout`

**Comment by jbub** [comment]
Related #730

**Comment by slimus** [comment]
yep, got it. 
move discussion to #730
