### ISSUE TITLE
question - how to compare results from 2 servers

### ISSUE THREAD

**Issue by avnerbarr** [buger/goreplay#688]
I am able to mirror traffic from one server to another or record traffic from one server and reply on another.
I'm not clear as to the mechanism in comparing the results of the 2 servers.

I saw this https://github.com/buger/goreplay/issues/177 but didn't see if there is a way to resolve it

**Comment by urbanishimwe** [comment]
I guess the current possible way is to write middleware that analyzes responses based on their ID(Ideally those responses will have the same ID as the request).
