### ISSUE TITLE
Multiple listen ports

### ISSUE THREAD

**Issue by DagW** [buger/goreplay#699]
Hello! I want to capture traffic on more than one port - i've seen some examples but cant get it to work. Is this supported?

``` 
--input-raw :80 --input-raw :81 --input-raw :82
 ```
It seems goreplay only listens on the last specified port.

**Comment by DagW** [comment]
And a comment i found that seems to use this;

https://github.com/buger/goreplay/issues/85#issuecomment-38050806

**Comment by DagW** [comment]
Also referenced here;
https://github.com/buger/goreplay/issues/298
Am I missing something?

**Comment by pourer** [comment]
[图片]
#700

**Comment by pourer** [comment]
![image](https://user-images.githubusercontent.com/5706696/67301771-7b6dd700-f522-11e9-9ef6-f2aea2654815.png)
Please check PR: #700

**Comment by buger** [comment]
Should be fixed now, thank you for the contribution!
