### ISSUE TITLE
input-raw: error while parsing addressaddress -: missing port in address

### ISSUE THREAD

**Issue by HeartIsBeat** [buger/goreplay#703]
![image](https://user-images.githubusercontent.com/20472976/68101955-5eb2a580-ff0b-11e9-83d5-9d0483c894fc.png)
tcpdump -i eth0 -s 0 -w -  | ./gor  --input-raw - --output-file "test.gor"  -exit-after 10s --input-raw-engine  pcap_file

When gor version is 0.16.1, this is ok.
But when gor version is 1.0.0，this is not ok.
![image](https://user-images.githubusercontent.com/20472976/68101974-7d18a100-ff0b-11e9-98f9-c6aa9a5df845.png)
What's wrong with me?

**Comment by relunctance** [comment]
+1

**Comment by slimus** [comment]
fixed error message via #745
