### ISSUE TITLE
URL query doesn't end up in the output http

### ISSUE THREAD

**Issue by emailtovamos** [buger/goreplay#704]
My Go-replay command is:
`./gor --input-raw=:8080                                                      
     --output-http="https://my-custom-domain.net|10%"`

The issue is the query of input doesn’t seem to get added to my output http address.
e.g. if a request has query of “/q=?x=1&y=2” , I expect a GET request to be made to https://my-custom-domain.net/q=?x=1&y=2.
But instead of this, a GET request is made simply to https://my-custom-domain.net/. I know this by looking at the logs.

What could I be doing wrong?

**Comment by slimus** [comment]
Hi @emailtovamos! Can you please test it with v1.0.0 or build `gor` from master? I tried with local server and it works correctly:
request:
`127.0.0.1 - - [03/Jun/2020 15:11:40] "GET /?q=1&v=1 HTTP/1.1" 200 -`
`127.0.0.1 - - [03/Jun/2020 15:11:41] "GET /?q=1&v=1 HTTP/1.1" 200 -`
`127.0.0.1 - - [03/Jun/2020 15:11:41] "GET /?q=1&v=1 HTTP/1.1" 200 -`
response:
`127.0.0.1 - - [03/Jun/2020 15:11:38] "GET /?q=1&v=1 HTTP/1.1" 200 -`
`127.0.0.1 - - [03/Jun/2020 15:11:42] "GET /?q=1&v=1 HTTP/1.1" 200 -`

Also if you  can reproduce, will be better if you create example application and show it. Thanks!

**Comment by urbanishimwe** [comment]
since there is no information so far, I'll mark this as fixed!
