### ISSUE TITLE
No output when using netcat (Debian)

### ISSUE THREAD

**Issue by b3nky** [buger/goreplay#712]
Hi,

Can someone explain me why when I use netcat there is no output, at first I thought that I messed up something with install/compile of goreplay.
Then I tried "curl http://localhost:8000" and goreplay show the request. Netcat was used like this:
"nc localhost 8000", then "GET / HTTP/1.1" "Host: localhost"

**Comment by urbanishimwe** [comment]
@b3nky the netcap request you sent (`"GET / HTTP/1.1 Host: localhost"`) has an invalid HTTP request format and Goreplay may dump that request due to invalidity and netcat sends data as is.
I'm going to close this issue feel free to re-open if there is some misunderstanding.
