### ISSUE TITLE
Pro Version - How to change HTTP Host in Middleware based on incoming host

### ISSUE THREAD

**Issue by pran-m** [buger/goreplay#715]
We have various sub-domains like - dev.user.example.com/v1/user , dev.org.example.com/v1/org

We want to replay this to - stage.user.example.com/v1/user, stage.org.example.com/v1/org

All subdomain traffic are captured in a single GOR file in S3.  

1) We are using Node.JS middleware to modify payload during replay.  I'm not seeing an option to change host in - https://github.com/buger/goreplay/tree/master/middleware . 

How to modify the replay host in middleware dynamically based on incoming host?

2) I 'm accessing incoming host like this -  gor.httpHeader(req.http, "host") -  But it returns undefined.   Host is present in the header in the GOR File (as seen below)

1 7752434f6cff6bea6aff7295cd9a0cff507a073c 1574781960974507755
GET /api HTTP/1.1
host: localhost:3000
Connection: keep-alive

**Comment by dullyouth** [comment]
I believe you can use the rewrite-header function to rewrite them on the fly for what you're trying to accomplish, without the need for middleware.

```
-http-rewrite-header value
Rewrite the request header based on a mapping:
gor --input-raw :8080 --output-http staging.com --http-rewrite-header Host: (.*).example.com,$1.beta.example.com```
