### ISSUE TITLE
--output-http-track-response not returning response

### ISSUE THREAD

**Issue by topwqp** [buger/goreplay#718]
Hey guys
my version is 1.0.0

`sudo ./gor --output-http-track-response --input-raw-track-response --input-raw :9901 --output-stdout`

my server language is java, if invoke http request , response return string type , request and response return is ok

![image](https://user-images.githubusercontent.com/3363807/70970861-79676500-20da-11ea-86f0-8e2c1347384a.png)

my sever java code is

```java
@RequestMapping(value = "/testString", method = RequestMethod.POST) 
public String testString() { 
return "test"; 
}
```
above code is capture request and reponse , everthing is ok

but if i modify java code return object like this

```java
 @RequestMapping(value = "/testObject", method = RequestMethod.POST)
    public MockDTO testObject() {
        MockDTO mockDTO = new MockDTO();
        mockDTO.setId(1);
        mockDTO.setName("wqp");
        mockDTO.setDesc("desc");
        mockDTO.setScope(BigDecimal.valueOf(5.43d));
        return mockDTO;
    }
```
no response output this is my output

![image](https://user-images.githubusercontent.com/3363807/70971016-e7139100-20da-11ea-9f09-cff4fe52b3de.png)

this response  is not output

I don't know why ? someone can help me?

when i save request and replay ,  command is this 
```shell
./gor --input-file request_json_0.gor --output-http="http://localhost:9902" --output-file test.gor  --output-http-track-response
```

the response is ok , output like this 
![image](https://user-images.githubusercontent.com/3363807/70971195-5c7f6180-20db-11ea-98d8-44339d66a392.png)

I want to  direct get request and response , not replay

why i cant direct get response ,    
Transfer-Encoding: chunked   can effect the response not output ?

**Comment by wumangxing1990** [comment]
i have the same issue, have you resolved this problem ?

**Comment by slimus** [comment]
@topwqp @wumangxing1990 hi! Can you please test gor from master branch?
I tried with php server (json, plain test, chunked transfer) and can't reproduce this issue.

**Comment by urbanishimwe** [comment]
related to #743
