### ISSUE TITLE
goreplay drops big package

### ISSUE THREAD

**Issue by jackstraw-dev** [buger/goreplay#719]
Goreply drops big package which body size is ~4k.

 I run goreply using "sudo ./gor --input-raw :8080 --output-http mjq.jd.local --http-set-param forcebot=1 --input-raw-buffer-size 500485760 -copy-buffer-size 500485760 2>&1 &"

the log has below text:

   2019/09/30 07:55:10 PANIC: pkg: runtime error: slice bounds out of range /gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:199 (0x5969ee)
/goroot/src/runtime/asm_amd64.s:401 (0x454395)
/goroot/src/runtime/panic.go:387 (0x42ba78)
/goroot/src/runtime/panic.go:18 (0x42ac5e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:237 (0x59425e)
/gopath/src/github.com/buger/gor/raw_socket_listener/listener.go:100 (0x592b41)
/goroot/src/runtime/asm_amd64.s:2232 (0x4564b1)

**Comment by shen123shen** [comment]
How can I fix this?

**Comment by baodingfengyun** [comment]
try v0.16.1

**Comment by restebanez** [comment]
I've had the same issue, working fine with `v0.16.1` but starting from `1.x` only a fraction of the requests were captured. My traffic is mainly composed of very large JSON blobs (body size of up to 20MB). After trying many options I found out that `--input-raw-engine raw_socket` generated the same filesize as  `v0.16.1`, here it's the full command that works for me:

`./gor --input-raw :80 --input-raw-engine raw_socket --copy-buffer-size 500485760 --output-file capture-%Y-%m-%d-%H --output-file-append --verbose`
