### ISSUE TITLE
Cannot replay request to second port on windows.

### ISSUE THREAD

**Issue by amosnothing** [buger/goreplay#723]
G:\ChocolateyInstall\Cmder>gor version
Version:
2019/12/30 16:46:55 Required at least 1 input and 1 output

G:\ChocolateyInstall\Cmder>go version
go version go1.13.5 windows/amd64

Steps:
1. set up gor file-server :8000
2. set up gor file-server :8001
3. gor --input-raw :8000 --output-http :8001
4. curl localhost:8000

Result: the port 8001 has not replay request, please see the picture below.
![gor](https://user-images.githubusercontent.com/24653016/71574714-eb04d180-2b24-11ea-9b71-dcdb5b31f111.gif)

**Comment by urbanishimwe** [comment]
@amosnothing what goreplay version weere you running? meanwhile, try to run as an administrator to see if the issue will be reproduced!
another workaround is to switch between different engines https://github.com/buger/goreplay/wiki/Capturing-and-replaying-traffic#traffic-interception-engine

**Comment by urbanishimwe** [comment]
If you run goreplay as sudo does this issue reproduce?
