### ISSUE TITLE
bug: listening to interface without network address

### ISSUE THREAD

**Issue by shuvigoss** [buger/goreplay#727]
2020/01/08 14:10:54 SIOCGIFMEDIA on llw0 failed: Device power is off
Exiting.

my network config is 
![image](https://user-images.githubusercontent.com/3062921/71954952-d362d280-3221-11ea-9adb-c0ccb240a9db.png)

why use llw0 ?

**Comment by porjo** [comment]
Try specifying the input interface e.g. `gor --input-raw eth0:80 --output-stdout`

**Comment by shuvigoss** [comment]
> Try specifying the input interface e.g. `gor --input-raw eth0:80 --output-stdout`

![image](https://user-images.githubusercontent.com/3062921/72323088-d575d700-36e2-11ea-8022-707d7ef5ec6a.png)
not working

**Comment by urbanishimwe** [comment]
@shuvigoss does the issue occur on macOS Catalina?

**Comment by urbanishimwe** [comment]
@shuvigoss I learned that this issue was produced because this interface doesn't have network address(the only address there is hardware address), it was supposed to be ignored!
