### ISSUE TITLE
QUESTION:  `response`  refers to origin response or copy response .

### ISSUE THREAD

**Issue by amosnothing** [buger/goreplay#728]
In this [docs](https://goreplay.org/monitoring.html)： 

> Middleware has full access to both request and response. 

![shadowing](https://user-images.githubusercontent.com/24653016/72583470-6508c900-3921-11ea-84dc-f56fab6a9214.png)

But I donot know whether `response`  refers to origin response or copy response .

**Comment by urbanishimwe** [comment]
Response refers to the response of the server that received the captured request. e.g `sudo gor --input-raw :8000 --output-stdout --track-respone`. the response to be tracked is from server running on port `8000`
