### ISSUE TITLE
1.0.0 mac version: cpu full

### ISSUE THREAD

**Issue by lfz757077613** [buger/goreplay#730]
It causes cpu 400% when I run 'sudo gor --input-raw :9999 --output-http=xxx --http-allow-url /new/redirect'
![image](https://user-images.githubusercontent.com/16242100/72790402-7c70ea80-3c70-11ea-8995-893e91470174.png)
Its ok when I use 0.16.1

**Comment by jbub** [comment]
@slimus so the result of:

```sudo gor --input-raw en0:9000 --output-stdout```

is that instead of 4 CPUs it just pegs single one with 100% (on version: 1.0.0).

**Comment by slimus** [comment]
@jbub thanks for details. We discussed this issue with team and return with PR or some description a little bit later

**Comment by slimus** [comment]
I have returned with good news
We are using libpcap and google/gopacket as bindings.
And I think libpcap for macos has a bug. I found [opened issue](https://github.com/google/gopacket/issues/499) in gopacket.

So, for our users we have workaround:
`sudo gor --input-raw en0:9000 --input-raw-expire 1s --output-stdout`

@jbub @lfz757077613 can you please test it and tell us about result? You can use v1.0.0 or build it from master, it doesn't matter

**Comment by jbub** [comment]
Yep that worked! Thank you sir!

**Comment by buger** [comment]
@slimus nice one! Lets temporary add check that if it is MacOS fix it to 1 second.

**Comment by slimus** [comment]
@buger done https://github.com/buger/goreplay/pull/763
