### ISSUE TITLE
output-http could not receive any request from the input

### ISSUE THREAD

**Issue by lxjbutterfly** [buger/goreplay#732]
In the source endpoint:
$ sudo ./gor --input-raw :8080 --output-http="http://10.62.49.229:8080"
Version: 1.0.0
2020/02/13 10:21:20 Error when sending  read tcp 10.62.158.31:36748->10.62.49.229:8080: i/o timeout 2020-02-13 10:21:20.51921861 +0100 CET m=+265.855179855
2020/02/13 10:22:20 Error when sending  read tcp 10.62.158.31:36796->10.62.49.229:8080: i/o timeout 2020-02-13 10:22:20.639321976 +0100 CET m=+325.975283222

In the destination endpoint():
[bidvmm@serobidvmm02 ~]$ sudo netstat -anp|grep 8080
tcp        0      0 0.0.0.0:8080            0.0.0.0:*               LISTEN      1237/nginx: master  
It means that there is no connection between the source and the destination, so what's wrong with this issue?
Could anyone give some suggestion?

**Comment by lxjbutterfly** [comment]
Appending:
In the source endpoint:
$ sudo ./gor --input-raw :8080  --output-stdout
It will print all the requests in the screen.

**Comment by urbanishimwe** [comment]
@lxjbutterfly does the issue reproduce with latest release
