### ISSUE TITLE
How to use docker image buger/goreplay

### ISSUE THREAD

**Issue by lxjbutterfly** [buger/goreplay#733]
HI,
  I tried to run the docker image , but the image could be started.

$ docker pull buger/goreplay
Using default tag: latest
latest: Pulling from buger/goreplay
1cae461a1479: Pull complete 
ae77aeafddf2: Pull complete 
Digest: sha256:cda971e34c0a71fc6d23368efca8a0af6984193511d66717ea8592eef305e7ef
Status: Downloaded newer image for buger/goreplay:latest

$ docker run -d  --name gor --network host buger/goreplay
f2a7d8d89f9a2804413b6baa9b068513eb7ca177fc6c5322b03fca1f808e341d

$ docker ps -a
CONTAINER ID        IMAGE                                                          COMMAND                  CREATED              STATUS                          PORTS                               NAMES
f2a7d8d89f9a        buger/goreplay                                                 "./gor"                  About a minute ago   Exited (1) About a minute ago                                       gor

The goreplay could not been started.

Are there anyone have the similar experience?

**Comment by danbamboo** [comment]
What do they docker logs suggest?
 `docker logs f2a7d8d89f9a`

**Comment by danbamboo** [comment]
Check out the wiki: https://github.com/buger/goreplay/wiki/Getting-Started

**Comment by slimus** [comment]
Hi @lxjbutterfly ! Is your question still actual?

**Comment by lxjbutterfly** [comment]
I have gave up to use gorepaly. Thanks







发自我的iPhone


------------------ Original ------------------
