### ISSUE TITLE
HTTP dynamic worker scaling is broken in 1.0

### ISSUE THREAD

**Issue by Syraxius** [buger/goreplay#735]
Hi!

I'd like to bring your attention to the following [code section](https://github.com/buger/goreplay/blob/a8cfaa75812ac176b253ffe1d11eb9bbc7be7522/output_http.go#L164-L177).

```
	if o.config.workersMax != o.config.workersMin {
		workersCount := int(atomic.LoadInt64(&o.activeWorkers))

		if len(o.queue) > workersCount {
			extraWorkersReq := len(o.queue) - workersCount + 1
			maxWorkersAvailable := o.config.workersMax - workersCount
			if extraWorkersReq > maxWorkersAvailable {
				extraWorkersReq = maxWorkersAvailable
			}
			if extraWorkersReq > 0 {
				o.needWorker <- extraWorkersReq
			}
		}
	}
```

If not specified, the default values for the worker parameters are as follows:
- [workersMax = 0](https://github.com/buger/goreplay/blob/a8cfaa75812ac176b253ffe1d11eb9bbc7be7522/settings.go#L159)
- [workersMin = 0](https://github.com/buger/goreplay/blob/a8cfaa75812ac176b253ffe1d11eb9bbc7be7522/settings.go#L158) (even though help hints say default is 1)

At this point, since they're both the same value, then the `o.config.workersMax != o.config.workersMin` condition will evaluate to false and dynamic scaling is disabled.

Even if we assume the suggested defaults of `workersMax = 0`, `workersMin = 1`, we would enter this section but `maxWorkersAvailable` will always be negative, causing `extraWorkersReq` to be negative and `o.needWorker` will never be increased.

Instead, I would suggest this fix:

```
	if o.config.workersMax != o.config.workersMin || o.config.workersMax == 0 {
		workersCount := int(atomic.LoadInt64(&o.activeWorkers))

		if len(o.queue) > workersCount {
			extraWorkersReq := len(o.queue) - workersCount + 1
			maxWorkersAvailable := o.config.workersMax - workersCount
			if extraWorkersReq > maxWorkersAvailable && o.config.workersMax != 0 {
				extraWorkersReq = maxWorkersAvailable
			}
			if extraWorkersReq > 0 {
				o.needWorker <- extraWorkersReq
			}
		}
	}
```

Let me know if you're fine with this and I'll submit a PR.

**Comment by urbanishimwe** [comment]
@Syraxius we're okay with your help
