### ISSUE TITLE
Release a new version with go.mod

### ISSUE THREAD

**Issue by roopakv** [buger/goreplay#739]
Could you please release a new version with the go.mod.

We are trying to update the brew formula to work with go 1.14 and having this will make life a lot easier.

**Comment by slimus** [comment]
Hi @roopakv ! Please look at https://github.com/buger/goreplay/tree/v1.1.0

**Comment by alebcay** [comment]
Thanks for tagging a release! We've shipped the new version downstream at https://github.com/Homebrew/homebrew-core/commit/b8ff07d5ae5b37fd5c36cc4b409ff3193603dbfa. ✨
