### ISSUE TITLE
i used--input-raw-track-response,but still can't get response, only get request

### ISSUE THREAD

**Issue by wumangxing1990** [buger/goreplay#743]
![image](https://user-images.githubusercontent.com/6417189/78102901-0fbb5e80-741e-11ea-9470-7d6503d6182d.png)

**Comment by cyxinda** [comment]
A same problem happened.
I run `./gor --input-raw :30001 --input-raw-track-response --output-file=requests.gor`.
And the messy code of response appeared in the file of 'requests.gor' .
the pic is as follow:
![image](https://user-images.githubusercontent.com/7237898/80357777-09e65b00-88ae-11ea-8072-6550d3c51061.png)

**Comment by lanjingling** [comment]
I encountered the same problem。

i found that：if response body size very bigger，--input-raw-track-response can return response;
but，if response body smaller，not return.

**Comment by urbanishimwe** [comment]
@Ianjingling I think that's the case, but there is a fix on the way
