### ISSUE TITLE
capture traffics from multiple ports and network cards

### ISSUE THREAD

**Issue by wayddmldbzz** [buger/goreplay#747]
If the question can be used to capture packets for network cards or capture packets from multiple ports at once?

**Comment by urbanishimwe** [comment]
@wayddmldbzz capturing from multiple ports in a single goreplay instance is not yet possible although you can have multiple inputs of different types. Currently, the possible workaround is to run multiple goreplay instances for each port.

**Comment by urbanishimwe** [comment]
related to this #784
