### ISSUE TITLE
delay (buffering) on low load

### ISSUE THREAD

**Issue by Fullmetal8ender** [buger/goreplay#762]
Hi. I noticed that when captured load is low (1-10rps) gor does not send requests immediately.
Example: if i have 1 request every 100ms on main server gor will wait for 2 seconds and then will send 20 requests simultaneously. Is it possible for gor to  send requests immediately ?

**Comment by Fullmetal8ender** [comment]
Look like my problem is in -input-raw-expire.
I think, that for keepalive connections this is really hard to determine where is hight-level protocol messages ends, but for a simple connection that ends with FIN packets maybe gor can just "flush" them?

**Comment by slimus** [comment]
@Fullmetal8ender Hi! Can you please show your cli example?

**Comment by Fullmetal8ender** [comment]
1st console
```
sudo ./gor -input-raw lo:80 --output-http http://my_second_server -debug -stats -verbose
<2 sec timeout>
<batch of 20 requests>
<2 sec timeout>
<batch of 20 requests>
```
2nd console
```
while [ 1 ];do curl 0:80/test;sleep 0.1;done
```
3rd
```
tcpdump --nni eth0 port 80
<2 sec timeout>
<batch of 20 requests>
<2 sec timeout>
<batch of 20 requests>
```
-input-raw-expire 0.1s helps me in this case, but I just realized that I don`t know how to mirror keepalived requests at the same rate as they come

**Comment by buger** [comment]
Hi! Can you pls provide some details on such requests. I do not think it is about keep alive. Maybe your requests just take a lot of the time?

**Comment by Fullmetal8ender** [comment]
curl 0:80/test takes 0ms. This is nginx on localhost and /test is empty file

**Comment by buger** [comment]
Any chance you can send us TCP dump so we can replicate it locally?

Thank you!

**Comment by Fullmetal8ender** [comment]
You already have all information for replicate it locally. All you need is: curl, nginx, empty file, shell.
Anyway, see attached dumps - traffic from 127.0.0.1 is captured, traffic from 10.154.18.225 is mirrored.
default.cap is for command 
```./gor -input-raw lo:80 --output-http http://vk.s```
with-input-raw-expire_0.1s.cap is for command
```./gor -input-raw lo:80 --output-http http://vk.s -input-raw-expire 0.1s```
[dumps.zip](https://github.com/buger/goreplay/files/4818511/dumps.zip)

**Comment by urbanishimwe** [comment]
the fix was merged on master

**Comment by Fullmetal8ender** [comment]
Can you show link to commit? I didn`t see any related commit

**Comment by urbanishimwe** [comment]
@Fullmetal8ender check impls in https://github.com/buger/goreplay/blob/master/tcp/tcp_message.go#L127

**Comment by Fullmetal8ender** [comment]
Thank You!
