### ISSUE TITLE
How to rewrite path and\or params?

### ISSUE THREAD

**Issue by HeartIsBeat** [buger/goreplay#770]
when I use `--http-rewrite-url `, It throws error `bash: syntax error near unexpected token `('`

./gor --input-file 'search2_0.gor|200%' --output-http 'http://test-xxx.xxx.com' --verbose --output-http-workers 100 --input-file-loop --http-rewrite-url /v1/user/([^\\/]+)/ping:/v2/user/$1/ping

gor Version: 1.0.0

**Comment by HeartIsBeat** [comment]
@slimus Thankyou so much.You are right!

But I can't get `$1` 

for I use this:
--http-rewrite-url "/v2/search/?([^\s]*):/v2/search/?$1&close_search=1&testPhp=php"

I get this:

![image](https://user-images.githubusercontent.com/20472976/84017306-0c5dc980-a9b1-11ea-99bb-1fc16094260f.png)

**Comment by HeartIsBeat** [comment]
Use this is right
--http-rewrite-url "/v2/search/?v([^\s]*):/v2/search/?v$1&close_search=1estPhp=php"

**Comment by slimus** [comment]
@HeartIsBeat can you please show me example of original requests and what you should get after rewrite.

**Comment by HeartIsBeat** [comment]
Two requests.
One is `GET /v2/search_suggest?from=1`
![image](https://user-images.githubusercontent.com/20472976/84019525-f56ca680-a9b3-11ea-9d0a-dcb6a3abc527.png)

Another is `POST /v2/search/?v=7.7.0&platform=android&from=1&page=2&current_tab=1`
![image](https://user-images.githubusercontent.com/20472976/84019428-d706ab00-a9b3-11ea-84ab-6b1008fe3206.png)

I want to get `POST /v2/search/?v=7.7.0&platform=android&from=1&page=2&current_tab=1&close_search=1&testPhp=php`

**Comment by slimus** [comment]
@HeartIsBeat thanks for examples. 
So, sorry, this is not possible now. You can add params like this `-http-set-param close_search=1 -http-set-param testPhp=php` but this line will add params to all of your requests. 
But you can write your own middleware and ignore some paths and add some params to your urls.

**Comment by HeartIsBeat** [comment]
@slimus Ok. Thankyou so much for your help.
