### ISSUE TITLE
Dynamic configuration using API.

### ISSUE THREAD

**Issue by arijitAD** [buger/goreplay#773]
**Motivation**
Currently, all the configurations are managed by command-line flags. It will be beneficial to have configuration management using API so that we can the application configuration on the go.

**Implementation**
In the current implementation, we parse the command line using the `flag` package. I propose to use [viper](https://github.com/spf13/viper) instead. Viper can handle most types of configuration needs and formats. We can support configuration from the command line as well as API.

Example of configuration management using Viper from the command line.
```
package main

import (
	"flag"
	"github.com/spf13/pflag"
)

func main() {

	// using standard library "flag" package
	flag.Int("flagname", 1234, "help message for flagname")

	pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
	pflag.Parse()
	viper.BindPFlags(pflag.CommandLine)

	i := viper.GetInt("flagname") // retrieve value from viper

	...
}
```
For configuration management using API we can have an endpoint `/flags` and use GET request to modify it. 
`/flags` will return all the flag values along with their default value.
`/flags?foo=bar&xyz=true` indicates that we want to set the flag `foo` to `bar` and `xyz` to `true`

@buger @urbanishimwe @slimus Need your input on this.

**Comment by slimus** [comment]
@arijitAD 
1. I think we should use POST or PATCH http method to modify config. Get method just for get full config (for example http://host/flags should return json with current config)
2. What about save updated flags? Should we store new config or we should flush it after gor stop?
3. Viper is good library. It has readings from JSON, env file, env, etc

**Comment by urbanishimwe** [comment]
That idea will be great actually. pflag offers a lot of ways of parsing configurations, which will be impactful in case of a lot of flags.
Instead of restarting goreplay anytime someone wants to change flags there could rather be an endpoint that help to modify them on the fly.

**Comment by arijitAD** [comment]
> * I think we should use POST or PATCH http method to modify config. Get method just for get full config (for example http://host/flags should return json with current config)
Sure. I will update it to POST.

> * What about save updated flags? Should we store new config or we should flush it after gor stop?
I was thinking not to persist the flags values in the first cut. But that's definitely doable with Viper. We can also load and update config from files.

**Comment by arijitAD** [comment]
> Instead of restarting goreplay anytime someone wants to change flags there could rather be an endpoint that help to modify them on the fly.

Exactly. The user doesn't have to restart for config changes.

**Comment by buger** [comment]
It will be great if you also think about a distributed setup when one instance takes configuration from another GoReplay instance.
