### ISSUE TITLE
--output-file-max-size-limit with compressed .gz file

### ISSUE THREAD

**Issue by xiaofud** [buger/goreplay#775]
Hi, I tested with 
```
sudo gor --input-raw :8080 --output-file=/tmp/gor/requests.txt.gz --output-file-max-size-limit 1m --output-file-append
```
Gor exited when the file /tmp/gor/requests.txt.gz reached 152KB. It seems the `--output-file-max-size-limit` option applies to the decompressed file instead of the gz file. Is there any way for this option to apply to the compressed file?

**Comment by buger** [comment]
Hi! Indeed it looks like a bug.

I checked the code, and issue is on this line 231:

https://github.com/buger/goreplay/blob/3dff07107a7a3793d168d329f4b31d3632e8ac23/output_file.go#L228-L232

Instead of incrementing by direct bytes, it should read "n" argument from the "Write" operation, and use it.
