### ISSUE TITLE
Intercepting traffic 

### ISSUE THREAD

**Issue by Yuvala191** [buger/goreplay#780]
Hello,
I had an issue while trying to forward all my app requests and few requests were missed.
I tried to use debug+verbose mode to see what the problem is but didn't figure out yet, I understood that maybe the issue is many requests have a log of "Intercepting traffic"
The run command: "--input-raw 80 --output-stdout --output-http-timeout 120s"

Anyone knows how to fix it or what is the problem?

**Comment by slimus** [comment]
Hi @Yuvala191 ! Can you please show us:
1. How many RPS do you have?
2. How many bytes in your requests and responses?
Thanks!

**Comment by urbanishimwe** [comment]
@Yuvala191 `--outp-http-timeout` should be used with `--output-http` flag but you've used `--output-stdout`(which prints traffic to stdout), can you refactor the commands and check again

**Comment by Yuvala191** [comment]
> Hi @Yuvala191 ! Can you please show us:
> 
> 1. How many RPS do you have?
> 2. How many bytes in your requests and responses?
>    Thanks!
1. 20 requests per second
2. 2,000 bytes per requests.


> @Yuvala191 `--outp-http-timeout` should be used with `--output-http` flag but you've used `--output-stdout`(which prints traffic to stdout), can you refactor the commands and check again

I tried that before with output-http that's the reason but it didn't work either

**Comment by Yuvala191** [comment]
Used option: "--input-raw-override-snaplen 62914560"

and it solved it.
