### ISSUE TITLE
turn on -prettify-HTTP will cause some requests have no Response

### ISSUE THREAD

**Issue by GITnewfish** [buger/goreplay#781]
when I use
 ./gor --input-raw :8080 --output-file testzpp22.logs -input-raw-track-response --prettify-http --output-http-response-buffer 62914560 --copy-buffer-size 62914560 --input-raw-override-snaplen 62914560
I found that some of the requests did not have response.
![image](https://user-images.githubusercontent.com/38394518/86225649-1a23fa80-bbbd-11ea-85a9-d5bddb6acfe8.png)

then I turn off --prettify-http, all of the requests has response
![image](https://user-images.githubusercontent.com/38394518/86226013-9c142380-bbbd-11ea-9607-367484934c6f.png)

**Comment by GITnewfish** [comment]
seems when response's content-encoding is not gzip, turn on --prettify-http , can not get the response

**Comment by buger** [comment]
Just to clarify, so when request is gzip but response not, it breaks? If so it feels like a bug, and I will rather have this ticket opened.

**Comment by urbanishimwe** [comment]
@GITnewfish did you find the solutions to this issue?

**Comment by GITnewfish** [comment]
> @GITnewfish did you find the solution to this issue?

yes, request is gzip but response not. i turn off --prettify-http , then ok
