### ISSUE TITLE
What is the timestamp format of goReplay records?

### ISSUE THREAD

**Issue by pengsilong** [buger/goreplay#782]
![image](https://user-images.githubusercontent.com/42997980/86313167-0a58f480-bc57-11ea-9f96-b213d61a004e.png)
Hello, may I ask how accurate is this timestamp? We normally use milliseconds, but this is out of the millisecond range, not microseconds.How can I convert this timestamp to yyyy-mm-dd hh:MM:ss ?

**Comment by urbanishimwe** [comment]
@pengsilong  the time stamp there might be in `nanoseconds`
```
const nanoToMilli = 1000000; // from nano to milli
new Date(1593589327796572000 / nanoToMilli).toString(); // Wed Jul 01 2020 09:42:07 GMT+0200 (Central Africa Time)
```
I think, it's not related to `goreplay`.

the information regarding timestamp in gor https://github.com/buger/goreplay/blob/master/settings.go#L164.
