### ISSUE TITLE
some request can not be recorded

### ISSUE THREAD

**Issue by GITnewfish** [buger/goreplay#785]
command:  ./gor --input-raw :80 --output-stdout -input-raw-track-response
gor version: 1.0.0
![image](https://user-images.githubusercontent.com/38394518/86557263-3989a180-bf88-11ea-8d60-92a4dd65ec60.png)

Can you help me out

the nomal request
![image](https://user-images.githubusercontent.com/38394518/86557639-58d4fe80-bf89-11ea-8676-66419dd4dc0a.png)

the lost packets
![image](https://user-images.githubusercontent.com/38394518/86557544-0abffb00-bf89-11ea-8451-ecb966a99969.png)

**Comment by GITnewfish** [comment]
seems not support user-defined request headers?

**Comment by urbanishimwe** [comment]
@GITnewfish there is a fix on the way

**Comment by GITnewfish** [comment]
![image](https://user-images.githubusercontent.com/38394518/86740550-521db880-c069-11ea-843f-1e1873fe8cc1.png)

when request header has "origin", request also lost

May I know when you plan to release this version

**Comment by urbanishimwe** [comment]
@GITnewfish as far as I know, gor doesn't arbitrarily modify any data(particularly headers) unless specified by the user through middlewares. At first, I thought the error was about missing packets. If you think this is a goreplay issue, you may clarify on how you produced this issue so we can solve it in an upcoming version later this month.

**Comment by GITnewfish** [comment]
sorry, These should be my method of use.
when i use the command below, everything is ok
./gor --input-raw :80 --output-stdout -input-raw-track-response --output-http-response-buffer 62914560 --copy-buffer-size 62914560 --input-raw-override-snaplen 62914560
