### ISSUE TITLE
k8s server when replay returns 520

### ISSUE THREAD

**Issue by GITnewfish** [buger/goreplay#787]
my server is in k8s pod
when i replay in pod, response is ok. but when i replay outside pod returns 520, i don't know why.
replay in pod
![image](https://user-images.githubusercontent.com/38394518/87139652-e9d20f80-c2d2-11ea-83f5-c41557783beb.png)
replay outside pod, 
![image](https://user-images.githubusercontent.com/38394518/87140070-7b418180-c2d3-11ea-85c0-62e4bbb51fe8.png)

outside pod, curl test is ok
![image](https://user-images.githubusercontent.com/38394518/87140295-e1c69f80-c2d3-11ea-8168-9ffc08af773a.png)

**Comment by GITnewfish** [comment]
cookie contains "", does this matter?
![image](https://user-images.githubusercontent.com/38394518/87141119-2acb2380-c2d5-11ea-9778-7f35b61c8aff.png)

**Comment by urbanishimwe** [comment]
@GITnewfish if you want to know more about that error [check here](https://community.cloudflare.com/t/community-tip-fixing-error-520-web-server-is-returning-an-unknown-error/44205).
can you check this

> Connection resets (following a successful TCP handshake), Headers exceed the Cloudflare header size limit (over 8kb), An empty response from the origin, An invalid HTTP response, Missing response headers from an HTTP response, or the Presence of multiple Content-Length headers.

> cookie contains "", does this matter?

I think its because there is spaces in that value

**Comment by GITnewfish** [comment]
> @GITnewfish if you want to know more about that error [check here](https://community.cloudflare.com/t/community-tip-fixing-error-520-web-server-is-returning-an-unknown-error/44205).
> can you check this
> 
> > Connection resets (following a successful TCP handshake), Headers exceed the Cloudflare header size limit (over 8kb), An empty response from the origin, An invalid HTTP response, Missing response headers from an HTTP response, or the Presence of multiple Content-Length headers.
> 
> > cookie contains "", does this matter?
> 
> I think its because there is spaces in that value

I delete cookie，still got 520
![image](https://user-images.githubusercontent.com/38394518/87149101-3113cc80-c2e2-11ea-9375-c0855cab235d.png)

**Comment by urbanishimwe** [comment]
No, its not about cookie. I said about because of your question _cookie contains "", does this matter?_.
maybe you can try to give us the body of that request(modify proprietary stuff) so we can check if its about the formatting of gorepaly.

**Comment by GITnewfish** [comment]
my problem is solved. thanks for replay
