### ISSUE TITLE
Can GoReplay support HTTPS protocol? How do you record it?

### ISSUE THREAD

**Issue by pengsilong** [buger/goreplay#788]
Can GoReplay support HTTPS protocol? How do you record it?

**Comment by urbanishimwe** [comment]
the current version drops packet that is not HTTP(i.e that doesn't contain HTTP method). The upcoming version will be able to record almost anything that uses TCP except the behaviors of replaying packets will not be granted to work well! If you particularly need the support for HTTPS you can email us https://goreplay.org/

**Comment by pengsilong** [comment]
> the current version drops packet that is not HTTP(i.e that doesn't contain HTTP method). The upcoming version will be able to record almost anything that uses TCP except the behaviors of replaying packets will not be granted to work well! If you particularly need the support for HTTPS you can email us https://goreplay.org/ so we can consider the options of adding tls!

thank you very much!
