### ISSUE TITLE
input_file: validate empty timestamp

### ISSUE THREAD

**Issue by GITnewfish** [buger/goreplay#789]
I applied GOR to automated testing . A few days ago I recorded a batch of interfaces, now I find a few interfaces missing and I maked up. I changed the timestamps, so the two parts can be played back in sequence. But when I replay, I get this error
![image](https://user-images.githubusercontent.com/38394518/87390186-eb554d80-c5da-11ea-853b-0e5540c7a4c6.png)
 below is part of my record file
![image](https://user-images.githubusercontent.com/38394518/87390323-35d6ca00-c5db-11ea-92d0-cf9ee6d0a21a.png)

Is this error because I modified the timestamp? 

How do you deal with this situation

**Comment by GITnewfish** [comment]
![image](https://user-images.githubusercontent.com/38394518/87390720-ff4d7f00-c5db-11ea-9bc2-2846e78853cc.png)

I changed the timestamps is like this: 2=1+3 and 4=1+5s

**Comment by GITnewfish** [comment]
![image](https://user-images.githubusercontent.com/38394518/87408014-7f341300-c5f5-11ea-8e7f-147a0375b564.png)
I know the reason for this error, its because I carelessly put the request end code at the beginning of the record file.

so the next question is what do you recommend for this situation? Since it's not convenient to change the timestamps.

**Comment by buger** [comment]
Hi! Just to clarify. It is totally fine to change the timestamps if you do not modify the file format. in your case, I assume you copy-pasted a few requests and accidentally put the "monkeys" to the top of the file?

**Comment by GITnewfish** [comment]
> Hi! Just to clarify. It is totally fine to change the timestamps if you do not modify the file format. in your case, I assume you copy-pasted a few requests and accidentally put the "monkeys" to the top of the file?

yes, I accidentally put the "monkeys" to the top of the file. Changing the timestamp can solve the problem, but is there a more convenient way? For example, if I have a switch to control different files do not compare timestamps?
