### ISSUE TITLE
The problem of self-compiled version

### ISSUE THREAD

**Issue by dujiang426** [buger/goreplay#801]
I used the officially compiled version 0.16.1 to replicate the traffic, sent 20000 requests, and finally got 20000 traffic, but I used the version compiled by myself based on the source code of version 0.16.1, sent 20000 requests, and finally got the traffic. It is always less than 20000 (for example, 197592). Why? The same environment and request are used

This is my compile command`go build -ldflags "-s -w -X main.VERSION=0.16.1" -o gor`

**Comment by urbanishimwe** [comment]
so it can depends on factors like `libcap version` or if you cloned the master branch it may not be really version 0.16.1(`go get -u github.com/buger/goreplay@v0.16.1`),
