### ISSUE TITLE
 In the same environment, v1.1.0 version gets less traffic than v0.16.1 version

### ISSUE THREAD

**Issue by dujiang426** [buger/goreplay#805]
I sent 20w requests for v0.16.1 and v1.1.0 in the same environment. The v0.16.1 version can get about 16w requests, but the v1.1.0 version can only get about 10w requests. Why is this?

**Comment by urbanishimwe** [comment]
@dujiang426  AFAIK no optimization was done on part of capture engines in the recently released versions!
In the meantime, you can try to use master it will perform well with `libpcap`(note that raw_socket is still in progress), it was optimized to capture many traffics and much more data as possible(feel free to open issues as well while testing).
more description will be provided in the version to be released!

**Comment by dujiang426** [comment]
I used the master branch to compile a version by myself, but an error was reported when I executed the following command

`sudo ./gor --input-raw :8080 --output-kafka-host '192.168.0.1:9092,192.168.0.2:9092' --output-kafka-topic 'kafka-log'`

panic: reflect: Call with too many input arguments

goroutine 1 [running]:
reflect.Value.call(0xc8caa0, 0xe12f68, 0x13, 0xdbecbb, 0x4, 0xc000088600, 0x3, 0x4, 0x1, 0x0, ...)
  /home/admin/go/src/reflect/value.go:380 +0x134c
reflect.Value.Call(0xc8caa0, 0xe12f68, 0x13, 0xc000088600, 0x3, 0x4, 0x2, 0x4, 0x1)
  /home/admin/go/src/reflect/value.go:321 +0xb4
main.(*InOutPlugins).registerPlugin(0xc00007c7d0, 0xc8caa0, 0xe12f68, 0xc00019fda8, 0x3, 0x3)
  /home/admin/gocode/src/github.com/buger/gor/plugins.go:50 +0x1f4
main.NewPlugins(0xc0000882a0)
  /home/admin/gocode/src/github.com/buger/gor/plugins.go:140 +0x52f
main.main()
  /home/admin/gocode/src/github.com/buger/gor/gor.go:54 +0x8f2

**Comment by urbanishimwe** [comment]
Cc: @arijitAD there is a bug in plugin register at line 140

**Comment by urbanishimwe** [comment]
@dujiang426 please use master if you want more data!
