### ISSUE TITLE
gzip request decompress failure

### ISSUE THREAD

**Issue by dujiang426** [buger/goreplay#808]
I use the following command

`sudo ./gor --input-raw :8080 --output-kafka-host "192.168.0.1:9092,192.168.0.2:9092" --output-kafka-topic "kafka-log"`

to write the copied traffic to Kafka, but when consuming from Kafka, if the requested body type is in gzip format, I will fail when I decompress the body according to the communication protocol in the document.

```
String requestPayload = new String(kafkaBytes); 
String gzipRequestBody = parseRequestBody(requestPayload);  
unGzip(gzipRequestBody.getBytes());
```

error is: `java.util.zip.ZipException: Not in GZIP format`

**Comment by urbanishimwe** [comment]
@dujiang426 can you show us the header of that payload (content-type and content-length)! was the request big enough so that maybe some data was not sent, check the original length versus sent data length

**Comment by dujiang426** [comment]
> @dujiang426 can you show us the header of that payload (content-type and content-length)! was the request big enough so that maybe some data was not sent, check the original length versus sent data length

Thank you very much. I know where the problem is. This is a bug in my program. I converted the byte array into a string and parsed the body except for errors.
