### ISSUE TITLE
--output-http stopped working in 1.2.0

### ISSUE THREAD

**Issue by anatoly71** [buger/goreplay#831]
Host osx 10.15.5, goreplay 1.2.0.

The simple scenario (read in a file and output to an http server all on the same host) works fine with goreplay 1.1.0. Below are the commands and outputs.

 Version 1.2.0- not traffic reaches mockservice
`./gor_1.2.0 -verbose 2   --input-file ./replay.log --output-http localhost:18080`
2020/10/01 13:14:35 [PPID 5270 and PID 16548] Version:1.2.0
2020/10/01 13:14:35 FileInput: end of file './replay.log'
[DEBUG][elapsed 2.950584ms]: [OUTPUT-HTTP] meta: ["1" "2ab9131d28832ba909e154555192728c42e8cd99" "1497876005018046050"]
[DEBUG][elapsed 32.895µs]: [OUTPUT-HTTP] meta: ["1" "8af9872d076412bb109de1b8f9f9c6cd2a929dcd" "1497876005018046775"]
[DEBUG][elapsed 34.826µs]: [OUTPUT-HTTP] meta: ["1" "a15266ae2134d646361089a2bc7ae41034b69440" "1497876005018046880"]
[DEBUG][elapsed 23.405µs]: [OUTPUT-HTTP] meta: ["1" "a15266ae2134d646361089a2bc7ae41034b69440" "1497876005018046885"]
.....

 Version 1.1.0 works fine, traffic reaches mockservice
`./gor_1.1.0 -verbose --input-file ./replay.log  --output-http http://localhost:18080/`
Version: 1.1.0
[DEBUG][PID 16622][Oct  1 13:19:44.078654000][elapsed 3.339715ms] [HTTPClient] Connecting: http://localhost:18080/
2020/10/01 13:19:44 FileInput: end of file './replay.log'
[DEBUG][PID 16622][Oct  1 13:19:44.079864000][elapsed 1.210484ms] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.079897000][elapsed 33.325µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.079957000][elapsed 60.056µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.080001000][elapsed 44.028µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.080089000][elapsed 87.577µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.080162000][elapsed 73.109µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.080229000][elapsed 67.019µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.080291000][elapsed 61.57µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.080365000][elapsed 74.689µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.083376000][elapsed 3.010466ms] [HTTPClient] isAlive readBytes  1
[DEBUG][PID 16622][Oct  1 13:19:44.083576000][elapsed 200.137µs] [HTTPClient] Closed connection on 400 response
[DEBUG][PID 16622][Oct  1 13:19:44.083606000][elapsed 29.788µs] [HTTP] Disconnected:  http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:44.083676000][elapsed 70.497µs] [HTTPClient] Connecting: http://localhost:18080/
[DEBUG][PID 16622][Oct  1 13:19:45.084924000][elapsed 1.001243547s] [HTTPClient] Response read unknown error read tcp [::1]:58809->[::1]:18080: i/o timeout &{{0xc00128e180}} 15 {"status":"OK"}
[DEBUG][PID 16622][Oct  1 13:19:45.085164000][elapsed 239.757µs] [HTTP] Disconnected:  http://localhost:18080/
2020/10/01 13:19:45 Error when sending  read tcp [::1]:58809->[::1]:18080: i/o timeout 2020-10-01 13:19:45.085182 +0300 MSK m=+1.018946409
[DEBUG][PID 16622][Oct  1 13:19:45.085230000][elapsed 66.169µs] Request error: read tcp [::1]:58809->[::1]:18080: i/o timeout

**Comment by urbanishimwe** [comment]
I did experience this too!

**Comment by buger** [comment]
should be fied now
