### ISSUE TITLE
DEBUG message printed with verbose 0

### ISSUE THREAD

**Issue by jkerr5** [buger/goreplay#840]
With the `--stats --output-http-stats` options set, I am getting "DEBUG" messages in the output. I explicitly set verbose to "0" but that didn't change anything.

```
[DEBUG][elapsed 1.2972ms]: 
 output_http:latest,mean,max,count,count/second,gcount
[DEBUG][elapsed 50.167µs]: 
 output_http:0,0,0,0,0,6
[DEBUG][elapsed 5.000112842s]: 
 output_http:0,0,0,25,5,59
```

**Comment by urbanishimwe** [comment]
stats will be printed regardless of the debug value if stats flags are provided.
These functionalities may be changed later!

**Comment by jkerr5** [comment]
Why does it say "DEBUG"?

**Comment by urbanishimwe** [comment]
It is not yet standardized
