### ISSUE TITLE
How do you get detailed response time statistics

### ISSUE THREAD

**Issue by jkerr5** [buger/goreplay#841]
I know that summary stats can be output for HTTP calls but I would like to get the detailed stats so I can calculate stats like 95th, 99th percentile response time, etc. Is there a way for me to see/record how long each request actually takes?

**Comment by urbanishimwe** [comment]
I think there is no way for now but detailed stats are on our future plans!

**Comment by jkerr5** [comment]
Thanks. I was just looking at https://github.com/buger/goreplay/wiki/Middleware#communication-protocol and see the 4 is "latency". What are the units and what makes it "tricky"?

**Comment by urbanishimwe** [comment]
> What are the units

the unit is **Unix Time** as **int64**, from Go docs its "the number of nanoseconds elapsed since January 1, 1970, UTC."

> and what makes it "tricky"?

if you know how you can use that meta, it may not be tricky!

**Comment by jkerr5** [comment]
Thanks. That is helpful.
