### ISSUE TITLE
Is the request id unique globally? 

### ISSUE THREAD

**Issue by ZmfCn** [buger/goreplay#842]
As the document, I expect it is.
![image](https://user-images.githubusercontent.com/29651828/96822402-8a9ca300-145c-11eb-9599-950577e564ea.png)

But after I captured traffic and analyze the .gor file, I saw that request id is not seemly unique. The following picture is my traffic file and I searched one request Id but 46 matched.

![image](https://user-images.githubusercontent.com/29651828/96825782-81173900-1464-11eb-81e5-e9a22ba4ce76.png)

And I found that `tcp_message.go#UUID()` function calculates the request id by src address and dest address, which seems not to be unique.

Could you please answer this question? Thanks!

**Comment by urbanishimwe** [comment]
@ZmfCn  as the [docs](https://github.com/buger/goreplay/blob/master/tcp/tcp_message.go#L48) says, that function generate (most likely) the unique ID of  **a TCP session**, **not of a request**. The source and destination socket should be the virtual identification of the session. However, the uniqueness **may not exceed 65535 on most servers**. Requests/responses with the same TCP session will have the same ID(which I think is your case). The TCP acknowledgment number used in former versions may cause errors as requests and responses are now parsed independently.

This may improve!

**Comment by ZmfCn** [comment]
@urbanishimwe   Thank you for your reply. The Protocol http/1.1 uses pipelining to reuse a tcp connection, so there may be more than one requests having the same requset id, right? And the http/1.1 pipelining feature require the server to return the response as the order of the received request(as the [REC2616](https://tools.ietf.org/html/rfc2616#section-8.1.2.2) says). But when I tried to analyze with this rule, I couldn't find corresponding response for some requests(is there something wrong with me?). In this case, I couldn't match the request and response now. 

**So is there an available approach to analyze request and corresponding response from the .gor file?**

**Comment by urbanishimwe** [comment]
yes, **_"Requests/responses with the same TCP session will have the same ID"_**.

**_"pipelining feature require the server to return the response as the order of the received request(as the REC2616 says)"_**.
Goreplay just captures traffics as they come in and parse them in the same order.

**_"I tried to analyze with this rule, I couldn't find the corresponding response for some requests"_**
have you used `track-response` flags?

**Side note**: From the screenshot, I forgot to mention that request and response must have the same ID, so what you saw is not really an issue

to analyze the .gor file, `meta` data that are added to each message can be used. check [this issue](https://github.com/buger/goreplay/issues/841). There is a plan to implement this in the right way!

**Comment by ZmfCn** [comment]
Thanks again! I used following command to capture:

`sudo gor --input-raw :8080 \
-http-allow-method GET \
-http-allow-method POST \
-http-allow-method PUT \
-http-allow-method DELETE \
--input-raw-track-response \
--output-file requests.gor`

**I tried to analyze with this rule, I couldn't find the corresponding response for some requests**  I mean that I can find response for a part of requests, while some others not. Is that possible? And is there something wrong with me?

**Comment by urbanishimwe** [comment]
some traffics can be missed! which Goreplay version are you using?

**Comment by ZmfCn** [comment]
Previously, The version is **v1.2.0**


And when I changed the version to **v1.1.0**, something different happened. Althought the responses still partly missed,**The request ids same to be globally unique.**. And the command is:
```sh
./gor --input-raw :8080 \
-http-allow-method GET \
-http-allow-method POST \
-http-allow-method PUT \
-http-allow-method DELETE \
--input-raw-track-response \
--prettify-http \
--output-file-append \
--input-raw-buffer-size 10485760 \
--output-file requests.log
```

Following screenshot is from a .gor file (v1.1.0) with size 272Mi, and I don't find a request id used by more than 2 parts(analyzed by program). And I see the logic to calculate request id is different(using ack), is something wrong with this way?
![image](https://user-images.githubusercontent.com/29651828/97131123-4243f480-177e-11eb-9c9e-78559608f358.png)

**Comment by urbanishimwe** [comment]
I presume this is why we changed it!

> The TCP acknowledgment number used in former versions may cause errors as requests and responses are now parsed independently

**Comment by ZmfCn** [comment]
Thanks you very much !  All these are helpful~

**Comment by ChenLingPeng** [comment]
https://github.com/buger/goreplay/blob/master/input_raw.go#L81

enlarge the message chan size may help you when finding missing request/response

**Comment by urbanishimwe** [comment]
> enlarge the message chan size may help you when finding missing request/response

neat!

**Comment by ZmfCn** [comment]
> https://github.com/buger/goreplay/blob/master/input_raw.go#L81
> 
> enlarge the message chan size may help you when finding missing request/response


> https://github.com/buger/goreplay/blob/master/capture/capture.go#L113


Thanks. Does this mean that I should change the chan size and re-build goreplay myself to avoid response missing? Or that just helps when I debug?
@urbanishimwe @ChenLingPeng

**Comment by ChenLingPeng** [comment]
In my case, this change can avoid request/response miss.

**Comment by ZmfCn** [comment]
> In my case, this change can avoid request/response miss.

Thank you, I will try.

**Comment by urbanishimwe** [comment]
you may as well provide the end results!

**Comment by ZmfCn** [comment]
Back here, I tried. Here are my operations:
1. I checked out from tag `v1.2.0`
2. I modified the value of the [](https://github.com/buger/goreplay/blob/master/input_raw.go#L81) and [](https://github.com/buger/goreplay/blob/master/capture/capture.go#L113) from `1000` to `1000000` and built a new binary via command `go build -ldflags "-extldflags \"-static\""` and go version is `1.13.1`
3. Using the new binary, I captured the traffic by this command:

   ```sh
   ./gor --input-raw :8080 \
  -http-allow-method GET \
  -http-allow-method POST \
  -http-allow-method PUT \
  -http-allow-method DELETE \
  --input-raw-track-response \
  --prettify-http \
  --output-file-append \
  --input-raw-buffer-size 10485760 \
  --output-file requests.log
   ```

4. And found that there were `42005` requests and `33876` responses, which means reponses are still partly missed.


And before this modification, I captured `24870` requests and `15616` responses

**Comment by urbanishimwe** [comment]
thanks for the information!
I will open a proposal to add flags to increase the queue buffer size!

**Comment by ZmfCn** [comment]
> thanks for the information!
> I will open a proposal to add flags to increase the queue buffer size!

OK~

**Comment by ZmfCn** [comment]
> https://github.com/buger/goreplay/blob/master/input_raw.go#L81
> 
> enlarge the message chan size may help you when finding missing request/response

@ChenLingPeng  Could you please look at the operations above of me and tell the difference to yours?

**Comment by urbanishimwe** [comment]
FWIW; @ZmfCn if you try these flags `-input-raw-buffer-size 32mb` and `-input-raw-buffer-timeout 1m` you may see a significant improvement in packets capturing without even changing the channel capacity
