### ISSUE TITLE
Req_ID bug introduced between 1.1.0 and 1.2.0

### ISSUE THREAD

**Issue by davidFR** [buger/goreplay#851]
Hello,

Since 1.2.0/master, there is a regression for Req_ID : duplicates.

## Expected Behavior
Unique Req_ID between request and its reponse

## Current Behavior
* lots of duplicate Req_ID if http requests are close (from 15 to 90 duplicates)
* and fake requests with empty url

## Steps to Reproduce
1. Start a kafka  (`docker-compose up` with the given [docker-compose.yml.txt](https://github.com/buger/goreplay/files/5494019/docker-compose.yml.txt))
2. Start a fake server. I choose json-server to run a minimal helloworld api port 3000. 
  * Command: `json-server data.json` 
  * File: data.json
```
{
  "myapi": [
    { "hello": "world" }
  ]
}
```
3. Listen this port with goreplay : `./goreplay --input-raw :3000 --input-raw-track-response  --output-kafka-host localhost:9092 --output-kafka-topic goreplay.mytopic --output-kafka-json-format --verbose 4`
4. Make a call `curl http://localhost:3000/myapi` : you will see 3 messages and the first is empty
```
{
   "Req_URL": "",
   "Req_Type": "1",
   "Req_ID": "2be777156e5dca81dedabd214ad6f68e354a2950",
   "Req_Ts": "1604575803638549781",
   "Req_Method": ""
}
```
5. Make several sequential calls `for i in {1..10}; do curl http://localhost:3000/myapi ; done` : you will see correct Req_ID
6. Make simultaneous calls `docker run --net=host --rm skandyla/wrk -t2 -c4 -d5s http://localhost:3000/myapi` and  duplicates appear

## Detailed Description

Bug in master and 1.2.0
Tested in 1.0.0 and there is no duplicate and no empty requests.

Extracts of GoReplay log in verbose mode : 
```
[DEBUG][elapsed 40.892µs]: [EMITTER] input: 1 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417481867135 0
[DEBUG][elapsed 27.79µs]: [EMITTER] input: 2 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417485262099 0
[DEBUG][elapsed 41.319µs]: [EMITTER] input: 1 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417485307927 0
[DEBUG][elapsed 70.488µs]: [EMITTER] input: 2 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417488838413 0
[DEBUG][elapsed 46.536µs]: [EMITTER] input: 1 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417488884062 0
[DEBUG][elapsed 38.186µs]: [EMITTER] input: 2 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417492414232 0
[DEBUG][elapsed 43.084µs]: [EMITTER] input: 1 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417492466856 0
[DEBUG][elapsed 34.67µs]: [EMITTER] input: 2 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417496312305 0
[DEBUG][elapsed 39.395µs]: [EMITTER] input: 1 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417496411034 0
[DEBUG][elapsed 29.3µs]: [EMITTER] input: 2 65039eaa7085bd30c1327e73042b699f74f1dd47 1604578417500636937 0
```
Complete log : 
[log.txt](https://github.com/buger/goreplay/files/5494286/log.txt)

```
$ grep 65039eaa7085bd30c1327e73042b699f74f1dd47 log.txt  | wc -l
96
```

**Comment by davidFR** [comment]
After some tests, same bug in file recording : 
1. Start a fake server
2. Listen this port with goreplay : `./goreplay --input-raw :3000 --input-raw-track-response  --verbose 4  --output-file record_%Y%m%d.gor --output-file-append`
3. Make simultaneous calls : `docker run --net=host --rm skandyla/wrk -t2 -c4 -d5s http://localhost:3000/myapi`

Lots of duplicates in record : [record_20201105.txt](https://github.com/buger/goreplay/files/5494346/record_20201105.txt)

**Comment by davidFR** [comment]
Same tests on version 1.1.0 give no duplicate :
`./goreplay --input-raw :3000 --input-raw-track-response --output-file record_%Y%m%d.gor --output-file-append --verbose`

```
$ grep "^1 " record_20201105.gor | cut -d  " " -f 2 | sort | uniq -d
```

**Comment by urbanishimwe** [comment]
for re-used TCP sessions, this should occur! see(#842)

Coincidently, I was trying many ways to fix this!

**Comment by davidFR** [comment]
If I understand issue 842, between 1.1.0 and 1.2.0 you change the Req_ID in order to lost less responses, but now Req_ID is not an unique ID.

 Is it a bug for you or a new feature than we have to deal with ?

**Comment by urbanishimwe** [comment]
That was another issue that passed by in the comment but the real issue was about "same ID".

**Comment by davidFR** [comment]
Note also the additionnal empty request present for each request :
```
{
   "Req_URL": "",
   "Req_Type": "1",
   "Req_ID": "2be777156e5dca81dedabd214ad6f68e354a2950",
   "Req_Ts": "1604575803638549781",
   "Req_Method": ""
}
```

**Comment by urbanishimwe** [comment]
try adding `--verbose 4` it may give out information about it!
