### ISSUE TITLE
elasticsearch can't parse URI

### ISSUE THREAD

**Issue by quzhixue-Kimi** [buger/goreplay#854]
hi there,

Based on your doc via https://github.com/buger/goreplay/wiki/Exporting-to-ElasticSearch

The es7 and gor 1.2 have been installed in my centos7 OS and, I ran the command as below: (Is there any version limitation of elasticsearch?)

/usr/local/bin/gor --input-raw :8080 --output-http http://localhost:8081 --output-http-elasticsearch http://localhost:9200/test123

The test123 index has not been created. Also, the pattern of es URI must be scheme://host/index_name
 Otherwise, the exception will be thrown out:
2020/11/13 15:49:38 Can't initialize ElasticSearch plugin.Wrong ElasticSearch URL format. Expected to be: scheme://host/index_name

It is appreciated that you could guide me on how to resolve this issue.

And, another issue is about kafka with version 1.2, which https://github.com/buger/goreplay/issues/848 has been submitted.
I am concerning whether this bug related with kafka will be fixed in next version (v1.3?) and when will the next version be released?

Sorry for your inconvenience.
BR
Kimi

**Comment by urbanishimwe** [comment]
Kafka issue is fixed on the master branch(try a build with master branch), I believe the new version may be released this month.

**Comment by quzhixue-Kimi** [comment]
hi there,

Thanks for your reply about the kafka issue! It is appreciated that you may help investigate the elasticsearch issue and update your doc.

Sorry for your inconvenience.
BR
Kimi

**Comment by urbanishimwe** [comment]
I think it's not about the doc! the problem might be [about parsing URL](https://github.com/buger/goreplay/blob/master/elasticsearch.go#L63)

**Comment by quzhixue-Kimi** [comment]
Hi there,

Thank you for your reply and, there is a stupid question that I would like to ask as below:
The binary gor file should be installed on the same server to catch the http request. May I install the gor file into another server and try to catch the http server? Such as: gor file installed on 192.168.18.6 server and catch the ip 1.2.3.4 (or test.me:8080) server's 8080 port.
sudo gor --input-raw 1.2.3.4:8080 --output-http http://5.6.7.8:8081

Sorry for your inconvenience
BR
Kimi

**Comment by urbanishimwe** [comment]
Basically, you need to install gor on the same host machine as the server. if gor is not installed on a machine with IP `1.2.3.4`, it won't capture any traffic(if not fails to start at all).

**Comment by quzhixue-Kimi** [comment]
Copy, copy

Thanks

Kimi

**Comment by quzhixue-Kimi** [comment]
Hi there,


> I think it's not about the doc! the problem might be [about parsing URL](https://github.com/buger/goreplay/blob/master/elasticsearch.go#L63)

So, May it be a new bug to track this issue? Or, is there any solution or new guide to fix the es issue?

Sorry for your inconvenience.
BR
Kimi

**Comment by quzhixue-Kimi** [comment]
Hi there,

And, I would like to make the compile based on your suggestion and the doc via https://github.com/buger/goreplay/wiki/Compilation

But, got the compile error. When I just ran 'go build', there is one binary file named goreplay file generated.
![image](https://user-images.githubusercontent.com/8235746/99204172-c32b6480-27ef-11eb-86ef-362bb633be19.png)

Then, when I just ran ./goreplay, the error is "error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory"

Any suggestion is appreeciated.

Sorry for your inconvenience.
BR
Kimi

**Comment by urbanishimwe** [comment]
> So, May it be a new bug to track this issue? Or, is there any solution or new guide to fix the es issue?

I think there is nothing wrong with your URI format. this is a new bug to track this issue.

> when I just ran ./goreplay, the error is "error while loading shared libraries: libpcap.so.1: cannot open shared object file: No such file or directory"

have you installed libpcap? also just using `go build .` is sufficient in most cases.

**Comment by quzhixue-Kimi** [comment]
hi there,

OS: ubuntu 16.04
Switch to root user

Not sure, whether the code has been the latest or not. During the 'go get github.com/buger/gor' command ran, there is one message shown
![image](https://user-images.githubusercontent.com/8235746/99490156-42fa3000-29a4-11eb-9ca4-0c001138123f.png)

And then, what I did based on the doc to get the message as below:
![image](https://user-images.githubusercontent.com/8235746/99490543-05e26d80-29a5-11eb-88e8-f8c54a8754b6.png)

All what I have done was based on the https://github.com/buger/goreplay/wiki/Compilation


Sorry for your inconvenience
BR
Kimi

**Comment by urbanishimwe** [comment]
meanwhile, you may `git clone https://github.com/buger/goreplay.git`
after properly installing libpcap, `go build .` will probably work.

**Comment by urbanishimwe** [comment]
@quzhixue-Kimi I can't reproduce this issue on `master` with the same command, try and give us some updates.

**Comment by quzhixue-Kimi** [comment]
hi there,

Thanks for your reply.

I made one virtual machine with Ubuntu 16.04 x64 again and, go version with 1.15.5

libpcap installed with 1.7.4 and 1.9.1 version installed in /usr/local/lib

![image](https://user-images.githubusercontent.com/8235746/99617273-fd983a00-2a59-11eb-8b45-140e81d706d3.png)

The latest code of master branch

![image](https://user-images.githubusercontent.com/8235746/99617337-23254380-2a5a-11eb-98c0-feedcfedc937.png)


go build . command ran

![image](https://user-images.githubusercontent.com/8235746/99617356-2c161500-2a5a-11eb-9f70-10b4606dae86.png)

generate one file named goreplay

ran ./goreplay, error occurred as below:

![image](https://user-images.githubusercontent.com/8235746/99617409-40f2a880-2a5a-11eb-8e78-018014393d46.png)


Sorry for your inconvenience.
BR
Kimi

**Comment by urbanishimwe** [comment]
Interestingly on my system(linux) doesn't show the same results.
```
pc@pc:~$ whereis libpcap
libpcap: /usr/lib/x86_64-linux-gnu/libpcap.so /usr/lib/x86_64-linux-gnu/libpcap.a
```

have you tried `sudo apt install libpcap-dev` or equivalence.

**Comment by quzhixue-Kimi** [comment]
hi there,

yes, I install the libpcap-dev and get the latest master branch code to make the compile. Successfully.
It is appreciated that you may help to resolve the es issue. Is that the latest master branch fixed this es issue already?

Sorry for your inconvenience.

BR
Kimi

**Comment by urbanishimwe** [comment]
> Is that the latest master branch fixed this es issue already?

we can't reproduce the issue on the master.

**Comment by quzhixue-Kimi** [comment]
Hi there,

sure, waiting for your the latest binary file. Thank you very much

BR
Kimi

**Comment by quzhixue-Kimi** [comment]
Since the latest master branch code fixed the kafka issue, this issue will be closed.


BR
Kimi
