### ISSUE TITLE
goreplay replaying HTTP traffic lost uri

### ISSUE THREAD

**Issue by two** [buger/goreplay#862]
version: v1.2.0

server1:
```
./goreplay --file-server 8000
```
server2:
```
./goreplay --file-server 8001
```
star traffic:
```
./goreplay --input-raw :8000 --output-http="http://localhost:8001"
```

send request:
```
curl http://localhost:8000/demo/get
```
server1  log:
```
2020/12/03 20:33:42 GET /demo/get HTTP/1.1
Host: localhost:8000
Accept: */*
User-Agent: curl/7.29.0
```
server2 log:
```
2020/12/03 20:33:42 GET / HTTP/1.1
Host: localhost:8001
Accept: */*
Accept-Encoding: gzip
User-Agent: curl/7.29.0
```

question:

server1 got request path : ` /demo/get` but server2 got request path `/`

**Comment by urbanishimwe** [comment]
for the record, some users explicitly provide `output path` like `-output-http "http://localhost/[something]"` and they expect all requests to be sent with `[something]` appended.
What should be done I think is to add new flag: `-output-http-use-request-path`  if it's true we can then use a path from the original request.

**Comment by two** [comment]
most scenes we use this tool if for replay request with the same path, and now the v1.2.0 is not compatible with the old version
maybe we can judge the logic to be executed by whether there is a path
case 1:
`--output-http "http://host:port"`
all request will be send to  ` url.ParseRequestURI(c.config.url.Scheme + "://" + c.config.url.Host + req.RequestURI)`
case 2:
`--output-http "http://host:port/[something]"`
all request will be send to `c.config.url`

**Comment by two** [comment]
like this:
```
if c.config.url.Path == "" {
		req.URL, _ = url.ParseRequestURI(c.config.url.Scheme + "://" + c.config.url.Host + req.RequestURI)
	} else {
		req.URL = c.config.url
	}
```

**Comment by urbanishimwe** [comment]
sounds fair enough! I left the comment https://github.com/buger/goreplay/pull/864#discussion_r537011610
