### ISSUE TITLE
v1.2.0 will block sometimes.

### ISSUE THREAD

**Issue by LuZiZhang** [buger/goreplay#871]
I found that gor will enter the block state from time to time. I print and process stack trace. The trace information of 142 out of 152 goroutines is as follows:
goroutine 311978 [semacquire, 39 minutes]:
sync.runtime_SemacquireMutex(0xc0000a30e4, 0xc0018cad00, 0x1)
        /usr/local/go/src/runtime/sema.go:71 +0x47
sync.(*Mutex).lockSlow(0xc0000a30e0)
        /usr/local/go/src/sync/mutex.go:138 +0x105
sync.(*Mutex).Lock(...)
        /usr/local/go/src/sync/mutex.go:81
github.com/buger/goreplay/tcp.(*MessagePool).dispatch(0xc0000a30e0, 0x809d005046897d64, 0xc001ada6c0)
        /www/gocode/goreplay/tcp/tcp_message.go:245 +0x27e
created by github.com/buger/goreplay/tcp.(*MessagePool).Handler
        /www/gocode/goreplay/tcp/tcp_message.go:213 +0x7d6

**Comment by urbanishimwe** [comment]
the state of that function was modified https://github.com/buger/goreplay/blob/master/tcp/tcp_message.go#L243 (I guess at that time it would block if `input-raw-expire` and `copy-buffer-size` happens at the same time)
not sure if this can be reproduced on the master.

**Comment by LuZiZhang** [comment]
I complie with the code of master branch. And the commd as follows:./gor --input-raw :80 --output-file ./dump.gor --output-file-append. but the same situation happend.

**Comment by urbanishimwe** [comment]
in general, that function should certainly block waiting for (*tcp.MessagePool).Handler to release the lock. unless you saw it holds the lock for too long?

**Comment by LuZiZhang** [comment]
> in general, that function should certainly block waiting for (*tcp.MessagePool).Handler to release the lock or vice versa(and this can happen more than one time). unless you saw it holds the lock for too long?

yes，the process will block here. And there were no more traffic written to file any more.

**Comment by urbanishimwe** [comment]
I'm closing this as working as expected!

(unless there is further info)
