### ISSUE TITLE
many duplicate request id appears

### ISSUE THREAD

**Issue by GITnewfish** [buger/goreplay#876]
When I record with the following command: 
./gor --input-raw :$3 --output-file "./record_dir/$2" -input-raw-track-response --prettify-http --output-http-timeout 30s --output-http-response-buffer 62914560 --copy-buffer-size 62914560 --input-raw-override-snaplen 62914560 -output-file-append

I found that there were a lot of duplicate request ids, but the request ID should be unique.

![image](https://user-images.githubusercontent.com/38394518/103396998-2b03f780-4b71-11eb-9500-9a7357ef9f41.png)

**Comment by SloanAufderstrase** [comment]
same problem

**Comment by urbanishimwe** [comment]
a fix was merged some time ago https://github.com/buger/goreplay/pull/855
