### ISSUE TITLE
The goreplay binary from the latest master branch didn't record http request

### ISSUE THREAD

**Issue by GITnewfish** [buger/goreplay#877]
The goreplay binary is packaged with code from the latest master branch, when i use this gorpelay binary to record, i found no http request was recorded.
package method: 
https://github.com/buger/goreplay/wiki/Compilation
the goreplay binary

I am not familiar with go language, I am not sure if it is my compilation problem. But the compilation process is error-free
![image](https://user-images.githubusercontent.com/38394518/103513533-c7960480-4ea5-11eb-99d6-a853e3fe0b8d.png)

**Comment by urbanishimwe** [comment]
fresh `go build .` works most of the times

**Comment by urbanishimwe** [comment]
@GITnewfish  The temporary fix is to specify interface name like `-input-raw eth:80`

**Comment by GITnewfish** [comment]
still can not work
![image](https://user-images.githubusercontent.com/38394518/103844949-03171580-50d6-11eb-9ef7-a0a36c080ab5.png)

**Comment by urbanishimwe** [comment]
@GITnewfish this looks like libpcap is missing! you built goreplay with dynamic linking?

**Comment by buger** [comment]
Indeed smth wrong with libpcap you have locally. 
In order to do a build, you should have libpcap-dev version, with needed headers.

**Comment by GITnewfish** [comment]
Thank you very much for your careful answers .
Since my libpcap was unzipped in my personal directory, I created a soft link, and it works.
