### ISSUE TITLE
panic: runtime error: slice bounds out of range [-1:]

### ISSUE THREAD

**Issue by gitmessage** [buger/goreplay#879]
sudo ./gor --input-raw :3306 --input-raw-realip-header "X-Real-IP" --output-stdout

panic: runtime error: slice bounds out of range [-1:]
goroutine 5 [running]:
github.com/buger/goreplay/byteutils.Insert(...)
	/go/src/github.com/buger/goreplay/byteutils/byteutils.go:20
github.com/buger/goreplay/proto.AddHeader(0xc0004b4000, 0xb24, 0xc00, 0xc000063a40, 0x9, 0x20, 0xc000063a20, 0x10, 0x20, 0xffffffffffffffff, ...)
	/go/src/github.com/buger/goreplay/proto/proto.go:174 +0x45d
github.com/buger/goreplay/proto.SetHeader(0xc0004b4000, 0xb24, 0xc00, 0xc000063a40, 0x9, 0x20, 0xc000063a20, 0x10, 0x20, 0x1742538, ...)
	/go/src/github.com/buger/goreplay/proto/proto.go:160 +0x4e7
main.(*RAWInput).Read(0xc0002de000, 0xc000580000, 0x500000, 0x500000, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/input_raw.go:120 +0x7de
main.CopyMulty(0xc0000965a0, 0x7f1a3171b600, 0xc0002de000, 0xc0002b2270, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/emitter.go:126 +0x208
main.(*emitter).Start.func3(0xc0002b6f90, 0xc0000c08c0, 0x7f1a3171b600, 0xc0002de000)
	/go/src/github.com/buger/goreplay/emitter.go:69 +0x9c
created by main.(*emitter).Start
	/go/src/github.com/buger/goreplay/emitter.go:67 +0x156

**Comment by gitmessage** [comment]
3306 is mysql prot

**Comment by urbanishimwe** [comment]
@gitmessage care to provide request headers that caused that issue?

**Comment by buger** [comment]
Hi! 

It can be related to the fact that you trying to catch MySQL binary protocol.

Can you explain your full use-case?

**Comment by gitmessage** [comment]
jack@jack-machine:~$ sudo ./gor --input-raw :3306 --input-raw-realip-header "X-Real-IP" --output-stdout
[sudo] jack 的密码： 
2021/01/12 14:41:27 [PPID 3220 and PID 3221] Version:1.2.0

（connect to mysql server 3306 use client）


panic: runtime error: slice bounds out of range [-1:]

goroutine 34 [running]:
github.com/buger/goreplay/byteutils.Insert(...)
	/go/src/github.com/buger/goreplay/byteutils/byteutils.go:20
github.com/buger/goreplay/proto.AddHeader(0xc0003a6000, 0x592, 0x700, 0xc00041ca40, 0x9, 0x20, 0xc00041ca20, 0xf, 0x20, 0xffffffffffffffff, ...)
	/go/src/github.com/buger/goreplay/proto/proto.go:174 +0x45d
github.com/buger/goreplay/proto.SetHeader(0xc0003a6000, 0x592, 0x700, 0xc00041ca40, 0x9, 0x20, 0xc00041ca20, 0xf, 0x20, 0x1742538, ...)
	/go/src/github.com/buger/goreplay/proto/proto.go:160 +0x4e7
main.(*RAWInput).Read(0xc0002ae000, 0xc000500000, 0x500000, 0x500000, 0x0, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/input_raw.go:120 +0x7de
main.CopyMulty(0xc00036a060, 0x7fd44c0a5008, 0xc0002ae000, 0xc000282290, 0x1, 0x1, 0x0, 0x0)
	/go/src/github.com/buger/goreplay/emitter.go:126 +0x208
main.(*emitter).Start.func3(0xc000358090, 0xc00007c910, 0x7fd44c0a5008, 0xc0002ae000)
	/go/src/github.com/buger/goreplay/emitter.go:69 +0x9c
created by main.(*emitter).Start
	/go/src/github.com/buger/goreplay/emitter.go:67 +0x156

**Comment by gitmessage** [comment]
mysql server (on docker)   、mysql client、 gor in seam vm machine.

**Comment by buger** [comment]
Hi! 

GoReplay at the moment can work only with HTTP traffic, so unfortunately it is not possible to work with MySQL at the moment.

Thanks!

**Comment by gitmessage** [comment]
Thanks
