### ISSUE TITLE
Frequently update Docker image on Docker Hub

### ISSUE THREAD

**Issue by rmasclef** [buger/goreplay#880]
Hi !

It seems that the [latest docker image version of goreplay available on DockerHub](https://hub.docker.com/r/buger/goreplay) is 4 years old.

It looks like there is no CI workflow that build & push docker image on each new release/tag (If you need any help I can prepare a PR that uses GithActions to do this).

Related to #451

**Comment by urbanishimwe** [comment]
@rmasclef PRs are welcomed :hugs:
