### ISSUE TITLE
POST body is truncated

### ISSUE THREAD

**Issue by talonx** [buger/goreplay#885]
Gor version v1.2.0

I'm seeing the request body getting truncated in my POST requests when sending (mirroring) the requests to another HTTP endpoint. This is with `-input-raw` and `--output-http`. The request body is pretty small, around 1kB, and I can see that the content length is set.

**Comment by buger** [comment]
Hi! Any chance you can attach tcpdump recording? 
Also can you try record to file, e.g. with --input-file, and check if it is broken too.

Thanks!

**Comment by talonx** [comment]
Hi, thanks for the response. I've been trying this in a K8S cluster, so it's not easy (possible?) to do a tcpdump there. I'll try it locally and with the file option too.

**Comment by talonx** [comment]
Locally (on my laptop), the same request body works. The Content-Length is correct (identical in both envs).

**Comment by buger** [comment]
Interesting 🤔 

It should be possible to ssh inside the pod https://kubernetes.io/docs/tasks/debug-application-cluster/get-shell-running-container/

If your k8s is running on a real server you can run tcpdump outside of the cluster, just by pointing to the container port.

Can you at least run it with `--verbose --debug` flags and show logs output?

Thanks!

**Comment by talonx** [comment]
I resolved it by setting `-input-raw-override-snaplen` - looks like that was the problem.

**Comment by Neurostep** [comment]
@talonx Hi. Can you share please on what env you are running the `goreplay`. So, you are running in k8s. Is this a cloud solution, like GKE, AKE or it is a bare metal solution? The thing is I bumped on a very similar issue with baremetal k8s installation, but the `-input-raw-override-snaplen` doesn't help here. Thus trying to narrow down the problem. Thanks

**Comment by talonx** [comment]
@Neurostep my env was GKE.
