### ISSUE TITLE
Return error when close file

### ISSUE THREAD

**Issue by ohDaddyPlease** [buger/goreplay#889]
[#69](https://github.com/buger/goreplay/blob/master/input_file.go#L69) in this case method always return only **nil**, and there is noway to return error, when closing file is failing. in some day it may cause some problems. is it incorrect and we need to add **return** statement to line [#72](https://github.com/buger/goreplay/blob/master/input_file.go#L72) or i'm wrong?
underhood the ReadCloser struct's [Close method](https://github.com/buger/goreplay/blob/dfbaf2c8081bd97c6db22fa9dd6f2ddd4e057682/input_file.go#L26)  return current [error](https://golang.org/pkg/io/#Closer)

there is same cases:

- [1](https://github.com/buger/goreplay/blob/3aec926ad9a25b57cc512223f4084371e7c0efac/limiter.go#L107) - we can return error from [Close](https://github.com/buger/goreplay/blob/3aec926ad9a25b57cc512223f4084371e7c0efac/limiter.go#L109), 
- [2](https://github.com/buger/goreplay/blob/3aec926ad9a25b57cc512223f4084371e7c0efac/output_file.go#L278) - we can collect and return errors from [#281](https://github.com/buger/goreplay/blob/3aec926ad9a25b57cc512223f4084371e7c0efac/output_file.go#L281) ([std Close](https://golang.org/pkg/compress/gzip/#Writer.Close)), [#283](https://github.com/buger/goreplay/blob/3aec926ad9a25b57cc512223f4084371e7c0efac/output_file.go#L283) ([std Flush](https://golang.org/pkg/bufio/#Writer.Flush)), [#285](https://github.com/buger/goreplay/blob/3aec926ad9a25b57cc512223f4084371e7c0efac/output_file.go#L285)

**Comment by ohDaddyPlease** [comment]
and maybe is it good idea to add [Discussions ](https://docs.github.com/en/discussions)? or Issues is completely fine for same questions?

**Comment by buger** [comment]
That's a very good point, and unfortunately I totally missed it...

Wanted to enable them for a long time (and just did it https://github.com/buger/goreplay/discussions)

**Comment by buger** [comment]
As for the topic itself, we need to think about it from user experience basis. 

As for now it looks like some edge case: if you were allowed to open the file, and allowed write to the file, what can be the reason if you can't close it?

But in any case, we should at least log the error.

**Comment by ohDaddyPlease** [comment]
> As for the topic itself, we need to think about it from user experience basis.
> 
> As for now it looks like some edge case: if you were allowed to open the file, and allowed write to the file, what can be the reason if you can't close it?
> 
> But in any case, we should at least log the error.

yeah, i got it. it's my fault, sorry :)
