### ISSUE TITLE
why does the input file rate not work? help

### ISSUE THREAD

**Issue by chenfpc** [buger/goreplay#893]
I'm just doing a simple test about goreplay. 
howerver I got a problem. 
a . I record traffic from the server with port 8030  into test.gor .   Here is my command.
     sudo ./gor --input-raw :8030 --output-file test.gor
b.  Then I replay the traffic into another server with port 8029. 
          sudo ./gor --input-file "test_0.gor|600%" --output-http "http://127.0.0.1:8029" --stats --output-http-stats --input-file-loop

But when I run the step b, It seems that the system with  port 8029 didn"t recevice requests and write any log .
   Howerver ,when I remove the phase "|600%" , just using 【sudo ./gor --input-file "test_0.gor|600%" --output-http "http://127.0.0.1:8029" --stats --output-http-stats --input-file-loop】， it works . The traffic from test_0.gor has replayed and the console write the log .

 So if there is something wrong with my command used ?  Need guidance . 

Here is the content of file "test_0.gor"

`1 aeb496b6165db3fad05c89b8 1611642131487022000 405000
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 575827e1-c8e8-4728-a348-a8284ecdd789
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49798165db3fb42fd3800 1611642133410560000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 72a80af5-03f5-47c3-a942-12a479e7918f
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49879165db3fbfcf59630 1611642136530622000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 8dec869a-5b48-4772-9893-573e6870fb98
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4995a165db3fc55d6da20 1611642138021780000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 7614d556-d6a9-4346-81e5-72f4d1a3cdca
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49a3b165db3fcb3e8f990 1611642139600026000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: f7a503ea-9858-4fa3-ad58-b34198c54213
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49b1c165db3fd1f4adbb8 1611642141401603000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: b5f85fd2-c1ea-46c6-907c-59c3b515df09
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49bfd165db3fd7db34cd0 1611642142985506000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: dc6bc125-a81c-441d-a9a6-5028242ded84
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49cde165db3fe1559d720 1611642145529780000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 7fd2ca61-2dc1-4e08-b42e-7ab44799f06c
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49dbf165db3fe77743090 1611642147175674000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 7e423460-1e1c-432a-b364-d40d94865183
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49ea0165db3fecd8adee8 1611642148620001000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 15312973-3d86-45e2-a6a2-b95b11d27d5b
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb49f81165db3ff50dfdf78 1611642150823387000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: ecb2da73-0d0c-4449-8259-e21c5ade2b36
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a062165db3ffcba75880 1611642152883280000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: b72f9a71-69b8-4c99-991b-b22d5c459f36
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a143165db40042f37220 1611642154884756000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 8d899e11-4c13-446e-95fb-caa84c32bb07
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a224165db400c0e13168 1611642156997489000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 8ce27332-c09d-45f3-a855-480129a5a269
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a305165db401419cce20 1611642159157268000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 3dc4ba33-7100-413e-8709-caebdc0a80d0
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a3e6165db401c60605a0 1611642161378756000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 0f0d4fe2-9b54-47f0-b8b1-7261dca1c33a
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a4c7165db40249a4b960 1611642163586972000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: 1a83fedb-add9-4677-bc7a-e109e57c8842
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉
1 aeb4a5a8165db402c5a16e78 1611642165667131000 0
POST /test HTTP/1.1
User-Agent: PostmanRuntime/7.26.8
Accept: */*
Postman-Token: c61e99f3-86bb-4b9d-a4c2-f5ac8d85de59
Host: localhost:8030
Accept-Encoding: gzip, deflate, br
Connection: keep-alive
Content-Length: 0

🐵🙈🙉`

**Comment by chenfpc** [comment]
v1.3.0_RC1 has the problem. 
The problem doesn't exists in latest release 1.2.0. 
So maybe this is a bug for v1.3.0_RC1...

**Comment by urbanishimwe** [comment]
@chenfpc did you find the solution?

**Comment by fengnex** [comment]
@chenfpc v1.2.0 also has the SAME problem, and ALL later versions have the SAME problem.
Is the above statement wrong OR how should we do in order to make it work?
