### ISSUE TITLE
Using same input and output port causes request duplication

### ISSUE THREAD

**Issue by fanfan520-debug** [buger/goreplay#918]
I think this [issue](https://github.com/buger/goreplay/issues/292) has reappeared again，I've tested various requests and it still recurs，But I use this [version](https://github.com/buger/goreplay/issues/292#issuecomment-224645655) and can get it fixed

**Comment by fanfan520-debug** [comment]
my cmd：
`sudo ./goreplay  -input-raw :8080  --output-http 'dst:8080' `

**Comment by buger** [comment]
Fixed in latest 1.3.0 release
