### ISSUE TITLE
GoReplay v1.3.0_RC1 has goroutine leak when replaying traffic

### ISSUE THREAD

**Issue by code4wt** [buger/goreplay#926]
GoReplay stat log:
<img src="https://user-images.githubusercontent.com/25877772/118385931-fe470d00-b645-11eb-8a2c-5f1835186684.png" width="50%" height="50%">

go ppref:
![image](https://user-images.githubusercontent.com/25877772/118385941-11f27380-b646-11eb-915e-bc3cc3383a5e.png)

**Comment by urbanishimwe** [comment]
I don't think this is a goroutine leak!
the line that print those stats is https://github.com/buger/goreplay/blob/master/gor_stat.go#L54
the information printed is https://github.com/buger/goreplay/blob/master/gor_stat.go#L58

the last stat(`gcount`) returns
> the number of goroutines that currently exist.

**Comment by code4wt** [comment]
> I don't think this is a goroutine leak!
> the line that print those stats is https://github.com/buger/goreplay/blob/master/gor_stat.go#L54
> the information printed is https://github.com/buger/goreplay/blob/master/gor_stat.go#L58
> 
> the last stat(`gcount`) returns
> 
> > the number of goroutines that currently exist.

I don't think so. Please read the Transport#dialConn function code. At the same time, go pprof can also show that a lot of goreplay is blocked on the readLoop and writeLoop functions.

```go
func (t *Transport) dialConn(ctx context.Context, cm connectMethod) (pconn *persistConn, err error) {
	pconn = &persistConn{....}
        // ......

	go pconn.readLoop()
	go pconn.writeLoop()
	return pconn, nil
}
```

**Comment by urbanishimwe** [comment]
> a lot of goreplay is blocked on the readLoop and writeLoop functions.

@code4wt  this is because the output HTTP code uses a single client with persist connection enabled!
one goroutine that sends requests may live as long goreplay is running and I think this is perfectly normal!
opening many file socket may cause file leaks!

**Comment by code4wt** [comment]
> opening many file socket may cause file leaks(and it did once)!

you are right, I have encountered this problem. error msg is as follows：
```text
[DEBUG][elapsed 1.000138155s]:
 output_http:0,0,0,325,325,3092
[DEBUG][elapsed 1.000139843s]:
 output_http:0,0,1,352,352,3048
[DEBUG][elapsed 162.021543ms]: [INPUT-FILE] err: "open /xyz/request_10.gor: too many open files"
[DEBUG][elapsed 27.39µs]: [INPUT-FILE] err: "open /xyz/request_11.gor: too many open files"
[DEBUG][elapsed 12.21µs]: [INPUT-FILE] err: "open /xyz/request_12.gor: too many open files"
[DEBUG][elapsed 11.534µs]: [INPUT-FILE] err: "open /xyz/request_13.gor: too many open files"
[DEBUG][elapsed 16.241µs]: [INPUT-FILE] err: "open /xyz/request_14.gor: too many open files"
......
```
