### ISSUE TITLE
Does capturing binary protocol supports --http-disallow-url option for filtering?

### ISSUE THREAD

**Issue by alchristleo** [buger/goreplay#928]
Hi, have a question regarding capturing binary protocol supports in pro version. Can we use the `--http-disallow-url` in goreplay to filter endpoint for `binary` protocol?

Example command:
```
/gor --input-raw :50000 --input-raw-protocol binary --output-file test.gor --http-disallow-url /xxx.xxx.Service/Login
```

Thanks.

**Comment by buger** [comment]
URL is an HTTP level variable. 
I assume you trying gRPC protocol?

**Comment by alchristleo** [comment]
> URL is an HTTP level variable.
> I assume you trying gRPC protocol?

Thanks for the replay @buger, yes correct this case is for gRPC, have you done so or do you have any suggestion how to filter binary protocol requests?

**Comment by buger** [comment]
Just to clarify, are you using gRPC though h2c, e.g. http2 without TLS?

In general purpose filtering for binary protocols not possible by nature.
You need to know a bit about protocol to make it work. 
And to be frank, http2 is way more complex than http1, parsing it will be harder.
I really want to add gRPC support for a long time, but it never fits to priority, so contributions are welcomed :)

**Comment by alchristleo** [comment]
> Just to clarify, are you using gRPC though h2c, e.g. http2 without TLS?
> 
> In general purpose filtering for binary protocols not possible by nature.
> You need to know a bit about protocol to make it work.
> And to be frank, http2 is way more complex than http1, parsing it will be harder.
> I really want to add gRPC support for a long time, but it never fits to priority, so contributions are welcomed :)

Yes I'm using without TLS one, thanks @buger for the explanation I will close this issue then
