### ISSUE TITLE
request id is not unique in the Recording file

### ISSUE THREAD

**Issue by liminbnm** [buger/goreplay#930]
If I send the request speed is fast, will have the follow problem，but send requst speed slow will not
Here's the command I recording file:
sudo ./gor --input-raw :80 --output-file home.gor
recorded file as follow:
![image](https://user-images.githubusercontent.com/15685871/118444443-b1376980-b71f-11eb-9cb2-224a6a15cde0.png)

**Comment by urbanishimwe** [comment]
@liminbnm  I'm curious as to what version you're using! this was fixed on master!

**Comment by liminbnm** [comment]
The version I use is v1.2.0

**Comment by urbanishimwe** [comment]
yes, that issue was on v1.2.0 but it was fixed!
