### ISSUE TITLE
real-time performance testing question

### ISSUE THREAD

**Issue by dujiang426** [buger/goreplay#931]
Can i specify multiple same` --output-http` to enlarge real-time request for performance testing? like below:

```
//Replay real-time request on 3x speed 
./gor --input-raw :80 --output-http "staging.com" --output-http "staging.com" --output-http "staging.com"
```

**Comment by urbanishimwe** [comment]
@dujiang426  that's a nice trick actually!

**Comment by buger** [comment]
Hi! 

In general yes you can, you will get requests duplicated, but if you fine with that, that's a valid way :)

**Comment by buger** [comment]
Also, worth noticing that there is an option called --split-output, which allows you to load balance between multiple outputs, instead of sending copy to each.
