### ISSUE TITLE
Goreplay sends the host name request

### ISSUE THREAD

**Issue by zhaofengocean** [buger/goreplay#934]
When I send the request in the file to traefik, I receive an exception that returns 404. When goreplay sends the request, it does not bring the Host request header? How can I solve this problem? thank

gor:
`./gor  --input-file request.gor  --http-original-host --http-rewrite-header "Host(.*),x1\$1"  --output-http http://10.1.0.3:80
`

log:
`10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/order/selectWaitConfirmOrderList HTTP/1.1" 404 19 "-" "-" 3665 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/common/getRunStrategy HTTP/1.1" 404 19 "-" "-" 3663 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/order/current HTTP/1.1" 404 19 "-" "-" 3664 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3662 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3668 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3669 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/log/collect HTTP/1.1" 404 19 "-" "-" 3667 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:17 +0000] "POST /api/app/order/waitOrderInfo HTTP/1.1" 404 19 "-" "-" 3670 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/common/indexAd HTTP/1.1" 404 19 "-" "-" 3671 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/order/selectWaitConfirmOrderList HTTP/1.1" 404 19 "-" "-" 3672 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/common/indexAd HTTP/1.1" 404 19 "-" "-" 3674 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3673 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3675 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/activity/getFootInfo HTTP/1.1" 404 19 "-" "-" 3676 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/common/getUrl HTTP/1.1" 404 19 "-" "-" 3677 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/u/updateAppInfo HTTP/1.1" 404 19 "-" "-" 3679 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3678 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3680 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3684 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/collect HTTP/1.1" 404 19 "-" "-" 3686 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/log/appCalorie HTTP/1.1" 404 19 "-" "-" 3682 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/driver/getDriverAuditInfo HTTP/1.1" 404 19 "-" "-" 3685 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/activity/driverAvailableActivity HTTP/1.1" 404 19 "-" "-" 3681 - - 0ms
10.0.72.0 - - [02/Jun/2021:13:06:18 +0000] "POST /api/app/activity/getFootInfo HTTP/1.1" 404 19 "-" "-" 3683 - - 0ms
`

**Comment by buger** [comment]
Hi! 

Is the Host header inside the requests.gor file?
Can you put here example recorded request?

Also what are you trying to do with the following argument: `"Host(.*),x1\$1"`?

**Comment by zhaofengocean** [comment]
hi. I'm very glad to hear from you
"Host(.*),x1\$1"：  In my traefik configuration, all the hostnames are domain names starting with x1



`1 0cdbc978ff232fb4e4ae6e361847166674c37fab 1622639948322503694
POST /api/app/log/appCalorie HTTP/1.1
Connection: close
Content-Length: 1098
RemoteIp: 112.224.67.11
X-Forwarded-Proto: https
user-agent: okhttp/3.12.0
x-b3-spanid: a1f2b71b28d5fd79
x-b3-traceid: 5ddc6d3d4372141b
Host: x1xdriver2.traefikxxxxxx.com
X-Forwarded-For: 112.224.67.11
accept-encoding: gzip
content-type: application/x-www-form-urlencoded

brand=vivo&token=e06a18dd0b80ca62abef117c8c35e219
1 b7999a18151201c9529a2378a15eca89a4d242de 1622639948322541594
POST /athena/api/app/driver/goods/selectGoodsInfo HTTP/1.1
Host: x1xdriver2.traefikxxxxxx.com
RemoteIp: 117.136.31.90
accept: */*
accept-language: zh-Hans-CN;q=1.0
content-type: application/x-www-form-urlencoded
cookie: sensorsdata2015jssdkcross=%7B%22distinct_id%22%3A%22HY886243%22%2C%22first_id%22%3A%22179ac7857b84c3-021bbc77b40dfe-8260f7b-304500-179ac7857b93fb%22%2C%22props%22%3A%7B%22%24latest_traffic_source_type%22%3A%22%E7%9B%B4%E6%8E%E6%B5%81%E9%87%8F%22%2C%22%24latest_search_keyword%22%3A%22%E6%9C%AA%E5%8F%96%E5%88%B0%E5%80%BC_%E7%9B%B4%E6%8E%A5%E6%89%93%E5%BC%80%22%2C%22%24latest_referrer%22%3A%22%22%7D%2C%22%24device_id%22%3A%22179ac7857b84c3-021bbc77b40dfe-8260f7b-304500-179ac7857b93fb%22%7D; userId=886243
head_key_traceid: B990F951-9F2C-4D98-98C9-063A44FAB818
Connection: close
Content-Length: 538
X-Forwarded-For: 117.136.31.90
X-Forwarded-Proto: https
accept-encoding: br;q=1.0, gzip;q=0.9, deflate;q=0.8
user-agent: FYDriverNew/6.24.0 (com.foryou.FYLucky; build:1096; iOS 14.3.0) Alamofire/5.4.3

X-B3-SpanId=d91c70e4bd6d4a97&X-B3-TraceId=bbc526b4657cae44
1 86e0272ecace933a1b6acc67c6ad4c8f8f71a30f 1622639948322552542
POST /api/app/log/appCalorie HTTP/1.1
user-agent: okhttp/3.12.0
x-b3-traceid: dedccf50c64b60f2
Connection: close
Content-Length: 1145
RemoteIp: 123.139.84.223
X-Forwarded-For: 123.139.84.223
X-Forwarded-Proto: https
accept-encoding: gzip
Host: x1xdriver2.traefikxxxxxx.com
content-type: application/x-www-form-urlencoded
x-b3-spanid: 11e6e9ba83f806e8

brand=OPPO&token=0&uid=957916&reqTimestamp=1622639947&signature=d9b5453937d4d88a2fb89a8afb1ebaae&appKey=24b7e468611fc912f1f4ce22e9e8a463&nonce=1539143174
1 05f85d1fdfa1e40926134e22ce4949a8a852b9dc 1622639948322446356
POST /api/app/activity/activityShare HTTP/1.1
x-b3-traceid: 3d35b89e5aa41b67
Connection: close
RemoteIp: 171.82.101.89
accept-encoding: gzip
content-type: application/x-www-form-urlencoded
x-b3-spanid: 8941d468e48705c3
Content-Length: 373
Host: x1xdriver2.traefikxxxxxx.com
X-Forwarded-For: 171.82.101.89
X-Forwarded-Proto: https
user-agent: okhttp/3.12.0

token=8ebffa5dca77ced60b7fae3481eed450&appVersion=6.24.0&channalType=1&network=2&osType=1

1 63ab7e96797c339facdd8098931daf068657eb5a 1622639948322527402
POST /api/mini/order/queryRemindBidPrice?appKey=&reqTimestamp=1622639946&nonce=187947&signature= HTTP/1.1
Content-Length: 58
EagleEye-TraceId: 7b39758816226399475737091e1504
Referer: https://wx870dec2be262fc2b/66/page-frame.html
X-Forwarded-For: 36.28.194.151, 123.57.117.136
Host: x1xcustomer2.traefikxxxxxx.com
Web-Server-Type: nginx
content-type: application/x-www-form-urlencoded
Accept-Encoding: gzip,compress,br,deflate
WL-Proxy-Client-IP: 36.28.194.151
X-Forwarded-Cluster: waf,
X-Forwarded-Proto: https
X-Real-IP: 36.28.194.151
X-True-IP: 36.28.194.151
charset: utf-8
Connection: close
RemoteIp: 123.57.117.136
User-Agent: Mozilla/5.0 (Linux; Android 11; PEGM10 Build/RKQ1.201217.002; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/78.0.3904.62 XWEB/2797 MMWEBSDK/20210302 Mobile Safari/537.36 MMWEBID/3842 MicroMessenger/8.0.3.1880(0x2800033D) Process/appbrand0 WeChat/arm64 Weixin NetType/4G Language/zh_CN ABI/arm64 MiniProgramEnv/android
eagleeye-rpcid: 0.1

token=8f7615a95acbc8a85f61c337d77b91ff&serviceVersion=2110
`

**Comment by buger** [comment]
Which version of GoReplay do you use?

Also it is still not clear for me why you use `--http-rewrite-header ` argument, since all your recorded hostnames already start with "x"?

**Comment by zhaofengocean** [comment]
GoReplay Version: 1.1.0
The header you see is after rewrite. It's not raw data

**Comment by buger** [comment]
@zhaofengocean I saw you closed it. Have you solved the issue?
