### ISSUE TITLE
replay question

### ISSUE THREAD

**Issue by liujinyubro** [buger/goreplay#945]
Hi,
  I encountered a problem when referring to your project. I recorded the traffic of project A to the file request. gor, and then I want to replay the requests in this file to project B. However, the context of these two projects is different. Is there any way to solve this problem?

Thanks!

**Comment by buger** [comment]
Hi! Can you add more info pls? It is not clear what is the actual error?

**Comment by liujinyubro** [comment]
Thank you for your reply ! It is not error,It's just a requirement for my scene.
I would like to ask if there is such a way to use it.The context root of project a is 'pcms_query', the context root of project B is 'pcms'. I want to specify the context of the request to be changed to 'pcms' during traffic playback.
![Uploading 20210622172122.png…]()

**Comment by buger** [comment]
(image not get uploaded)

**Comment by liujinyubro** [comment]
uh ,my network is poor, I tried many times to upload image ,but not sucess yet. 
My question is actually very simple. Can I change the request path when using the file for traffic playback? For example, the request path recorded in the.gor file is '/query/api1', and can I change it to '/uniquery/api2' when playing back?

**Comment by liujinyubro** [comment]
I manually replace the request path in the generated  .gor file to the path I want, and then when I use the modified .gor file for traffic playback, It directly prompt 'the end of file request.gor', and I don't receive any request in the request.gor file

**Comment by buger** [comment]
I guess what you are looking is ` --http-rewrite-url` argument https://github.com/buger/goreplay/wiki/Request-rewriting

**Comment by liujinyubro** [comment]
Yes! That is the solution of my issue.Thanks a lot.
