### ISSUE TITLE
Can support HTTP2 

### ISSUE THREAD

**Issue by zhangxiumei99** [buger/goreplay#948]
Which version supports？and if not, When do you plan to support

**Comment by buger** [comment]
It is a tricky one. 
The thing is that GoReplay right now have strict limitation that it can't capture HTTPS traffic (by nature it is encrypted).
And based on my experience, the majority of servers require you to have HTTPS on top of HTTP2. Even browsers do not support HTTP2 without TLS https://stackoverflow.com/questions/46788904/why-do-web-browsers-not-support-h2c-http-2-without-tls

However, TLS by itself is rarely handled by the application itself, and usually lives on proxy or load balancer level. 
So in the majority of situations you have a flow like this:
Client -----HTTP2 (with TLS)-----> Load Balancer ----HTTP1.1 ----> Application 

E.g. application themselves usually deployed using HTTP1.1 anyway, and GoReplay already supports it.

The only active used of HTTP2 without TLS (usually called h2c), in GRPC world, but it is pretty specific niche. 

Does it make sense to you? Or maybe you have a use-case which i'm missing?
Thanks!

**Comment by buger** [comment]
I will close it, if you have more comments feel free to add.

**Comment by zhangxiumei99** [comment]
ok，thank you very much


发送自JoyMail 京东企业邮箱
________________________________
发件人: Leonid Bugaev ***@***.***>
发送时间: 2021年7月1日 1:12:02
收件人: buger/goreplay
抄送: 张秀梅; Author
主题: Re: [buger/goreplay] Can support HTTP2 (#948)


I will close it, if you have more comments feel free to add.

―
