### ISSUE TITLE
--output-http-redirects option can not follow 302 location

### ISSUE THREAD

**Issue by wsm1988** [buger/goreplay#954]
My origin response contains 302 location.,   I use --output-http-redirects 4  , but I find it can not follow 302 location, why? can you help me?

**Comment by buger** [comment]
Hi! Try adding ` --verbose 2 ` flag, and check for  log lines with `[HTTPCLIENT] ` prefix

**Comment by wsm1988** [comment]
thank you for your replay.

adding --verbose 2 flag, the result is as follow:
![image](https://user-images.githubusercontent.com/86662270/123892908-00fb8880-d98e-11eb-8204-9586e70d7444.png)

**Comment by buger** [comment]
I think you are using pretty old GoReplay version. It even does not detect redirect.

**Comment by wsm1988** [comment]
oh，you are right！
thank you very very much!

**Comment by buger** [comment]
I will close this issue. Feel free to re-open :)
