### ISSUE TITLE
How do I disable Mac Filter?

### ISSUE THREAD

**Issue by laybatin** [buger/goreplay#955]
version : v1.3.0_RC6
os : mac

I want to process all packets through packet shading.(Like aws vpc mirroring)

When I used Stable 1.2, I handled all packets coming into port 80, but now I think it only handles packets coming into my Mac Address and IP address.

Terminal 1
```
sudo gor --input-raw-bpf-filter 'tcp' --input-raw-promisc --input-raw en0:80 --output-file requests.log
```

Terminal 2
```
sudo tcpreplay -i en0 -M 10 b.pcap
```

In Stable 1.2, the HTTP protocol in the file was logged to requests.log, but it is not working now.

I think it's because the bpf filter is applied, but even if you add the bpf filter parameter, it is automatically applied as below.

```
Interface: en0 . BPF Filter: ((tcp dst portrange 0-65535) and (dst host Mac Address or dst host Ip Address))
```

**Comment by buger** [comment]
Hi! Indeed, it was a bug, just fixed it in master `2b993ed`. 
The idea here is that for majority of the users having detailed BPF rule more beneficial, it is faster and bring less unwanted traffic (for example what if your application doing outbound calls with the same port).
But more advanced users can bring their own bpf filter.

Also, I do not think that it is related to Mac address.
> Interface: lo0 . BPF Filter: ((tcp dst port 8080) and (dst host 127.0.0.1 or dst host ::1 or dst host fe80::1))
`fe80::1` is one of the IPv6 addresses of this interface. 

I'm really curious about your use-case and how you're using packet shading! 
Am I right that if smth like `aws vpc mirroring` is used, you can deploy GoReplay even outside of application servers, which sounds very powerful. And as I understand it works for outbound traffic as well (e.g. for tracking responses)?
Also how you were able to forward this traffic to your local mac?

Thank you!

**Comment by buger** [comment]
PS.

Here is the latest mac build.
[gor_DEV-1625120884_mac.tar.gz](https://github.com/buger/goreplay/files/6745888/gor_DEV-1625120884_mac.tar.gz)

**Comment by laybatin** [comment]
Thank you for your quick response.
I'm using aws and I'm serving several products inside the vpc.

We wanted to test the service with traffic from real users, not mockup users based on scenarios, such as jmeter, using aws vpc mirroring function.

The file was saved and imported into the local Mac by running tcpdump on ec2 instance.

I thought about the environment for the test as the image below.
I think it will be possible if we see what we can handle for all the packets.
Please let me know if you have a better idea.


![스크린샷 2021-07-01 오후 5 49 34](https://user-images.githubusercontent.com/5277053/124095716-e829ca80-da94-11eb-8341-b93a98e113ee.png)




And.. I have a question.
Is it correct to run gor on each service instance?
service1-0 on gor
service1-1 on gor
service1-2 on gor
service2-0 on gor
.......


We don't use a proxy like nginx, we use aws' alb.
If you use nginx, you can run gor on that instance, but if not, should you run it on each instance?
