### ISSUE TITLE
couldn't load wpcap.dll

### ISSUE THREAD

**Issue by 89z** [buger/goreplay#967]
If I run this command:

~~~
gor --input-raw :8000 --output-stdout
~~~

I get this result:

~~~
2021/07/17 21:35:24 couldn't load wpcap.dll
~~~

**Comment by buger** [comment]
Hi! 

In order to work on windows you need install npcap https://nmap.org/npcap/
https://github.com/buger/goreplay/wiki/Running-on-Windows

**Comment by 89z** [comment]
I downloaded this file:

https://nmap.org/dist/nmap-7.91-win32.zip

but that DLL doesnt exist:

~~~
PS C:\nmap-7.91-win32\nmap-7.91> fd dll
libcrypto-1_1.dll
libssh2.dll
libssl-1_1.dll
zlibwapi.dll
~~~

**Comment by buger** [comment]
I think you may need to use installer.
When you install npcap that way, it has "WinpCap compatibility mode" which adds needed libraries.

**Comment by 89z** [comment]
oh FFS, they dont offer a zip file. Man that project is an old piece of crap. As a workaround, it seems you can extract this with 7-Zip or similar:

https://nmap.org/npcap/dist/npcap-1.50.exe

**Comment by buger** [comment]
Well, npcap is the only commercially supported and active project for the windows.
The project itself is actually quite active https://github.com/nmap/npcap/blob/master/CHANGELOG.md
