### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by yaowenqiang** [buger/goreplay#971]
Version:1.2.0

**Comment by yaowenqiang** [comment]
> Version:1.2.0

uname -a
Linux 2.6.32-431.el6.x86_64 #1 SMP Fri Nov 22 03:15:09 UTC 2013 x86_64 x86_64 x86_64 GNU/Linux
cat /etc/issue
CentOS release 6.5 (Final)
Kernel \r on an \m

**Comment by buger** [comment]
It is 12 years old kernel, and CenOS 6.5 is already EOL.  

The only workaround I can imagine try using older GoReplay like 0.16, maybe it will work. 
The other workaround will be recording traffic using tcpdump, and after feeding it to GoReplay like this: 

`--input-raw ./traffic.pcap --input-raw-engine pcap_file`

**Comment by yaowenqiang** [comment]
version 0.16 works
