### ISSUE TITLE
 use --http-rewrite-url  makes the recording  file missing characters

### ISSUE THREAD

**Issue by hkun0120** [buger/goreplay#977]
my gor script is : ./gor --input-raw-track-response --input-raw :7001  --output-kafka-json-format --http-allow-url /pcms_query/services/UniQueryWebService  --http-rewrite-url /pcms_query/services/UniQueryWebService:/pcms/uniqueryouterweb/rest/replay/flowReplay --output-file-append --output-file %Y%m%d.log

And the error record file is like this,  " &gt;120000&lPOST /pcms_query/   " ,
the correct one should like this:        "&gt;120000&lt;/BRANCH_&gt;        /POST /pcms_query/ "
some characters are missing ,I want to know  how to repair this ? Have any problem is my script?

<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><cl:HEADER xmlns:cl="http://www.e-chinalife.com/soa/"><SVCNAME>UniQueryWebServiceCsbps</SVCNAME><SVCCODE>PCMS-1001</SVCCODE><SVCVER>1.0</SVCVER><ORISYS>CSBPS</ORISYS><TRANTIME>2021-07-29 14:34:53</TRANTIME><TRANNO>20210729143453800</TRANNO><FROMSYS>CSBPS</FROMSYS><AUTH><BRANCHNO></BRANCHNO><USERID></USERID><TOKENID></TOKENID></AUTH><SECURITY><SIGNATURE>10</SIGNATURE></SECURITY><ROUTE><BRANCHNO>000000</BRANCHNO><DESTSYS>PCMS</DESTSYS></ROUTE></cl:HEADER></soap:Header><soap:Body><getQueryResult xmlns="http://www.e-chinalife.com/soa/"><args0>&lt;ROOT&gt;&lt;HEADER&gt;&lt;TRANS_NO&gt;20210729143453752712802&lt;/TRANS_NO&gt;&lt;SERV_CODE&gt;215&lt;/SERV_CODE&gt;&lt;USERNAME&gt;csbpsuser&lt;/USERNAME&gt;&lt;PASSWORD&gt;csbpspwd&lt;/PASSWORD&gt;&lt;/HEADER&gt;&lt;BODY&gt;&lt;PARAM&gt;&lt;ROUTER&gt;&lt;SYS_NO&gt;4&lt;/SYS_NO&gt;&lt;BRANCH_NO&gt;000000&lt;/BRANCH_NO&gt;&lt;/ROUTER&gt;&lt;CONDITION xsi:type="mioCondition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;CNTR_NO&gt;2018120106290000004534&lt;/CNTR_NO&gt;&lt;END&gt;500&lt;/END&gt;&lt;BEGIN&gt;1&lt;/BEGIN&gt;&lt;/CONDITION&gt;&lt;/PARAM&gt;&lt;PARAM&gt;&lt;ROUTER&gt;&lt;SYS_NO&gt;4&lt;/SYS_NO&gt;&lt;BRANCH_NO&gt;000000&lt;/BRANCH_NO&gt;&lt;/ROUTER&gt;&lt;CONDITION xsi:type="mioCondition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;CNTR_NO&gt;2018120106290000004521&lt;/CNTR_NO&gt;&lt;END&gt;500&lt;/END&gt;&lt;BEGIN&gt;1&lt;/BEGIN&gt;&lt;/CONDITION&gt;&lt;/PARAM&gt;&lt;PARAM&gt;&lt;ROUTER&gt;&lt;SYS_NO&gt;1&lt;/SYS_NO&gt;&lt;BRANCH_NO&gt;120000&lPOST /pcms_query/services/UniQueryWebService?wsdl HTTP/1.1^M

SOAPAction: "getQueryResult"^M

User-Agent: Apache-CXF/3.3.6^M

Accept: */*^M

Content-Type: text/xml; charset=UTF-8^M

Connection: keep-alive^M

Pragma: no-cache^M

Cache-Control: no-cache^M

Content-Length: 2282^M

Content-Encoding: UTF-8^M

Host: 10.30.59.76:7001^M

^M
============================

when I not using rewrite command ,the correct one is like below,pay attention to the BOLD part 
<soap:Envelope xmlns:soap="http://schemas.xmlsoap.org/soap/envelope/"><soap:Header><cl:HEADER xmlns:cl="http://www.e-chinalife.com/soa/"><SVCNAME>UniQueryWebServiceCsbps</SVCNAME><SVCCODE>PCMS-1001</SVCCODE><SVCVER>1.0</SVCVER><ORISYS>CSBPS</ORISYS><TRANTIME>2021-07-29 11:22:00</TRANTIME><TRANNO>B24B2FE5DB90498D9D52E6A0F7CDA201</TRANNO><FROMSYS>CSBPS</FROMSYS><AUTH><BRANCHNO></BRANCHNO><USERID></USERID><TOKENID></TOKENID></AUTH><SECURITY><SIGNATURE>10</SIGNATURE></SECURITY><ROUTE><BRANCHNO>000000</BRANCHNO><DESTSYS>PCMS</DESTSYS></ROUTE></cl:HEADER></soap:Header><soap:Body><getQueryResult xmlns="http://www.e-chinalife.com/soa/"><args0>&lt;ROOT&gt;&lt;HEADER&gt;&lt;TRANS_NO&gt;20210729112200031917480&lt;/TRANS_NO&gt;&lt;SERV_CODE&gt;201&lt;/SERV_CODE&gt;&lt;USERNAME&gt;csbpsuser&lt;/USERNAME&gt;&lt;PASSWORD&gt;csbpspwd&lt;/PASSWORD&gt;&lt;/HEADER&gt;&lt;BODY&gt;&lt;PARAM&gt;&lt;ROUTER&gt;&lt;SYS_NO&gt;4&lt;/SYS_NO&gt;&lt;BRANCH_NO&gt;120101&lt;/BRANCH_NO&gt;&lt;/ROUTER&gt;&lt;CONDITION xsi:type="cntrBasicCondition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;BEGIN&gt;1&lt;/BEGIN&gt;&lt;END&gt;100&lt;/END&gt;&lt;CNTR_NO&gt;2019120101U22000001023&lt;/CNTR_NO&gt;&lt;IPSN_NO&gt;0&lt;/IPSN_NO&gt;&lt;/CONDITION&gt;&lt;/PARAM&gt;&lt;PARAM&gt;&lt;ROUTER&gt;&lt;SYS_NO&gt;4&lt;/SYS_NO&gt;&lt;BRANCH_NO&gt;120101&lt;/BRANCH_NO&gt;&lt;/ROUTER&gt;&lt;CONDITION xsi:type="cntrBasicCondition" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"&gt;&lt;BEGIN&gt;1&lt;/BEGIN&gt;&lt;END&gt;100&lt;/END&gt;&lt;CNTR_NO&gt;2019120101U24000001032&lt;/CNTR_NO&gt;&lt;IPSN_NO&gt;0&lt;/IPSN_NO&gt;&lt;/CONDITION&gt;&lt;/POST /pcms_query/services/UniQueryWebService?wsdl HTTP/1.1^M

SOAPAction: "getQueryResult"^M

User-Agent: Apache-CXF/3.3.6^M

Accept: */*^M

Content-Type: text/xml; charset=UTF-8^M

Connection: keep-alive^M

Pragma: no-cache^M

Cache-Control: no-cache^M

Content-Length: 1764^M

Content-Encoding: UTF-8^M

Host: 10.30.59.76:7001^M

**Comment by hkun0120** [comment]
I use the 1.1.3RC5 to reduce the missing situation. But when I use 1.1.3 RC6, ./gor  error happens.
![image](https://user-images.githubusercontent.com/3326406/127678697-8326ecd0-d423-41b2-9f69-c95d11699314.png)

**Comment by buger** [comment]
Hi! Apologies for the delay!

In general, it looks like a bug. Any chance you can give me repeatable case, and record original traffic via tcpdump into pcap file or similar? 

> I use the 1.1.3RC5 to reduce the missing situation.

You mean to reproduce? E.g. this version has a bug?

**Comment by hkun0120** [comment]
> Hi! Apologies for the delay!
> 
> In general, it looks like a bug. Any chance you can give me repeatable case, and record original traffic via tcpdump into pcap file or similar?
> 
> > I use the 1.1.3RC5 to reduce the missing situation.
> 
> You mean to reproduce? E.g. this version has a bug?

no，1.1.3_RC5 this version fix the bug, and the record and  replay is perfect now.

**Comment by hkun0120** [comment]
change the version,and you will be ok

**Comment by buger** [comment]
perfect 👌🏻
