### ISSUE TITLE
Wrong elasticsearch URL format. Expected to be: scheme://host/index_ Name

### ISSUE THREAD

**Issue by hkun0120** [buger/goreplay#993]
When I use version 1.1.3 release to import data into es, I use the command sudo. / gor - input raw: 8000 - output HTTP ' http://something '- output http elasticsearch' 10.30.11.120:9200 / gor ', prompt me can't initialize elasticsearch plugin. Wrong elasticsearch URL format. Expected to be: scheme://host/index_ Name. When I change to '' http://10.30.11.120:9200/gor 'or after' es: / / 10.30.11.120:9200 / gor ', ES does not automatically create gor index. After I manually create the index, there is no data entry. Is there any error?

**Comment by holysor** [comment]
same question

**Comment by zsz001** [comment]
same question
but i prepared the index gor***, and then used "--output-http-elasticsearch scheme://esip/gor***" ,it worked
but ..... no data in

**Comment by Ammyz** [comment]
> ES does not automatically create gor index. After I manually create the index, there is no data entry. Is there any error?
i have the same problem

**Comment by hkun0120** [comment]
wowow
